// SPDX-License-Identifier: GPL-3.0-or-later
// CR 704.5 state-based action engine. sweep() collects every applicable
// SBA, applies all of them simultaneously (CR 704.3), records the batch,
// re-checks, loops to fixpoint. Returns the list of batches applied.
//
// Task 29 provides the skeleton + fixpoint loop; Tasks 30-32 populate
// `collectApplicable` + apply-dispatch per kind.
//
// Integration: Task 40's runPriorityWindow will call
//   const batches = yield* this.game.sbaEngine.sweep();
// and drain trigger queue after each batch.
import { mkEvent } from "@mtg-forge-ts/core";
import type { EngineYield } from "../action/engine-yield.js";
import type { Game } from "../game.js";
import type { SbaAction } from "./sba-action.js";

export class SbaEngine {
  // WHY bound: MTG rules guarantee that SBA sweeps terminate (every SBA
  // strictly reduces some observable: card counts on battlefield, counters
  // on a card, etc.). This cap catches engine bugs (a collector that
  // re-emits the same action without mutating state).
  static readonly MAX_ITERATIONS = 100;

  constructor(protected readonly game: Game) {}

  *sweep(): Generator<EngineYield, readonly (readonly SbaAction[])[], unknown> {
    const batches: (readonly SbaAction[])[] = [];
    for (let iter = 0; iter < SbaEngine.MAX_ITERATIONS; iter++) {
      const actions = this.collectApplicable();
      if (actions.length === 0) {
        return batches;
      }
      yield* this.applyBatch(actions);
      batches.push(actions);
      yield {
        kind: "event",
        event: mkEvent("StateBasedActionApplied", this.game.turn, this.game.phase, {
          actionCount: actions.length,
        }),
      };
    }
    throw new Error(`SbaEngine.sweep: exceeded ${SbaEngine.MAX_ITERATIONS} iterations — likely bug`);
  }

  // Tasks 30-32 populate the per-category collectors. Keeping them as
  // protected methods lets test subclasses override collectApplicable
  // (or specific helpers) without touching production code.
  protected collectApplicable(): SbaAction[] {
    const out: SbaAction[] = [];
    this.collectLossConditions(out);
    this.collectCreatureRemoval(out);
    this.collectLegendWorld(out);
    this.collectTokenAndCopy(out);
    this.collectPhasedOwnerLeaves(out);
    this.collectAttachmentLegality(out);
    this.collectCounterCancel(out);
    this.collectSagaAndClass(out);
    this.collectBestow(out);
    this.collectCommander(out);
    return out;
  }

  protected collectLossConditions(_out: SbaAction[]): void {
    /* Task 30 */
  }
  protected collectCreatureRemoval(_out: SbaAction[]): void {
    /* Task 30 */
  }
  protected collectLegendWorld(_out: SbaAction[]): void {
    /* Task 31 */
  }
  protected collectTokenAndCopy(_out: SbaAction[]): void {
    /* Task 31 */
  }
  protected collectPhasedOwnerLeaves(_out: SbaAction[]): void {
    /* Task 31 */
  }
  protected collectAttachmentLegality(_out: SbaAction[]): void {
    /* Task 31 */
  }
  protected collectCounterCancel(_out: SbaAction[]): void {
    /* Task 32 */
  }
  protected collectSagaAndClass(_out: SbaAction[]): void {
    /* Task 32 */
  }
  protected collectBestow(_out: SbaAction[]): void {
    /* Task 32 */
  }
  protected collectCommander(_out: SbaAction[]): void {
    /* Task 32 */
  }

  *applyBatch(actions: readonly SbaAction[]): Generator<EngineYield, void, unknown> {
    // CR 704.3 — all applicable SBAs in one check apply simultaneously.
    // We apply sequentially but don't re-check until the batch completes.
    // Triggers generated by each apply queue via Game.emitEvent; they drain
    // at the next priority window (Task 40).
    for (const action of actions) {
      yield* this.apply(action);
    }
  }

  protected *apply(action: SbaAction): Generator<EngineYield, void, unknown> {
    // Task 29 skeleton — Tasks 30-32 replace with an exhaustive switch
    // + `const _: never = action` guard. The void-read keeps the
    // parameter referenced so biome/ts don't flag it as unused.
    void action;
    return;
    // biome-ignore lint/correctness/useYield: placeholder body; Task 30-32 add yields
  }
}
