// SPDX-License-Identifier: GPL-3.0-or-later
// CR 704.5 state-based action engine. sweep() collects every applicable
// SBA, applies all of them simultaneously (CR 704.3), records the batch,
// re-checks, loops to fixpoint. Returns the list of batches applied.
//
// Integration: Task 40's runPriorityWindow will call
//   const batches = yield* this.game.sbaEngine.sweep();
// and drain trigger queue after each batch.
import { ZoneType, mkEvent } from "@mtg-forge-ts/core";
import type { PhaseStep, PlayerSeat } from "@mtg-forge-ts/core";
import type { EngineYield } from "../action/engine-yield.js";
import type { Game } from "../game.js";
import type { TerminalState } from "../terminal-state.js";
import { collectCreatureRemoval } from "./creature-removal.js";
import { collectLossConditions } from "./loss-conditions.js";
import type { SbaAction } from "./sba-action.js";

// The PlayerLost event's reason taxonomy is fixed (CR 104.3 / event.ts).
type LossReason = "life" | "decked" | "poison" | "concede" | "effect";

export class SbaEngine {
  // WHY bound: MTG rules guarantee that SBA sweeps terminate (every SBA
  // strictly reduces some observable: card counts on battlefield, counters
  // on a card, etc.). This cap catches engine bugs (a collector that
  // re-emits the same action without mutating state).
  static readonly MAX_ITERATIONS = 100;

  constructor(protected readonly game: Game) {}

  *sweep(): Generator<EngineYield, readonly (readonly SbaAction[])[], unknown> {
    const batches: (readonly SbaAction[])[] = [];
    for (let iter = 0; iter < SbaEngine.MAX_ITERATIONS; iter++) {
      const actions = this.collectApplicable();
      if (actions.length === 0) {
        return batches;
      }
      yield* this.applyBatch(actions);
      batches.push(actions);
      yield {
        kind: "event",
        event: mkEvent("StateBasedActionApplied", this.game.turn, this.game.phase, {
          actionCount: actions.length,
        }),
      };
    }
    throw new Error(`SbaEngine.sweep: exceeded ${SbaEngine.MAX_ITERATIONS} iterations — likely bug`);
  }

  // Tasks 30-32 populate the per-category collectors. Keeping them as
  // protected methods lets test subclasses override collectApplicable
  // (or specific helpers) without touching production code.
  protected collectApplicable(): SbaAction[] {
    const out: SbaAction[] = [];
    this.collectLossConditions(out);
    this.collectCreatureRemoval(out);
    this.collectLegendWorld(out);
    this.collectTokenAndCopy(out);
    this.collectPhasedOwnerLeaves(out);
    this.collectAttachmentLegality(out);
    this.collectCounterCancel(out);
    this.collectSagaAndClass(out);
    this.collectBestow(out);
    this.collectCommander(out);
    return out;
  }

  protected collectLossConditions(out: SbaAction[]): void {
    collectLossConditions(this.game, out);
  }
  protected collectCreatureRemoval(out: SbaAction[]): void {
    collectCreatureRemoval(this.game, out);
  }
  protected collectLegendWorld(_out: SbaAction[]): void {
    /* Task 31 */
  }
  protected collectTokenAndCopy(_out: SbaAction[]): void {
    /* Task 31 */
  }
  protected collectPhasedOwnerLeaves(_out: SbaAction[]): void {
    /* Task 31 */
  }
  protected collectAttachmentLegality(_out: SbaAction[]): void {
    /* Task 31 */
  }
  protected collectCounterCancel(_out: SbaAction[]): void {
    /* Task 32 */
  }
  protected collectSagaAndClass(_out: SbaAction[]): void {
    /* Task 32 */
  }
  protected collectBestow(_out: SbaAction[]): void {
    /* Task 32 */
  }
  protected collectCommander(_out: SbaAction[]): void {
    /* Task 32 */
  }

  *applyBatch(actions: readonly SbaAction[]): Generator<EngineYield, void, unknown> {
    // CR 704.3 — all applicable SBAs in one check apply simultaneously.
    // We apply sequentially but don't re-check until the batch completes.
    // Triggers generated by each apply queue via Game.emitEvent; they drain
    // at the next priority window (Task 40).
    for (const action of actions) {
      yield* this.apply(action);
    }
  }

  protected *apply(action: SbaAction): Generator<EngineYield, void, unknown> {
    switch (action.kind) {
      case "playerLosesLifeZero":
      case "playerLosesPoison":
      case "playerLosesEmptyDraw":
        yield* this.applyPlayerLoss(action);
        return;
      case "creatureZeroToughness":
        yield* this.game.action.moveTo(action.cardId, ZoneType.Graveyard);
        return;
      case "creatureLethalDamage":
        yield* this.game.action.destroy(action.cardId, { cause: "sba" });
        return;
      case "planeswalkerZeroLoyalty":
        yield* this.game.action.moveTo(action.cardId, ZoneType.Graveyard);
        return;
      case "battleZeroDefense":
        yield* this.game.action.exile(action.cardId);
        return;
      // Tasks 31-32 add more cases.
      default: {
        // Interim: ignore unimplemented kinds. Task 32 converts this into
        // an exhaustiveness guard with all kinds handled.
        return;
      }
    }
  }

  private *applyPlayerLoss(
    action: Extract<
      SbaAction,
      { kind: "playerLosesLifeZero" | "playerLosesPoison" | "playerLosesEmptyDraw" }
    >,
  ): Generator<EngineYield, void, unknown> {
    const reasonMap: Record<typeof action.kind, LossReason> = {
      playerLosesLifeZero: "life",
      playerLosesPoison: "poison",
      playerLosesEmptyDraw: "decked",
    };
    const reason = reasonMap[action.kind];
    const seat = action.seat;
    // Clear the failed-draw flag so the SBA doesn't re-fire on the next
    // sweep. Life / poison are the condition themselves; clearing them is
    // not meaningful (the player remains below zero).
    if (action.kind === "playerLosesEmptyDraw") {
      this.game.getPlayer(seat).failedDrawFromEmptyLibrary = false;
    }
    // Mark the player as lost BEFORE emitting so a same-sweep double-loss
    // (simultaneous life=0 + poison>=10) doesn't emit twice; the second
    // check in collectLossConditions sees the player as already lost.
    this.markPlayerLost(seat, reason);
    yield this.game.emitEvent(
      mkEvent("PlayerLost", this.game.turn, this.game.phase, {
        playerSeat: seat,
        reason,
      }),
    );
  }

  // SP2 interim terminal-state bookkeeping. Task 68 (Milestone V) enriches
  // this with proper loss-reason taxonomy + win/draw adjudication. Here we
  // track lost seats in concededSeats (the only roster field TerminalState
  // carries), and flip the outcome once only one seat remains.
  private markPlayerLost(seat: PlayerSeat, reason: LossReason): void {
    const current = this.game.terminalState;
    const existing = current?.concededSeats ?? [];
    if (existing.includes(seat)) return;

    const lost = [...existing, seat];
    const livingSeats = this.game.players.filter((p) => !lost.includes(p.seat)).map((p) => p.seat);

    const endedAt: { turn: number; phase: PhaseStep } = {
      turn: this.game.turn,
      phase: this.game.phase,
    };

    let next: TerminalState;
    if (livingSeats.length === 1) {
      const winner = livingSeats[0];
      if (winner === undefined) {
        next = {
          endedAt,
          outcome: { kind: "draw", reason },
          concededSeats: lost,
        };
      } else {
        next = {
          endedAt,
          outcome: { kind: "win", winner, reason },
          concededSeats: lost,
        };
      }
    } else if (livingSeats.length === 0) {
      next = {
        endedAt,
        outcome: { kind: "draw", reason },
        concededSeats: lost,
      };
    } else {
      // Multi-player: still in progress; bundle the running losses without
      // a concluding outcome so observers can see them.
      next = {
        endedAt,
        // Placeholder outcome until the last seat falls. `concededSeats`
        // is the authoritative roster.
        outcome: { kind: "draw", reason },
        concededSeats: lost,
      };
    }
    this.game.terminalState = next;
  }
}
