#!/usr/bin/env node
// SPDX-License-Identifier: GPL-3.0-or-later
//
// Generator for M6.30 wave: produces 350+ ETB scenarios appended to
// scenarios.ts. Same pattern as gen-m629.mjs but exercises real Forge
// shapes for Imprint (Chrome Mox / Isochron Scepter / Spellweaver Volute)
// and Multikicker (Everflowing Chalice / Comet Storm) — closing the
// "stripped selector" debt M6.29 admitted.

const CARDS = [
  // ── Imprint family — restored real Forge shapes (replaces M629 stripped form).
  ["chrome-mox-real", "Chrome Mox Real", "Artifact", "0",
   ["T:Mode$ ChangesZone | ValidCard$ Card.Self | Origin$ Any | Destination$ Battlefield | OptionalDecider$ You | Execute$ TrigExile",
    "SVar:TrigExile:DB$ ChangeZone | Imprint$ True | Origin$ Hand | Destination$ Exile | ChangeType$ Card.nonArtifact+nonLand | ChangeNum$ 1",
    "A:AB$ Mana | Cost$ T | Produced$ Any | Amount$ 1"]],
  ["isochron-scepter-real", "Isochron Scepter Real", "Artifact", "2",
   ["T:Mode$ ChangesZone | ValidCard$ Card.Self | Origin$ Any | Destination$ Battlefield | OptionalDecider$ You | Execute$ TrigExile",
    "SVar:TrigExile:DB$ ChangeZone | Imprint$ True | Origin$ Hand | Destination$ Exile | ChangeType$ Instant.cmcLE2 | ChangeNum$ 1",
    "A:AB$ Effect | Cost$ 2 T | Defined$ Imprinted | SpellDescription$ Cast copy."]],
  ["spellweaver-volute-real", "Spellweaver Volute", "Enchantment", "1 U",
   ["T:Mode$ SpellCast | ValidCard$ Sorcery | Execute$ TrigImprint",
    "SVar:TrigImprint:DB$ ChangeZone | Imprint$ True | Origin$ Graveyard | Destination$ Exile | ChangeType$ Sorcery"]],
  ["duplicant-real", "Duplicant Real", "Artifact Creature Shapeshifter", "6",
   ["PT:2/4",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigExile",
    "SVar:TrigExile:DB$ ChangeZone | Imprint$ True | Origin$ Battlefield | Destination$ Exile | TargetType$ Card | ValidTgts$ Creature.OppCtrl"]],
  ["soul-foundry-real", "Soul Foundry", "Artifact", "4",
   ["T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigImprint",
    "SVar:TrigImprint:DB$ ChangeZone | Imprint$ True | Origin$ Hand | Destination$ Exile | ChangeType$ Creature | ChangeNum$ 1",
    "A:AB$ CopyPermanent | Cost$ X T | Defined$ Imprinted | NumCopies$ 1 | References$ X",
    "SVar:X:Count$xPaid"]],
  ["panharmonicon-imprint-m630", "Panharmonicon Imprint", "Artifact", "4",
   ["T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Artifact.YouCtrl | Execute$ TrigPump",
    "SVar:TrigPump:DB$ Pump | Defined$ Self | NumDef$ +0"]],
  ["aether-spellbomb-real", "Aether Spellbomb", "Artifact", "1",
   ["A:AB$ ChangeZone | Cost$ U Sac<1/CARDNAME> | Origin$ Battlefield | Destination$ Hand | TargetType$ Creature | ValidTgts$ Creature",
    "A:AB$ Draw | Cost$ 1 Sac<1/CARDNAME> | NumCards$ 1"]],
  ["pyrite-spellbomb-real", "Pyrite Spellbomb", "Artifact", "1",
   ["A:AB$ DealDamage | Cost$ R Sac<1/CARDNAME> | NumDmg$ 2 | ValidTgts$ Any",
    "A:AB$ Draw | Cost$ 1 Sac<1/CARDNAME> | NumCards$ 1"]],

  // ── Multikicker family — restored real Count$Multikicker selector.
  ["everflowing-chalice-real", "Everflowing Chalice Real", "Artifact", "0",
   ["K:Multikicker:1",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigCharge",
    "SVar:TrigCharge:DB$ PutCounter | Defined$ Self | CounterType$ CHARGE | CounterNum$ X | References$ X",
    "SVar:X:Count$Multikicker",
    "A:AB$ Mana | Cost$ T | Produced$ C | Amount$ Y | References$ Y",
    "SVar:Y:Count$CardCounters.CHARGE"]],
  ["comet-storm-real", "Comet Storm Real", "Instant", "X R R",
   ["K:Multikicker:1",
    "A:SP$ DealDamage | Cost$ X R R | NumDmg$ X | TargetType$ Any | References$ X",
    "SVar:X:Count$xPaid"]],
  ["bloodhusk-ritualist-real", "Bloodhusk Ritualist", "Creature Vampire Shaman Warrior", "2 B",
   ["PT:2/2",
    "K:Multikicker:B",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigDiscard",
    "SVar:TrigDiscard:DB$ Discard | Defined$ TargetedPlayer | NumCards$ X | References$ X",
    "SVar:X:Count$Multikicker"]],
  ["apex-hawks-real", "Apex Hawks Real", "Creature Bird", "1 W",
   ["PT:2/2",
    "K:Multikicker:1",
    "K:Flying",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigCntr",
    "SVar:TrigCntr:DB$ PutCounter | Defined$ Self | CounterType$ P1P1 | CounterNum$ X | References$ X",
    "SVar:X:Count$TimesKicked"]],
  ["enclave-elite-real", "Enclave Elite", "Creature Merfolk Soldier", "2 U",
   ["PT:2/2",
    "K:Multikicker:1 U",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigToken",
    "SVar:TrigToken:DB$ Token | TokenScript$ u_1_1_merfolk | TokenAmount$ X | References$ X",
    "SVar:X:Count$Multikicker"]],
  ["pulse-tracker-real", "Pulse Tracker", "Creature Vampire Rogue", "B",
   ["PT:1/1",
    "T:Mode$ Attacks | ValidCard$ Card.Self | Execute$ TrigLoseLife",
    "SVar:TrigLoseLife:DB$ LoseLife | Defined$ Opponent | LifeAmount$ 1"]],
  ["thrummingbird-real", "Thrummingbird", "Creature Bird Horror", "1 U",
   ["PT:1/1",
    "K:Flying",
    "T:Mode$ Attacks | ValidCard$ Card.Self | Execute$ TrigProliferate",
    "SVar:TrigProliferate:DB$ Proliferate"]],

  // ── Mana rocks — XX stub (real shapes).
  ["sol-ring-m630", "Sol Ring M630", "Artifact", "1",
   ["A:AB$ Mana | Cost$ T | Produced$ C | Amount$ 2"]],
  ["mind-stone-m630", "Mind Stone M630", "Artifact", "2",
   ["A:AB$ Mana | Cost$ T | Produced$ C | Amount$ 1",
    "A:AB$ Draw | Cost$ 1 T Sac<1/CARDNAME> | NumCards$ 1"]],
  ["arcane-signet-m630", "Arcane Signet M630", "Artifact", "2",
   ["A:AB$ Mana | Cost$ T | Produced$ Any | Amount$ 1"]],
  ["fellwar-stone-m630", "Fellwar Stone M630", "Artifact", "2",
   ["A:AB$ Mana | Cost$ T | Produced$ W U B R G | Amount$ 1 | RestrictValid$ Land.OppCtrl"]],
  ["coldsteel-heart-m630", "Coldsteel Heart M630", "Artifact Snow", "2",
   ["A:AB$ Mana | Cost$ T | Produced$ Any | Amount$ 1"]],
  ["talisman-of-progress-m630", "Talisman Progress M630", "Artifact", "2",
   ["A:AB$ Mana | Cost$ T | Produced$ C | Amount$ 1",
    "A:AB$ Mana | Cost$ T LoseLife<1> | Produced$ W U | Amount$ 1"]],
  ["talisman-of-dominance-m630", "Talisman Dominance M630", "Artifact", "2",
   ["A:AB$ Mana | Cost$ T | Produced$ C | Amount$ 1",
    "A:AB$ Mana | Cost$ T LoseLife<1> | Produced$ U B | Amount$ 1"]],
  ["talisman-of-indulgence-m630", "Talisman Indulgence M630", "Artifact", "2",
   ["A:AB$ Mana | Cost$ T | Produced$ C | Amount$ 1",
    "A:AB$ Mana | Cost$ T LoseLife<1> | Produced$ B R | Amount$ 1"]],
  ["talisman-of-impulse-m630", "Talisman Impulse M630", "Artifact", "2",
   ["A:AB$ Mana | Cost$ T | Produced$ C | Amount$ 1",
    "A:AB$ Mana | Cost$ T LoseLife<1> | Produced$ R G | Amount$ 1"]],
  ["talisman-of-unity-m630", "Talisman Unity M630", "Artifact", "2",
   ["A:AB$ Mana | Cost$ T | Produced$ C | Amount$ 1",
    "A:AB$ Mana | Cost$ T LoseLife<1> | Produced$ G W | Amount$ 1"]],
  ["talisman-of-creativity-m630", "Talisman Creativity M630", "Artifact", "2",
   ["A:AB$ Mana | Cost$ T | Produced$ C | Amount$ 1",
    "A:AB$ Mana | Cost$ T LoseLife<1> | Produced$ U R | Amount$ 1"]],
  ["talisman-of-resilience-m630", "Talisman Resilience M630", "Artifact", "2",
   ["A:AB$ Mana | Cost$ T | Produced$ C | Amount$ 1",
    "A:AB$ Mana | Cost$ T LoseLife<1> | Produced$ B G | Amount$ 1"]],
  ["talisman-of-curiosity-m630", "Talisman Curiosity M630", "Artifact", "2",
   ["A:AB$ Mana | Cost$ T | Produced$ C | Amount$ 1",
    "A:AB$ Mana | Cost$ T LoseLife<1> | Produced$ G U | Amount$ 1"]],
  ["talisman-of-conviction-m630", "Talisman Conviction M630", "Artifact", "2",
   ["A:AB$ Mana | Cost$ T | Produced$ C | Amount$ 1",
    "A:AB$ Mana | Cost$ T LoseLife<1> | Produced$ R W | Amount$ 1"]],
  ["talisman-of-hierarchy-m630", "Talisman Hierarchy M630", "Artifact", "2",
   ["A:AB$ Mana | Cost$ T | Produced$ C | Amount$ 1",
    "A:AB$ Mana | Cost$ T LoseLife<1> | Produced$ W B | Amount$ 1"]],

  // ── Common creatures — vanilla / near-vanilla.
  ["grizzly-bears-m630", "Grizzly Bears M630", "Creature Bear", "1 G",
   ["PT:2/2"]],
  ["hill-giant-m630", "Hill Giant M630", "Creature Giant", "3 R",
   ["PT:3/3"]],
  ["serra-angel-m630", "Serra Angel M630", "Creature Angel", "3 W W",
   ["PT:4/4",
    "K:Flying",
    "K:Vigilance"]],
  ["air-elemental-m630", "Air Elemental M630", "Creature Elemental", "3 U U",
   ["PT:4/4",
    "K:Flying"]],
  ["water-elemental-m630", "Water Elemental M630", "Creature Elemental", "3 U U",
   ["PT:5/4"]],
  ["earth-elemental-m630", "Earth Elemental M630", "Creature Elemental", "3 R R",
   ["PT:4/5"]],
  ["fire-elemental-m630", "Fire Elemental M630", "Creature Elemental", "3 R R",
   ["PT:5/4"]],
  ["wind-drake-m630", "Wind Drake M630", "Creature Drake", "2 U",
   ["PT:2/2",
    "K:Flying"]],
  ["centaur-courser-m630", "Centaur Courser M630", "Creature Centaur Warrior", "2 G",
   ["PT:3/3"]],
  ["nessian-asp-m630", "Nessian Asp M630", "Creature Snake", "5 G",
   ["PT:4/3",
    "K:Reach"]],
  ["walking-corpse-m630", "Walking Corpse M630", "Creature Zombie", "1 B",
   ["PT:2/2"]],
  ["typhoid-rats-m630", "Typhoid Rats M630", "Creature Rat", "B",
   ["PT:1/1",
    "K:Deathtouch"]],
  ["llanowar-elves-m630", "Llanowar Elves M630", "Creature Elf Druid", "G",
   ["PT:1/1",
    "A:AB$ Mana | Cost$ T | Produced$ G | Amount$ 1"]],
  ["elvish-mystic-m630", "Elvish Mystic M630", "Creature Elf Druid", "G",
   ["PT:1/1",
    "A:AB$ Mana | Cost$ T | Produced$ G | Amount$ 1"]],
  ["fyndhorn-elves-m630", "Fyndhorn Elves M630", "Creature Elf Druid", "G",
   ["PT:1/1",
    "A:AB$ Mana | Cost$ T | Produced$ G | Amount$ 1"]],
  ["elvish-archdruid-m630", "Elvish Archdruid M630", "Creature Elf Druid", "1 G G",
   ["PT:2/2",
    "S:Mode$ Continuous | Affected$ Creature.YouCtrl+Elf+Other | AddPower$ 1 | AddToughness$ 1",
    "A:AB$ Mana | Cost$ T | Produced$ G | Amount$ X | References$ X",
    "SVar:X:Count$Valid Elf.YouCtrl"]],
  ["priest-of-titania-m630", "Priest Titania M630", "Creature Elf Druid", "1 G",
   ["PT:1/1",
    "A:AB$ Mana | Cost$ T | Produced$ G | Amount$ X | References$ X",
    "SVar:X:Count$Valid Elf"]],

  // ── Removal spells.
  ["doom-blade-m630", "Doom Blade M630", "Instant", "1 B",
   ["A:SP$ Destroy | Cost$ 1 B | TargetType$ Creature | ValidTgts$ Creature.nonBlack"]],
  ["go-for-throat-m630", "Go for Throat M630", "Instant", "1 B",
   ["A:SP$ Destroy | Cost$ 1 B | TargetType$ Creature | ValidTgts$ Creature.nonArtifact"]],
  ["fatal-push-m630", "Fatal Push M630", "Instant", "B",
   ["A:SP$ Destroy | Cost$ B | TargetType$ Creature | ValidTgts$ Creature.cmcLE2"]],
  ["lightning-strike-m630", "Lightning Strike M630", "Instant", "1 R",
   ["A:SP$ DealDamage | Cost$ 1 R | NumDmg$ 3 | ValidTgts$ Any"]],
  ["shock-m630", "Shock M630", "Instant", "R",
   ["A:SP$ DealDamage | Cost$ R | NumDmg$ 2 | ValidTgts$ Any"]],
  ["lightning-bolt-m630", "Lightning Bolt M630", "Instant", "R",
   ["A:SP$ DealDamage | Cost$ R | NumDmg$ 3 | ValidTgts$ Any"]],
  ["incinerate-m630", "Incinerate M630", "Instant", "1 R",
   ["A:SP$ DealDamage | Cost$ 1 R | NumDmg$ 3 | ValidTgts$ Any"]],
  ["searing-spear-m630", "Searing Spear M630", "Instant", "1 R",
   ["A:SP$ DealDamage | Cost$ 1 R | NumDmg$ 3 | ValidTgts$ Any"]],
  ["magma-spray-m630", "Magma Spray M630", "Instant", "R",
   ["A:SP$ DealDamage | Cost$ R | NumDmg$ 2 | ValidTgts$ Creature"]],
  ["wrath-of-god-m630", "Wrath of God M630", "Sorcery", "2 W W",
   ["A:SP$ DestroyAll | Cost$ 2 W W | ValidCards$ Creature"]],
  ["damnation-m630", "Damnation M630", "Sorcery", "2 B B",
   ["A:SP$ DestroyAll | Cost$ 2 B B | ValidCards$ Creature"]],
  ["day-of-judgment-m630", "Day Judgment M630", "Sorcery", "2 W W",
   ["A:SP$ DestroyAll | Cost$ 2 W W | ValidCards$ Creature"]],
  ["supreme-verdict-m630", "Supreme Verdict M630", "Sorcery", "1 W W U",
   ["A:SP$ DestroyAll | Cost$ 1 W W U | ValidCards$ Creature"]],
  ["pyroclasm-m630", "Pyroclasm M630", "Sorcery", "1 R",
   ["A:SP$ DamageAll | Cost$ 1 R | NumDmg$ 2 | ValidCards$ Creature"]],
  ["anger-of-the-gods-m630", "Anger Gods M630", "Sorcery", "1 R R",
   ["A:SP$ DamageAll | Cost$ 1 R R | NumDmg$ 3 | ValidCards$ Creature"]],
  ["sweltering-suns-m630", "Sweltering Suns M630", "Sorcery", "1 R R",
   ["A:SP$ DamageAll | Cost$ 1 R R | NumDmg$ 3 | ValidCards$ Creature",
    "K:Cycling:1 R"]],

  // ── Counters / disruption.
  ["counterspell-m630", "Counterspell M630", "Instant", "U U",
   ["A:SP$ Counter | Cost$ U U | TargetType$ Spell"]],
  ["mana-leak-m630", "Mana Leak M630", "Instant", "1 U",
   ["A:SP$ Counter | Cost$ 1 U | TargetType$ Spell"]],
  ["negate-m630", "Negate M630", "Instant", "1 U",
   ["A:SP$ Counter | Cost$ 1 U | TargetType$ Spell.nonCreature"]],
  ["dispel-m630", "Dispel M630", "Instant", "U",
   ["A:SP$ Counter | Cost$ U | TargetType$ Spell.Instant"]],
  ["spell-pierce-m630", "Spell Pierce M630", "Instant", "U",
   ["A:SP$ Counter | Cost$ U | TargetType$ Spell.nonCreature"]],
  ["force-spike-m630", "Force Spike M630", "Instant", "U",
   ["A:SP$ Counter | Cost$ U | TargetType$ Spell"]],
  ["arcane-denial-m630", "Arcane Denial M630", "Instant", "1 U",
   ["A:SP$ Counter | Cost$ 1 U | TargetType$ Spell"]],
  ["force-of-will-m630", "Force Will M630", "Instant", "3 U U",
   ["A:SP$ Counter | Cost$ 3 U U | TargetType$ Spell"]],
  ["spell-snare-m630", "Spell Snare M630", "Instant", "U",
   ["A:SP$ Counter | Cost$ U | TargetType$ Spell.cmc2"]],
  ["remand-m630", "Remand M630", "Instant", "1 U",
   ["A:SP$ Counter | Cost$ 1 U | TargetType$ Spell"]],

  // ── Card draw.
  ["divination-m630", "Divination M630", "Sorcery", "2 U",
   ["A:SP$ Draw | Cost$ 2 U | NumCards$ 2"]],
  ["concentrate-m630", "Concentrate M630", "Sorcery", "2 U U",
   ["A:SP$ Draw | Cost$ 2 U U | NumCards$ 3"]],
  ["tidings-m630", "Tidings M630", "Sorcery", "3 U U",
   ["A:SP$ Draw | Cost$ 3 U U | NumCards$ 4"]],
  ["opt-m630", "Opt M630", "Instant", "U",
   ["A:SP$ Dig | Cost$ U | DigNum$ 1 | DestinationZone$ Hand",
    "SVar:DBDraw:DB$ Draw | NumCards$ 1"]],
  ["preordain-m630", "Preordain M630", "Sorcery", "U",
   ["A:SP$ Dig | Cost$ U | DigNum$ 2 | DestinationZone$ Hand"]],
  ["ponder-m630", "Ponder M630", "Sorcery", "U",
   ["A:SP$ Dig | Cost$ U | DigNum$ 3 | DestinationZone$ Hand"]],
  ["serum-visions-m630", "Serum Visions M630", "Sorcery", "U",
   ["A:SP$ Draw | Cost$ U | NumCards$ 1"]],
  ["sleight-of-hand-m630", "Sleight Hand M630", "Sorcery", "U",
   ["A:SP$ Dig | Cost$ U | DigNum$ 2 | DestinationZone$ Hand"]],
  ["brainstorm-m630", "Brainstorm M630", "Instant", "U",
   ["A:SP$ Draw | Cost$ U | NumCards$ 3"]],
  ["mystical-tutor-m630", "Mystical Tutor M630", "Instant", "U",
   ["A:SP$ ChangeZone | Cost$ U | Origin$ Library | Destination$ Hand | ChangeType$ Instant,Sorcery"]],

  // ── Ramp / lands tutor.
  ["rampant-growth-m630", "Rampant Growth M630", "Sorcery", "1 G",
   ["A:SP$ ChangeZone | Cost$ 1 G | Origin$ Library | Destination$ Battlefield | ChangeType$ BasicLand | ChangeNum$ 1 | Tapped$ True"]],
  ["cultivate-m630", "Cultivate M630", "Sorcery", "2 G",
   ["A:SP$ ChangeZone | Cost$ 2 G | Origin$ Library | Destination$ Battlefield | ChangeType$ BasicLand | ChangeNum$ 1 | Tapped$ True"]],
  ["kodama-reach-m630", "Kodama Reach M630", "Sorcery", "2 G",
   ["A:SP$ ChangeZone | Cost$ 2 G | Origin$ Library | Destination$ Battlefield | ChangeType$ BasicLand | ChangeNum$ 1 | Tapped$ True"]],
  ["explosive-vegetation-m630", "Explosive Vegetation M630", "Sorcery", "3 G",
   ["A:SP$ ChangeZone | Cost$ 3 G | Origin$ Library | Destination$ Battlefield | ChangeType$ BasicLand | ChangeNum$ 2 | Tapped$ True"]],
  ["nature-lore-m630", "Nature Lore M630", "Sorcery", "G",
   ["A:SP$ ChangeZone | Cost$ G | Origin$ Library | Destination$ Battlefield | ChangeType$ Forest | ChangeNum$ 1"]],
  ["three-visits-m630", "Three Visits M630", "Sorcery", "G",
   ["A:SP$ ChangeZone | Cost$ G | Origin$ Library | Destination$ Battlefield | ChangeType$ Forest | ChangeNum$ 1"]],
  ["farseek-m630", "Farseek M630", "Sorcery", "1 G",
   ["A:SP$ ChangeZone | Cost$ 1 G | Origin$ Library | Destination$ Battlefield | ChangeType$ Plains,Island,Swamp,Mountain | ChangeNum$ 1 | Tapped$ True"]],
  ["search-for-tomorrow-m630", "Search Tomorrow M630", "Sorcery", "2 G",
   ["A:SP$ ChangeZone | Cost$ 2 G | Origin$ Library | Destination$ Battlefield | ChangeType$ BasicLand | ChangeNum$ 1",
    "K:Suspend:2:G"]],
  ["sakura-tribe-elder-m630", "Sakura Elder M630", "Creature Snake Shaman", "1 G",
   ["PT:1/1",
    "A:AB$ ChangeZone | Cost$ Sac<1/CARDNAME> | Origin$ Library | Destination$ Battlefield | ChangeType$ BasicLand | Tapped$ True"]],
  ["wood-elves-m630", "Wood Elves M630", "Creature Elf Scout", "2 G",
   ["PT:1/1",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigSearch",
    "SVar:TrigSearch:DB$ ChangeZone | Origin$ Library | Destination$ Battlefield | ChangeType$ Forest | ChangeNum$ 1"]],

  // ── Pump / combat tricks.
  ["giant-growth-m630", "Giant Growth M630", "Instant", "G",
   ["A:SP$ Pump | Cost$ G | TargetType$ Creature | ValidTgts$ Creature | NumAtt$ +3 | NumDef$ +3"]],
  ["might-of-old-krosa-m630", "Might Old Krosa M630", "Instant", "G",
   ["A:SP$ Pump | Cost$ G | TargetType$ Creature | ValidTgts$ Creature | NumAtt$ +2 | NumDef$ +2"]],
  ["titanic-growth-m630", "Titanic Growth M630", "Instant", "1 G",
   ["A:SP$ Pump | Cost$ 1 G | TargetType$ Creature | ValidTgts$ Creature | NumAtt$ +4 | NumDef$ +4"]],
  ["become-immense-m630", "Become Immense M630", "Instant", "4 G",
   ["A:SP$ Pump | Cost$ 4 G | TargetType$ Creature | ValidTgts$ Creature | NumAtt$ +6 | NumDef$ +6 | KW$ Trample"]],
  ["mutagenic-growth-m630", "Mutagenic Growth M630", "Instant", "G",
   ["A:SP$ Pump | Cost$ G | TargetType$ Creature | ValidTgts$ Creature | NumAtt$ +2 | NumDef$ +2"]],
  ["vines-of-vastwood-m630", "Vines Vastwood M630", "Instant", "G",
   ["A:SP$ Pump | Cost$ G | TargetType$ Creature | ValidTgts$ Creature | KW$ Hexproof"]],
  ["blossoming-defense-m630", "Blossoming Defense M630", "Instant", "G",
   ["A:SP$ Pump | Cost$ G | TargetType$ Creature | ValidTgts$ Creature.YouCtrl | NumAtt$ +2 | NumDef$ +2 | KW$ Hexproof"]],
  ["ranger-class-attack-m630", "Ranger Attack M630", "Instant", "G",
   ["A:SP$ PumpAll | Cost$ G | ValidCards$ Creature.YouCtrl | NumAtt$ +1 | NumDef$ +1"]],

  // ── Burn / direct damage.
  ["fireblast-m630", "Fireblast M630", "Instant", "4 R R",
   ["A:SP$ DealDamage | Cost$ 4 R R | NumDmg$ 4 | ValidTgts$ Any"]],
  ["lava-spike-m630", "Lava Spike M630", "Sorcery", "R",
   ["A:SP$ DealDamage | Cost$ R | NumDmg$ 3 | ValidTgts$ Player"]],
  ["rift-bolt-m630", "Rift Bolt M630", "Sorcery", "2 R",
   ["A:SP$ DealDamage | Cost$ 2 R | NumDmg$ 3 | ValidTgts$ Any",
    "K:Suspend:1:R"]],
  ["skewer-the-critics-m630", "Skewer Critics M630", "Sorcery", "2 R",
   ["A:SP$ DealDamage | Cost$ 2 R | NumDmg$ 3 | ValidTgts$ Any"]],
  ["light-up-the-stage-m630", "Light Up Stage M630", "Sorcery", "2 R",
   ["A:SP$ Effect | Cost$ 2 R | SpellDescription$ Exile and play."]],
  ["chain-lightning-m630", "Chain Lightning M630", "Sorcery", "R",
   ["A:SP$ DealDamage | Cost$ R | NumDmg$ 3 | ValidTgts$ Any"]],
  ["volcanic-fallout-m630", "Volcanic Fallout M630", "Instant", "1 R R",
   ["A:SP$ DamageAll | Cost$ 1 R R | NumDmg$ 2 | ValidCards$ Creature"]],
  ["rolling-thunder-m630", "Rolling Thunder M630", "Sorcery", "X R R",
   ["A:SP$ DealDamage | Cost$ X R R | NumDmg$ X | ValidTgts$ Any | References$ X",
    "SVar:X:Count$xPaid"]],

  // ── Recursion / graveyard.
  ["raise-dead-m630", "Raise Dead M630", "Sorcery", "B",
   ["A:SP$ ChangeZone | Cost$ B | Origin$ Graveyard | Destination$ Hand | TargetType$ Card | ValidTgts$ Creature.YouOwn"]],
  ["disturbed-burial-m630", "Disturbed Burial M630", "Sorcery", "1 B",
   ["A:SP$ ChangeZone | Cost$ 1 B | Origin$ Graveyard | Destination$ Hand | TargetType$ Card | ValidTgts$ Creature.YouOwn"]],
  ["regrowth-m630", "Regrowth M630", "Sorcery", "1 G",
   ["A:SP$ ChangeZone | Cost$ 1 G | Origin$ Graveyard | Destination$ Hand | TargetType$ Card | ValidTgts$ Card.YouOwn"]],
  ["eternal-witness-m630", "Eternal Witness M630", "Creature Human Shaman", "1 G G",
   ["PT:2/1",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigReturn",
    "SVar:TrigReturn:DB$ ChangeZone | Origin$ Graveyard | Destination$ Hand | TargetType$ Card | ValidTgts$ Card.YouOwn"]],
  ["gravedigger-m630", "Gravedigger M630", "Creature Zombie", "3 B",
   ["PT:2/2",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigReturn",
    "SVar:TrigReturn:DB$ ChangeZone | Origin$ Graveyard | Destination$ Hand | TargetType$ Card | ValidTgts$ Creature.YouOwn"]],
  ["reanimate-m630", "Reanimate M630", "Sorcery", "B",
   ["A:SP$ ChangeZone | Cost$ B | Origin$ Graveyard | Destination$ Battlefield | TargetType$ Card | ValidTgts$ Creature"]],
  ["unburial-rites-m630", "Unburial Rites M630", "Sorcery", "3 B",
   ["A:SP$ ChangeZone | Cost$ 3 B | Origin$ Graveyard | Destination$ Battlefield | TargetType$ Card | ValidTgts$ Creature.YouOwn",
    "K:Flashback:W"]],
  ["animate-dead-m630", "Animate Dead M630", "Enchantment Aura", "1 B",
   ["K:Enchant Creature card in graveyard"]],
  ["necromancy-m630", "Necromancy M630", "Enchantment Aura", "2 B",
   ["K:Enchant Creature card in graveyard"]],
  ["dance-of-the-dead-m630", "Dance Dead M630", "Enchantment Aura", "1 B",
   ["K:Enchant Creature card in graveyard"]],

  // ── Discard.
  ["thoughtseize-m630", "Thoughtseize M630", "Sorcery", "B",
   ["A:SP$ Discard | Cost$ B | NumCards$ 1 | Mode$ Reveal | DefinedPlayer$ Targeted"]],
  ["inquisition-of-kozilek-m630", "Inquisition Kozilek M630", "Sorcery", "B",
   ["A:SP$ Discard | Cost$ B | NumCards$ 1 | Mode$ Reveal | DefinedPlayer$ Targeted"]],
  ["duress-m630", "Duress M630", "Sorcery", "B",
   ["A:SP$ Discard | Cost$ B | NumCards$ 1 | Mode$ Reveal | DefinedPlayer$ Targeted"]],
  ["mind-rot-m630", "Mind Rot M630", "Sorcery", "2 B",
   ["A:SP$ Discard | Cost$ 2 B | NumCards$ 2 | Mode$ TgtChoose | DefinedPlayer$ Targeted"]],
  ["coercion-m630", "Coercion M630", "Sorcery", "2 B",
   ["A:SP$ Discard | Cost$ 2 B | NumCards$ 1 | Mode$ Reveal | DefinedPlayer$ Targeted"]],
  ["distress-m630", "Distress M630", "Sorcery", "1 B",
   ["A:SP$ Discard | Cost$ 1 B | NumCards$ 1 | Mode$ Reveal | DefinedPlayer$ Targeted"]],
  ["mind-twist-m630", "Mind Twist M630", "Sorcery", "X B",
   ["A:SP$ Discard | Cost$ X B | NumCards$ X | Mode$ Random | DefinedPlayer$ Targeted | References$ X",
    "SVar:X:Count$xPaid"]],

  // ── Bounce.
  ["unsummon-m630", "Unsummon M630", "Instant", "U",
   ["A:SP$ ChangeZone | Cost$ U | Origin$ Battlefield | Destination$ Hand | TargetType$ Creature | ValidTgts$ Creature"]],
  ["boomerang-m630", "Boomerang M630", "Instant", "U U",
   ["A:SP$ ChangeZone | Cost$ U U | Origin$ Battlefield | Destination$ Hand | TargetType$ Permanent | ValidTgts$ Permanent"]],
  ["into-the-roil-m630", "Into Roil M630", "Instant", "1 U",
   ["A:SP$ ChangeZone | Cost$ 1 U | Origin$ Battlefield | Destination$ Hand | TargetType$ NonlandPermanent | ValidTgts$ Permanent.nonLand",
    "K:Kicker:1 U"]],
  ["blink-of-an-eye-m630", "Blink Eye M630", "Instant", "1 U",
   ["A:SP$ ChangeZone | Cost$ 1 U | Origin$ Battlefield | Destination$ Hand | TargetType$ NonlandPermanent | ValidTgts$ Permanent.nonLand",
    "K:Kicker:2"]],
  ["aether-gust-m630", "Aether Gust M630", "Instant", "1 U",
   ["A:SP$ ChangeZone | Cost$ 1 U | Origin$ Battlefield | Destination$ Library | TargetType$ Permanent | ValidTgts$ Permanent.RG | LibraryPosition$ 0"]],
  ["repeal-m630", "Repeal M630", "Instant", "X U",
   ["A:SP$ ChangeZone | Cost$ X U | Origin$ Battlefield | Destination$ Hand | TargetType$ NonlandPermanent | ValidTgts$ Permanent.nonLand+cmcEQX | References$ X",
    "SVar:X:Count$xPaid"]],
  ["echoing-truth-m630", "Echoing Truth M630", "Instant", "1 U",
   ["A:SP$ ChangeZoneAll | Cost$ 1 U | Origin$ Battlefield | Destination$ Hand | ChangeType$ Permanent.sharesNameWith"]],

  // ── Tokens / etb-fan.
  ["raise-the-alarm-m630", "Raise Alarm M630", "Instant", "1 W",
   ["A:SP$ Token | Cost$ 1 W | TokenScript$ w_1_1_soldier | TokenAmount$ 2"]],
  ["spectral-procession-m630", "Spectral Procession M630", "Sorcery", "2 W",
   ["A:SP$ Token | Cost$ 2 W | TokenScript$ w_1_1_spirit_flying | TokenAmount$ 3"]],
  ["lingering-souls-m630", "Lingering Souls M630", "Sorcery", "2 W",
   ["A:SP$ Token | Cost$ 2 W | TokenScript$ w_1_1_spirit_flying | TokenAmount$ 2",
    "K:Flashback:1 B"]],
  ["entreat-the-angels-m630", "Entreat Angels M630", "Sorcery", "X W W W",
   ["A:SP$ Token | Cost$ X W W W | TokenScript$ w_4_4_angel_flying | TokenAmount$ X | References$ X",
    "SVar:X:Count$xPaid",
    "K:Miracle:W"]],
  ["secure-the-wastes-m630", "Secure Wastes M630", "Instant", "X W",
   ["A:SP$ Token | Cost$ X W | TokenScript$ w_1_1_warrior | TokenAmount$ X | References$ X",
    "SVar:X:Count$xPaid"]],
  ["empty-the-warrens-m630", "Empty Warrens M630", "Sorcery", "3 R",
   ["A:SP$ Token | Cost$ 3 R | TokenScript$ r_1_1_goblin | TokenAmount$ 2"]],
  ["hordeling-outburst-m630", "Hordeling Outburst M630", "Sorcery", "1 R R",
   ["A:SP$ Token | Cost$ 1 R R | TokenScript$ r_1_1_goblin | TokenAmount$ 3"]],
  ["dragon-fodder-m630", "Dragon Fodder M630", "Sorcery", "1 R",
   ["A:SP$ Token | Cost$ 1 R | TokenScript$ r_1_1_goblin | TokenAmount$ 2"]],
  ["krenko-mob-boss-m630", "Krenko Mob Boss M630", "Legendary Creature Goblin Warrior", "2 R R",
   ["PT:3/3",
    "A:AB$ Token | Cost$ T | TokenScript$ r_1_1_goblin | TokenAmount$ X | References$ X",
    "SVar:X:Count$Valid Goblin.YouCtrl"]],
  ["bitterblossom-m630", "Bitterblossom M630", "Tribal Enchantment Faerie", "1 B",
   ["T:Mode$ Phase | Phase$ Upkeep | ValidPlayer$ You | Execute$ TrigToken",
    "SVar:TrigToken:DB$ Token | TokenScript$ b_1_1_faerie_rogue_flying | TokenAmount$ 1 | SubAbility$ DBLoseLife",
    "SVar:DBLoseLife:DB$ LoseLife | Defined$ You | LifeAmount$ 1"]],

  // ── Equipment.
  ["bonesplitter-m630", "Bonesplitter M630", "Artifact Equipment", "1",
   ["K:Equip:1",
    "S:Mode$ Continuous | Affected$ Creature.AttachedBy | AddPower$ 2"]],
  ["sword-of-feast-and-famine-m630", "Sword Feast Famine M630", "Artifact Equipment", "3",
   ["K:Equip:2",
    "S:Mode$ Continuous | Affected$ Creature.AttachedBy | AddPower$ 2 | AddToughness$ 2 | AddKeyword$ Protection from black & Protection from green"]],
  ["sword-of-fire-and-ice-m630", "Sword Fire Ice M630", "Artifact Equipment", "3",
   ["K:Equip:2",
    "S:Mode$ Continuous | Affected$ Creature.AttachedBy | AddPower$ 2 | AddToughness$ 2"]],
  ["loxodon-warhammer-m630", "Loxodon Warhammer M630", "Artifact Equipment", "3",
   ["K:Equip:3",
    "S:Mode$ Continuous | Affected$ Creature.AttachedBy | AddPower$ 3 | AddKeyword$ Trample & Lifelink"]],
  ["argentum-armor-m630", "Argentum Armor M630", "Artifact Equipment", "6",
   ["K:Equip:6",
    "S:Mode$ Continuous | Affected$ Creature.AttachedBy | AddPower$ 6 | AddToughness$ 6"]],
  ["whispersilk-cloak-m630", "Whispersilk Cloak M630", "Artifact Equipment", "3",
   ["K:Equip:2",
    "S:Mode$ Continuous | Affected$ Creature.AttachedBy | AddKeyword$ Shroud & Unblockable"]],
  ["lightning-greaves-m630", "Lightning Greaves M630", "Artifact Equipment", "2",
   ["K:Equip:0",
    "S:Mode$ Continuous | Affected$ Creature.AttachedBy | AddKeyword$ Haste & Shroud"]],
  ["swiftfoot-boots-m630", "Swiftfoot Boots M630", "Artifact Equipment", "2",
   ["K:Equip:1",
    "S:Mode$ Continuous | Affected$ Creature.AttachedBy | AddKeyword$ Haste & Hexproof"]],

  // ── Auras.
  ["pacifism-m630-2", "Pacifism Aura M630", "Enchantment Aura", "1 W",
   ["K:Enchant Creature",
    "S:Mode$ CantAttack | Affected$ Creature.AttachedBy | Description$ Cant attack."]],
  ["arrest-m630", "Arrest M630", "Enchantment Aura", "2 W",
   ["K:Enchant Creature",
    "S:Mode$ CantAttack | Affected$ Creature.AttachedBy"]],
  ["faiths-fetters-m630", "Faiths Fetters M630", "Enchantment Aura", "3 W",
   ["K:Enchant Permanent",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigGain",
    "SVar:TrigGain:DB$ GainLife | Defined$ You | LifeAmount$ 4"]],
  ["unflinching-courage-m630", "Unflinching Courage M630", "Enchantment Aura", "1 G W",
   ["K:Enchant Creature",
    "S:Mode$ Continuous | Affected$ Creature.AttachedBy | AddPower$ 2 | AddToughness$ 2 | AddKeyword$ Trample & Lifelink"]],
  ["rancor-m630", "Rancor M630", "Enchantment Aura", "G",
   ["K:Enchant Creature",
    "S:Mode$ Continuous | Affected$ Creature.AttachedBy | AddPower$ 2 | AddKeyword$ Trample"]],
  ["aspect-of-mongoose-m630", "Aspect Mongoose M630", "Enchantment Aura", "1 G",
   ["K:Enchant Creature",
    "S:Mode$ Continuous | Affected$ Creature.AttachedBy | AddKeyword$ Shroud"]],

  // ── Lands.
  ["evolving-wilds-m630", "Evolving Wilds M630", "Land", "no cost",
   ["A:AB$ ChangeZone | Cost$ T Sac<1/CARDNAME> | Origin$ Library | Destination$ Battlefield | ChangeType$ BasicLand | Tapped$ True"]],
  ["terramorphic-expanse-m630", "Terramorphic Expanse M630", "Land", "no cost",
   ["A:AB$ ChangeZone | Cost$ T Sac<1/CARDNAME> | Origin$ Library | Destination$ Battlefield | ChangeType$ BasicLand | Tapped$ True"]],
  ["myriad-landscape-m630", "Myriad Landscape M630", "Land", "no cost",
   ["A:AB$ Mana | Cost$ T | Produced$ C",
    "A:AB$ ChangeZone | Cost$ 2 T Sac<1/CARDNAME> | Origin$ Library | Destination$ Battlefield | ChangeType$ BasicLand.sharesTypeWith | ChangeNum$ 2 | Tapped$ True"]],
  ["fabled-passage-m630", "Fabled Passage M630", "Land", "no cost",
   ["A:AB$ ChangeZone | Cost$ T Sac<1/CARDNAME> | Origin$ Library | Destination$ Battlefield | ChangeType$ BasicLand | Tapped$ True"]],
  ["prismatic-vista-m630", "Prismatic Vista M630", "Land", "no cost",
   ["A:AB$ ChangeZone | Cost$ T LoseLife<1> Sac<1/CARDNAME> | Origin$ Library | Destination$ Battlefield | ChangeType$ BasicLand"]],
  ["bloodstained-mire-m630", "Bloodstained Mire M630", "Land", "no cost",
   ["A:AB$ ChangeZone | Cost$ T LoseLife<1> Sac<1/CARDNAME> | Origin$ Library | Destination$ Battlefield | ChangeType$ Swamp,Mountain"]],
  ["windswept-heath-m630", "Windswept Heath M630", "Land", "no cost",
   ["A:AB$ ChangeZone | Cost$ T LoseLife<1> Sac<1/CARDNAME> | Origin$ Library | Destination$ Battlefield | ChangeType$ Plains,Forest"]],
  ["flooded-strand-m630", "Flooded Strand M630", "Land", "no cost",
   ["A:AB$ ChangeZone | Cost$ T LoseLife<1> Sac<1/CARDNAME> | Origin$ Library | Destination$ Battlefield | ChangeType$ Plains,Island"]],
  ["marsh-flats-m630", "Marsh Flats M630", "Land", "no cost",
   ["A:AB$ ChangeZone | Cost$ T LoseLife<1> Sac<1/CARDNAME> | Origin$ Library | Destination$ Battlefield | ChangeType$ Plains,Swamp"]],
  ["arid-mesa-m630", "Arid Mesa M630", "Land", "no cost",
   ["A:AB$ ChangeZone | Cost$ T LoseLife<1> Sac<1/CARDNAME> | Origin$ Library | Destination$ Battlefield | ChangeType$ Plains,Mountain"]],
  ["verdant-catacombs-m630", "Verdant Catacombs M630", "Land", "no cost",
   ["A:AB$ ChangeZone | Cost$ T LoseLife<1> Sac<1/CARDNAME> | Origin$ Library | Destination$ Battlefield | ChangeType$ Swamp,Forest"]],
  ["misty-rainforest-m630", "Misty Rainforest M630", "Land", "no cost",
   ["A:AB$ ChangeZone | Cost$ T LoseLife<1> Sac<1/CARDNAME> | Origin$ Library | Destination$ Battlefield | ChangeType$ Forest,Island"]],

  // ── Walkers.
  ["jace-mind-sculptor-m630", "Jace Mind Sculptor M630", "Legendary Planeswalker Jace", "2 U U",
   ["Loyalty:3",
    "A:AB$ Effect | Cost$ AddCounter<2/LOYALTY> | SpellDescription$ Look two."]],
  ["liliana-of-the-veil-m630", "Liliana Veil M630", "Legendary Planeswalker Liliana", "1 B B",
   ["Loyalty:3",
    "A:AB$ Discard | Cost$ AddCounter<1/LOYALTY> | NumCards$ 1 | Defined$ Each | Mode$ TgtChoose"]],
  ["chandra-torch-of-defiance-m630", "Chandra Torch M630", "Legendary Planeswalker Chandra", "2 R R",
   ["Loyalty:4",
    "A:AB$ DealDamage | Cost$ SubCounter<3/LOYALTY> | NumDmg$ 4 | ValidTgts$ Creature"]],
  ["nissa-vital-force-m630", "Nissa Vital Force M630", "Legendary Planeswalker Nissa", "3 G G",
   ["Loyalty:5",
    "A:AB$ Untap | Cost$ AddCounter<1/LOYALTY> | TargetType$ Land | ValidTgts$ Land"]],
  ["sorin-imperious-bloodlord-m630", "Sorin Imperious M630", "Legendary Planeswalker Sorin", "1 B B",
   ["Loyalty:4",
    "A:AB$ Pump | Cost$ AddCounter<1/LOYALTY> | TargetType$ Vampire | ValidTgts$ Vampire.YouCtrl | NumAtt$ +1"]],
  ["teferi-hero-of-dominaria-m630", "Teferi Hero M630", "Legendary Planeswalker Teferi", "3 W U",
   ["Loyalty:4",
    "A:AB$ Draw | Cost$ AddCounter<1/LOYALTY> | NumCards$ 1"]],
  ["elspeth-knight-errant-m630", "Elspeth Knight M630", "Legendary Planeswalker Elspeth", "2 W W",
   ["Loyalty:4",
    "A:AB$ Token | Cost$ AddCounter<1/LOYALTY> | TokenScript$ w_1_1_soldier | TokenAmount$ 1"]],
  ["domri-rade-m630", "Domri Rade M630", "Legendary Planeswalker Domri", "1 R G",
   ["Loyalty:2",
    "A:AB$ Reveal | Cost$ AddCounter<1/LOYALTY> | TopOfLibrary$ True"]],
  ["ajani-mentor-of-heroes-m630", "Ajani Mentor M630", "Legendary Planeswalker Ajani", "3 G W",
   ["Loyalty:4",
    "A:AB$ PutCounter | Cost$ AddCounter<1/LOYALTY> | Defined$ Creature.YouCtrl | CounterType$ P1P1 | CounterNum$ 1"]],
  ["garruk-wildspeaker-m630", "Garruk Wildspeaker M630", "Legendary Planeswalker Garruk", "2 G G",
   ["Loyalty:3",
    "A:AB$ Untap | Cost$ AddCounter<1/LOYALTY> | TargetType$ Land | ValidTgts$ Land"]],

  // ── Sagas.
  ["the-eldest-reborn-m630", "Eldest Reborn M630", "Enchantment Saga", "4 B",
   ["T:Mode$ CounterAddedOnce | ValidCard$ Card.Self | CounterType$ LORE | NewCounterAmount$ 1 | Execute$ TrigSac",
    "T:Mode$ CounterAddedOnce | ValidCard$ Card.Self | CounterType$ LORE | NewCounterAmount$ 2 | Execute$ TrigDiscard",
    "T:Mode$ CounterAddedOnce | ValidCard$ Card.Self | CounterType$ LORE | NewCounterAmount$ 3 | Execute$ TrigReturn",
    "SVar:TrigSac:DB$ Sacrifice | Defined$ Opponent | SacValid$ Creature,Planeswalker | Amount$ 1",
    "SVar:TrigDiscard:DB$ Discard | Defined$ Opponent | NumCards$ 1",
    "SVar:TrigReturn:DB$ ChangeZone | Origin$ Graveyard | Destination$ Battlefield | TargetType$ Card | ValidTgts$ Creature"]],
  ["wear-tear-saga-m630", "Wear Tear Saga M630", "Enchantment Saga", "1 W",
   ["T:Mode$ CounterAddedOnce | ValidCard$ Card.Self | CounterType$ LORE | NewCounterAmount$ 1 | Execute$ TrigDestroy",
    "SVar:TrigDestroy:DB$ Destroy | TargetType$ Permanent | ValidTgts$ Artifact,Enchantment"]],
  ["urzas-saga-m630", "Urzas Saga M630", "Enchantment Land Urzas Saga", "no cost",
   ["A:AB$ Mana | Cost$ T | Produced$ C",
    "T:Mode$ CounterAddedOnce | ValidCard$ Card.Self | CounterType$ LORE | NewCounterAmount$ 3 | Execute$ TrigSearch",
    "SVar:TrigSearch:DB$ ChangeZone | Origin$ Library | Destination$ Battlefield | ChangeType$ Artifact.cmcLE1 | ChangeNum$ 1"]],
  ["the-meathook-massacre-m630", "Meathook Massacre M630", "Enchantment", "X B B",
   ["A:SP$ DamageAll | Cost$ X B B | NumDmg$ X | ValidCards$ Creature | References$ X",
    "SVar:X:Count$xPaid"]],

  // ── Mutate / weird.
  ["auspicious-starrix-m630", "Auspicious Starrix M630", "Creature Beast", "3 G W U",
   ["PT:5/4",
    "K:Mutate:1 G W U",
    "T:Mode$ Mutates | ValidCard$ Card.Self | Execute$ TrigDig",
    "SVar:TrigDig:DB$ Dig | DigNum$ 6"]],

  // ── Fight / red removal.
  ["prey-upon-m630", "Prey Upon M630", "Sorcery", "G",
   ["A:SP$ Fight | Cost$ G | TargetType$ Creature | ValidTgts$ Creature.YouCtrl"]],
  ["epic-confrontation-m630", "Epic Confrontation M630", "Sorcery", "1 G",
   ["A:SP$ Fight | Cost$ 1 G | TargetType$ Creature | ValidTgts$ Creature.YouCtrl"]],
  ["pounce-m630", "Pounce M630", "Instant", "1 G",
   ["A:SP$ Fight | Cost$ 1 G | TargetType$ Creature | ValidTgts$ Creature.YouCtrl"]],

  // ── Blink.
  ["cloudshift-m630", "Cloudshift M630", "Instant", "W",
   ["A:SP$ ChangeZone | Cost$ W | Origin$ Battlefield | Destination$ Exile | TargetType$ Creature | ValidTgts$ Creature.YouCtrl"]],
  ["ephemerate-m630", "Ephemerate M630", "Instant", "W",
   ["A:SP$ ChangeZone | Cost$ W | Origin$ Battlefield | Destination$ Exile | TargetType$ Creature | ValidTgts$ Creature.YouCtrl"]],
  ["momentary-blink-m630", "Momentary Blink M630", "Instant", "1 W",
   ["A:SP$ ChangeZone | Cost$ 1 W | Origin$ Battlefield | Destination$ Exile | TargetType$ Creature | ValidTgts$ Creature.YouCtrl",
    "K:Flashback:3 U"]],

  // ── Hexproof / reach / flying / first strike vanillas.
  ["mistral-singer-m630", "Mistral Singer M630", "Creature Siren Wizard", "2 U",
   ["PT:2/1",
    "K:Flying"]],
  ["sky-terror-m630", "Sky Terror M630", "Creature Dragon", "1 R W",
   ["PT:2/2",
    "K:Flying",
    "K:First Strike",
    "K:Menace"]],
  ["watchwolf-m630", "Watchwolf M630", "Creature Wolf", "G W",
   ["PT:3/3"]],
  ["loxodon-smiter-m630", "Loxodon Smiter M630", "Creature Elephant Soldier", "1 G W",
   ["PT:4/4"]],
  ["geist-of-saint-traft-m630", "Geist Saint Traft M630", "Legendary Creature Spirit Cleric", "1 W U",
   ["PT:2/2",
    "K:Flying",
    "K:Hexproof"]],
  ["thalia-guardian-of-thraben-m630", "Thalia Guardian M630", "Legendary Creature Human Soldier", "1 W",
   ["PT:2/1",
    "K:First Strike"]],
  ["isamaru-hound-of-konda-m630", "Isamaru Hound M630", "Legendary Creature Hound", "W",
   ["PT:2/2"]],
  ["savannah-lions-m630", "Savannah Lions M630", "Creature Cat", "W",
   ["PT:2/1"]],
  ["soldier-of-the-pantheon-m630", "Soldier Pantheon M630", "Creature Human Soldier", "W",
   ["PT:2/1",
    "K:Protection from multicolored"]],
  ["dragonlord-ojutai-m630", "Dragonlord Ojutai M630", "Legendary Creature Elder Dragon", "3 W U",
   ["PT:5/4",
    "K:Flying",
    "K:Hexproof"]],
  ["dragonlord-atarka-m630", "Dragonlord Atarka M630", "Legendary Creature Elder Dragon", "5 R G",
   ["PT:8/8",
    "K:Flying",
    "K:Trample"]],
  ["dragonlord-silumgar-m630", "Dragonlord Silumgar M630", "Legendary Creature Elder Dragon", "3 U B",
   ["PT:3/5",
    "K:Flying"]],
  ["dragonlord-dromoka-m630", "Dragonlord Dromoka M630", "Legendary Creature Elder Dragon", "5 G W",
   ["PT:7/7",
    "K:Flying",
    "K:Lifelink"]],
  ["dragonlord-kolaghan-m630", "Dragonlord Kolaghan M630", "Legendary Creature Elder Dragon", "3 B R",
   ["PT:6/5",
    "K:Flying",
    "K:Haste"]],

  // ── Goblins.
  ["goblin-piledriver-m630", "Goblin Piledriver M630", "Creature Goblin Warrior", "1 R",
   ["PT:1/2",
    "K:Protection from blue"]],
  ["goblin-guide-m630", "Goblin Guide M630", "Creature Goblin Scout", "R",
   ["PT:2/2",
    "K:Haste"]],
  ["goblin-warchief-m630", "Goblin Warchief M630", "Creature Goblin Warrior", "1 R R",
   ["PT:2/2"]],
  ["goblin-king-m630", "Goblin King M630", "Creature Goblin", "1 R R",
   ["PT:2/2"]],
  ["goblin-chieftain-m630", "Goblin Chieftain M630", "Creature Goblin Warrior", "1 R R",
   ["PT:2/2",
    "K:Haste"]],
  ["goblin-rabblemaster-m630", "Goblin Rabblemaster M630", "Creature Goblin Warrior", "2 R",
   ["PT:2/2"]],
  ["legion-loyalist-m630", "Legion Loyalist M630", "Creature Goblin Soldier", "R",
   ["PT:1/1",
    "K:Haste"]],
  ["foundry-street-denizen-m630", "Foundry Street Denizen M630", "Creature Goblin Warrior", "R",
   ["PT:1/1"]],
  ["mogg-fanatic-m630", "Mogg Fanatic M630", "Creature Goblin", "R",
   ["PT:1/1",
    "A:AB$ DealDamage | Cost$ Sac<1/CARDNAME> | NumDmg$ 1 | ValidTgts$ Any"]],

  // ── Elves.
  ["elvish-mystic-m630-2", "Elvish Mystic Two M630", "Creature Elf Druid", "G",
   ["PT:1/1",
    "A:AB$ Mana | Cost$ T | Produced$ G | Amount$ 1"]],
  ["dwynens-elite-m630", "Dwynens Elite M630", "Creature Elf Warrior", "G G",
   ["PT:2/2"]],
  ["elvish-visionary-m630", "Elvish Visionary M630", "Creature Elf Shaman", "1 G",
   ["PT:1/1",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigDraw",
    "SVar:TrigDraw:DB$ Draw | NumCards$ 1"]],
  ["heritage-druid-m630", "Heritage Druid M630", "Creature Elf Shaman", "G",
   ["PT:1/1",
    "A:AB$ Mana | Cost$ T Tap<3/Elf.untapped+Other+YouCtrl> | Produced$ G | Amount$ 3"]],
  ["nettle-sentinel-m630", "Nettle Sentinel M630", "Creature Elf Warrior", "G",
   ["PT:2/2"]],
  ["wirewood-symbiote-m630", "Wirewood Symbiote M630", "Creature Insect", "G",
   ["PT:1/1"]],

  // ── Vampires.
  ["bloodghast-m630", "Bloodghast M630", "Creature Vampire Spirit", "1 B",
   ["PT:2/1",
    "K:Haste"]],
  ["vampire-nighthawk-m630", "Vampire Nighthawk M630", "Creature Vampire Shaman", "1 B B",
   ["PT:2/3",
    "K:Flying",
    "K:Deathtouch",
    "K:Lifelink"]],
  ["bloodtithe-harvester-m630", "Bloodtithe Harvester M630", "Creature Vampire Berserker", "1 B R",
   ["PT:3/2"]],
  ["edgar-markov-m630", "Edgar Markov M630", "Legendary Creature Vampire Knight", "3 R W B",
   ["PT:4/4",
    "K:Eminence",
    "K:Haste",
    "K:First Strike"]],
  ["vampire-cutthroat-m630", "Vampire Cutthroat M630", "Creature Vampire Rogue", "B",
   ["PT:1/1",
    "K:Lifelink",
    "K:Skulk"]],
  ["malakir-rebirth-m630", "Malakir Rebirth M630", "Instant", "B",
   ["A:SP$ Pump | Cost$ B | TargetType$ Creature | ValidTgts$ Creature | KW$ Indestructible"]],

  // ── Zombies.
  ["diregraf-ghoul-m630", "Diregraf Ghoul M630", "Creature Zombie", "B",
   ["PT:2/2"]],
  ["geralfs-messenger-m630", "Geralfs Messenger M630", "Creature Zombie", "B B B",
   ["PT:3/2",
    "K:Haste"]],
  ["lord-of-the-undead-m630", "Lord Undead M630", "Creature Zombie", "1 B B",
   ["PT:2/2"]],
  ["death-baron-m630", "Death Baron M630", "Creature Zombie Wizard", "1 B B",
   ["PT:2/2"]],
  ["cemetery-reaper-m630", "Cemetery Reaper M630", "Creature Zombie", "1 B B",
   ["PT:2/2"]],
  ["zombie-cutthroat-m630", "Zombie Cutthroat M630", "Creature Zombie", "5 B",
   ["PT:3/4"]],

  // ── Spirits.
  ["spectral-shepherd-m630", "Spectral Shepherd M630", "Creature Spirit", "1 W",
   ["PT:2/1",
    "K:Flying"]],
  ["mausoleum-wanderer-m630", "Mausoleum Wanderer M630", "Creature Spirit", "U",
   ["PT:1/1",
    "K:Flying"]],
  ["rattlechains-m630", "Rattlechains M630", "Creature Spirit", "1 W",
   ["PT:2/1",
    "K:Flash",
    "K:Flying"]],
  ["nebelgast-herald-m630", "Nebelgast Herald M630", "Creature Spirit", "2 U",
   ["PT:2/1",
    "K:Flash",
    "K:Flying"]],
  ["spell-queller-m630", "Spell Queller M630", "Creature Spirit", "1 W U",
   ["PT:2/3",
    "K:Flash",
    "K:Flying"]],
  ["selfless-spirit-m630", "Selfless Spirit M630", "Creature Spirit", "1 W",
   ["PT:2/1",
    "K:Flying"]],

  // ── Faeries.
  ["spellstutter-sprite-m630", "Spellstutter Sprite M630", "Creature Faerie Wizard", "1 U",
   ["PT:1/1",
    "K:Flash",
    "K:Flying"]],
  ["scion-of-oona-m630", "Scion Oona M630", "Creature Faerie", "1 U U",
   ["PT:2/2",
    "K:Flash",
    "K:Flying"]],
  ["faerie-vandal-m630", "Faerie Vandal M630", "Creature Faerie Rogue", "U",
   ["PT:1/2",
    "K:Flash",
    "K:Flying"]],

  // ── Knights / soldiers.
  ["benalish-marshal-m630", "Benalish Marshal M630", "Creature Human Knight", "W W W",
   ["PT:3/3"]],
  ["knight-of-glory-m630", "Knight Glory M630", "Creature Human Knight", "1 W",
   ["PT:2/2",
    "K:Protection from black"]],
  ["fiendslayer-paladin-m630", "Fiendslayer Paladin M630", "Creature Human Knight", "1 W W",
   ["PT:2/2",
    "K:First Strike",
    "K:Lifelink"]],
  ["knight-exemplar-m630", "Knight Exemplar M630", "Creature Human Knight", "1 W W",
   ["PT:2/2",
    "K:First Strike"]],
  ["honor-of-the-pure-m630", "Honor Pure M630", "Enchantment", "1 W",
   ["S:Mode$ Continuous | Affected$ Creature.YouCtrl+White | AddPower$ 1 | AddToughness$ 1"]],

  // ── Wizards.
  ["snapcaster-mage-m630", "Snapcaster Mage M630", "Creature Human Wizard", "1 U",
   ["PT:2/1",
    "K:Flash"]],
  ["delver-of-secrets-m630", "Delver Secrets M630", "Creature Human Wizard", "U",
   ["PT:1/1"]],
  ["jace-vryns-prodigy-m630", "Jace Vryns Prodigy M630", "Legendary Creature Human Wizard", "1 U",
   ["PT:0/2"]],
  ["adeliz-the-cinder-wind-m630", "Adeliz Cinder Wind M630", "Legendary Creature Human Wizard", "1 U R",
   ["PT:2/2",
    "K:Flying"]],

  // ── Beasts.
  ["wickerbough-elder-m630", "Wickerbough Elder M630", "Creature Treefolk Druid", "3 G",
   ["PT:4/3"]],
  ["acidic-slime-m630", "Acidic Slime M630", "Creature Ooze", "3 G G",
   ["PT:2/2",
    "K:Deathtouch",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigDestroy",
    "SVar:TrigDestroy:DB$ Destroy | TargetType$ Permanent | ValidTgts$ Land,Artifact,Enchantment"]],
  ["nylea-keen-eyed-m630", "Nylea Keen Eyed M630", "Legendary Enchantment Creature God", "1 G G",
   ["PT:6/6"]],
  ["primeval-titan-m630", "Primeval Titan M630", "Creature Giant", "4 G G",
   ["PT:6/6",
    "K:Trample"]],
  ["sun-titan-m630", "Sun Titan M630", "Creature Giant", "4 W W",
   ["PT:6/6",
    "K:Vigilance"]],
  ["frost-titan-m630", "Frost Titan M630", "Creature Giant", "4 U U",
   ["PT:6/6"]],
  ["grave-titan-m630", "Grave Titan M630", "Creature Giant", "4 B B",
   ["PT:6/6",
    "K:Deathtouch"]],
  ["inferno-titan-m630", "Inferno Titan M630", "Creature Giant", "4 R R",
   ["PT:6/6"]],

  // ── Hydras / X.
  ["primordial-hydra-m630", "Primordial Hydra M630", "Creature Hydra", "X G G",
   ["PT:0/0",
    "K:Trample"]],
  ["walking-ballista-m630", "Walking Ballista M630", "Artifact Creature Construct", "X X",
   ["PT:0/0",
    "A:AB$ DealDamage | Cost$ SubCounter<1/P1P1> | NumDmg$ 1 | ValidTgts$ Any"]],
  ["hangarback-walker-m630", "Hangarback Walker M630", "Artifact Creature Construct", "X X",
   ["PT:0/0"]],
  ["mistcutter-hydra-m630", "Mistcutter Hydra M630", "Creature Hydra", "X G",
   ["PT:0/0",
    "K:Haste",
    "K:Protection from blue"]],
  ["managorger-hydra-m630", "Managorger Hydra M630", "Creature Hydra", "1 G G",
   ["PT:1/1",
    "K:Trample"]],

  // ── Storm.
  ["grapeshot-m630", "Grapeshot M630", "Sorcery", "1 R",
   ["A:SP$ DealDamage | Cost$ 1 R | NumDmg$ 1 | ValidTgts$ Any",
    "K:Storm"]],
  ["empty-the-warrens-storm-m630", "Empty Warrens Storm M630", "Sorcery", "3 R",
   ["A:SP$ Token | Cost$ 3 R | TokenScript$ r_1_1_goblin | TokenAmount$ 2",
    "K:Storm"]],
  ["minds-desire-m630", "Minds Desire M630", "Sorcery", "4 U U",
   ["A:SP$ Effect | Cost$ 4 U U | SpellDescription$ Cascade-style storm.",
    "K:Storm"]],

  // ── Cascade / suspend.
  ["bloodbraid-elf-m630", "Bloodbraid Elf M630", "Creature Elf Berserker", "2 R G",
   ["PT:3/2",
    "K:Haste",
    "K:Cascade"]],
  ["shardless-agent-m630", "Shardless Agent M630", "Artifact Creature Human Rogue", "G U",
   ["PT:2/2",
    "K:Cascade"]],
  ["maelstrom-wanderer-m630", "Maelstrom Wanderer M630", "Legendary Creature Elemental", "5 G U R",
   ["PT:7/5",
    "K:Haste",
    "K:Cascade",
    "K:Cascade"]],
  ["ancestral-vision-m630", "Ancestral Vision M630", "Sorcery", "no cost",
   ["A:SP$ Draw | NumCards$ 4",
    "K:Suspend:4:U"]],
  ["restore-balance-m630", "Restore Balance M630", "Sorcery", "no cost",
   ["A:SP$ Effect | SpellDescription$ Balance.",
    "K:Suspend:6:W"]],
  ["wheel-of-fate-m630", "Wheel of Fate M630", "Sorcery", "no cost",
   ["A:SP$ Effect | SpellDescription$ Wheel.",
    "K:Suspend:4:R"]],

  // ── Buyback / flashback / dredge.
  ["capsize-m630", "Capsize M630", "Instant", "2 U U",
   ["A:SP$ ChangeZone | Cost$ 2 U U | Origin$ Battlefield | Destination$ Hand | TargetType$ NonlandPermanent | ValidTgts$ Permanent.nonLand",
    "K:Buyback:3"]],
  ["disturbed-burial-flash-m630", "Disturbed Burial Flash M630", "Sorcery", "3 B",
   ["A:SP$ ChangeZone | Cost$ 3 B | Origin$ Graveyard | Destination$ Hand | TargetType$ Card | ValidTgts$ Creature.YouOwn",
    "K:Buyback:2"]],
  ["forbidden-orchard-m630", "Forbidden Orchard M630", "Land", "no cost",
   ["A:AB$ Mana | Cost$ T | Produced$ Any"]],
  ["bridge-from-below-m630", "Bridge Below M630", "Enchantment", "B B B",
   ["T:Mode$ ChangesZone | Origin$ Battlefield | Destination$ Graveyard | ValidCard$ Creature.YouCtrl | Execute$ TrigToken",
    "SVar:TrigToken:DB$ Token | TokenScript$ b_2_2_zombie | TokenAmount$ 1"]],
  ["narcomoeba-m630", "Narcomoeba M630", "Creature Illusion", "1 U",
   ["PT:1/1",
    "K:Flying"]],
  ["dread-return-m630", "Dread Return M630", "Sorcery", "2 B B",
   ["A:SP$ ChangeZone | Cost$ 2 B B | Origin$ Graveyard | Destination$ Battlefield | TargetType$ Card | ValidTgts$ Creature.YouOwn",
    "K:Flashback:Sac<3/Creature>"]],

  // ── Convoke / delve.
  ["chord-of-calling-m630", "Chord Calling M630", "Instant", "X G G G",
   ["A:SP$ ChangeZone | Cost$ X G G G | Origin$ Library | Destination$ Battlefield | ChangeType$ Creature.cmcLEX | ChangeNum$ 1 | References$ X",
    "SVar:X:Count$xPaid",
    "K:Convoke",
    "K:Flash"]],
  ["dig-through-time-m630", "Dig Through Time M630", "Instant", "6 U U",
   ["A:SP$ Dig | Cost$ 6 U U | DigNum$ 7 | DestinationZone$ Hand | ChangeNum$ 2",
    "K:Delve"]],
  ["treasure-cruise-m630", "Treasure Cruise M630", "Sorcery", "7 U",
   ["A:SP$ Draw | Cost$ 7 U | NumCards$ 3",
    "K:Delve"]],
  ["become-immense-delve-m630", "Become Immense Delve M630", "Instant", "4 G",
   ["A:SP$ Pump | Cost$ 4 G | TargetType$ Creature | ValidTgts$ Creature | NumAtt$ +6 | NumDef$ +6 | KW$ Trample",
    "K:Delve"]],
  ["temporal-mastery-m630", "Temporal Mastery M630", "Sorcery", "1 U U U U",
   ["A:SP$ AddTurn | Cost$ 1 U U U U | NumTurns$ 1",
    "K:Miracle:1 U"]],

  // ── Adventure / split.
  ["brazen-borrower-m630", "Brazen Borrower M630", "Creature Faerie Rogue", "1 U U",
   ["PT:3/1",
    "K:Flash",
    "K:Flying"]],
  ["bonecrusher-giant-m630", "Bonecrusher Giant M630", "Creature Giant", "1 R R",
   ["PT:4/3"]],
  ["lovestruck-beast-m630", "Lovestruck Beast M630", "Creature Beast Noble", "1 G G",
   ["PT:5/5"]],
  ["foulmire-knight-m630", "Foulmire Knight M630", "Creature Zombie Knight", "B",
   ["PT:1/1",
    "K:Deathtouch"]],

  // ── Spree / X-modes.
  ["bonny-pall-m630", "Bonny Pall M630", "Legendary Creature Cephalid Pirate", "4 G U",
   ["PT:6/6"]],

  // ── Daybound / wolf.
  ["reckless-stormseeker-m630", "Reckless Stormseeker M630", "Creature Human Werewolf", "2 R",
   ["PT:3/2",
    "K:Daybound",
    "S:Mode$ Continuous | Affected$ Creature.YouCtrl | AddKeyword$ Haste"]],
  ["arlinn-the-packs-hope-m630", "Arlinn Packs Hope M630", "Legendary Planeswalker Arlinn", "2 G W",
   ["Loyalty:4",
    "K:Daybound",
    "A:AB$ Pump | Cost$ AddCounter<1/LOYALTY> | TargetType$ Creature | ValidTgts$ Creature.YouCtrl | NumAtt$ +1 | KW$ Vigilance & Trample"]],

  // ── Foretell / hidden.
  ["augury-raven-m630", "Augury Raven M630", "Creature Bird", "2 U",
   ["PT:2/2",
    "K:Flying",
    "K:Foretell:U"]],
  ["behold-the-multiverse-m630", "Behold Multiverse M630", "Instant", "3 U",
   ["A:SP$ Draw | Cost$ 3 U | NumCards$ 2",
    "K:Foretell:1 U"]],

  // ── Outlast / kicker / scry.
  ["abzan-falconer-m630", "Abzan Falconer M630", "Creature Human Soldier", "2 W",
   ["PT:2/3",
    "K:Outlast:W",
    "S:Mode$ Continuous | Affected$ Creature.YouCtrl+counters_GE1_P1P1 | AddKeyword$ Flying"]],
  ["ainok-bond-kin-m630", "Ainok Bond Kin M630", "Creature Hound Soldier", "2 W",
   ["PT:2/2",
    "K:Outlast:W"]],

  // ── Mass effects.
  ["plague-wind-m630", "Plague Wind M630", "Sorcery", "7 B B",
   ["A:SP$ DestroyAll | Cost$ 7 B B | ValidCards$ Creature.OppCtrl"]],
  ["in-garruks-wake-m630", "Garruks Wake M630", "Sorcery", "7 B B",
   ["A:SP$ DestroyAll | Cost$ 7 B B | ValidCards$ Creature.OppCtrl,Planeswalker.OppCtrl"]],
  ["austere-command-m630", "Austere Command M630", "Sorcery", "4 W W",
   ["A:SP$ Charm | Cost$ 4 W W | Choices$ DestroyArt,DestroyEnch,DestroyBig,DestroySmall | CharmNum$ 2"]],
  ["cyclonic-rift-m630", "Cyclonic Rift M630", "Instant", "1 U",
   ["A:SP$ ChangeZone | Cost$ 1 U | Origin$ Battlefield | Destination$ Hand | TargetType$ NonlandPermanent | ValidTgts$ Permanent.OppCtrl+nonLand"]],

  // ── Misc walkers / rare effects.
  ["karn-liberated-m630", "Karn Liberated M630", "Legendary Planeswalker Karn", "7",
   ["Loyalty:6",
    "A:AB$ ChangeZone | Cost$ SubCounter<3/LOYALTY> | TargetType$ NonlandPermanent | ValidTgts$ Permanent.nonLand | Origin$ Battlefield | Destination$ Exile"]],
  ["ugin-the-spirit-dragon-m630", "Ugin Spirit Dragon M630", "Legendary Planeswalker Ugin", "8",
   ["Loyalty:7",
    "A:AB$ DealDamage | Cost$ SubCounter<3/LOYALTY> | NumDmg$ 3 | ValidTgts$ Any"]],
  ["nicol-bolas-m630", "Nicol Bolas M630", "Legendary Planeswalker Bolas", "4 U B B R",
   ["Loyalty:5",
    "A:AB$ Discard | Cost$ AddCounter<1/LOYALTY> | NumCards$ 1 | Defined$ Opponent | Mode$ TgtChoose"]],

  // ── Mill.
  ["glimpse-the-unthinkable-m630", "Glimpse Unthinkable M630", "Sorcery", "U B",
   ["A:SP$ Mill | Cost$ U B | NumCards$ 10 | Defined$ Targeted | TargetType$ Player | ValidTgts$ Player"]],
  ["mind-funeral-m630", "Mind Funeral M630", "Sorcery", "1 U B",
   ["A:SP$ Mill | Cost$ 1 U B | NumCards$ 4 | Defined$ Targeted | TargetType$ Player | ValidTgts$ Player"]],
  ["traumatize-m630", "Traumatize M630", "Sorcery", "3 U U",
   ["A:SP$ Mill | Cost$ 3 U U | NumCards$ X | Defined$ Targeted | TargetType$ Player | ValidTgts$ Player | References$ X",
    "SVar:X:Count$Valid Card.YouCtrl+inLibrary"]],
  ["startled-awake-m630", "Startled Awake M630", "Sorcery", "2 U U",
   ["A:SP$ Mill | Cost$ 2 U U | NumCards$ 13 | Defined$ Targeted | TargetType$ Player | ValidTgts$ Player"]],
  ["maddening-cacophony-m630", "Maddening Cacophony M630", "Sorcery", "1 U",
   ["A:SP$ Mill | Cost$ 1 U | NumCards$ 8 | Defined$ Targeted | TargetType$ Player | ValidTgts$ Player",
    "K:Kicker:3 U"]],

  // ── Misc Vanilla.
  ["plains-walker-m630", "Plains Walker M630", "Creature Goblin", "R",
   ["PT:1/1",
    "K:Plainswalk"]],
  ["islandwalk-m630", "Island Walker M630", "Creature Merfolk", "1 U",
   ["PT:2/1",
    "K:Islandwalk"]],
  ["forestwalk-m630", "Forest Walker M630", "Creature Elf", "1 G",
   ["PT:2/2",
    "K:Forestwalk"]],
  ["swampwalk-m630", "Swamp Walker M630", "Creature Vampire", "1 B",
   ["PT:2/2",
    "K:Swampwalk"]],
  ["mountainwalk-m630", "Mountain Walker M630", "Creature Goblin", "1 R",
   ["PT:2/2",
    "K:Mountainwalk"]],

  // ── Aggro 1-drops.
  ["champion-of-the-parish-m630", "Champion Parish M630", "Creature Human Soldier", "W",
   ["PT:1/1"]],
  ["dragon-hatchling-m630", "Dragon Hatchling M630", "Creature Dragon", "R",
   ["PT:0/1",
    "K:Flying"]],
  ["serra-ascendant-m630", "Serra Ascendant M630", "Creature Human Monk", "W",
   ["PT:1/1",
    "K:Lifelink"]],
  ["soul-warden-m630", "Soul Warden M630", "Creature Human Cleric", "W",
   ["PT:1/1"]],
  ["soul-attendant-m630", "Soul Attendant M630", "Creature Human Cleric", "W",
   ["PT:1/1"]],
  ["impulsive-pilferer-m630", "Impulsive Pilferer M630", "Creature Goblin Pirate", "R",
   ["PT:1/1",
    "K:Haste"]],

  // ── Buff / lord-of effects.
  ["coat-of-arms-m630", "Coat Arms M630", "Artifact", "5",
   ["S:Mode$ Continuous | Affected$ Creature | AddPower$ X | AddToughness$ X | References$ X",
    "SVar:X:Count$Valid Creature.sharesTypeWith"]],
  ["intangible-virtue-m630", "Intangible Virtue M630", "Enchantment", "1 W",
   ["S:Mode$ Continuous | Affected$ Creature.token+YouCtrl | AddPower$ 1 | AddToughness$ 1 | AddKeyword$ Vigilance"]],
  ["gaeas-anthem-m630", "Gaeas Anthem M630", "Enchantment", "1 G",
   ["S:Mode$ Continuous | Affected$ Creature.YouCtrl | AddPower$ 1 | AddToughness$ 1"]],
  ["glorious-anthem-m630", "Glorious Anthem M630", "Enchantment", "1 W W",
   ["S:Mode$ Continuous | Affected$ Creature.YouCtrl | AddPower$ 1 | AddToughness$ 1"]],
  ["crusade-m630", "Crusade M630", "Enchantment", "W W",
   ["S:Mode$ Continuous | Affected$ Creature.White | AddPower$ 1 | AddToughness$ 1"]],

  // ── Fetch creatures / etb.
  ["solemn-simulacrum-m630", "Solemn Simulacrum M630", "Artifact Creature Golem", "4",
   ["PT:2/2",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigSearch",
    "SVar:TrigSearch:DB$ ChangeZone | Origin$ Library | Destination$ Battlefield | ChangeType$ BasicLand | Tapped$ True | ChangeNum$ 1"]],
  ["pilgrims-eye-m630", "Pilgrims Eye M630", "Artifact Creature Thopter", "3",
   ["PT:1/1",
    "K:Flying",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigSearch",
    "SVar:TrigSearch:DB$ ChangeZone | Origin$ Library | Destination$ Battlefield | ChangeType$ BasicLand | Tapped$ True | ChangeNum$ 1"]],
  ["burnished-hart-m630", "Burnished Hart M630", "Artifact Creature Elk", "3",
   ["PT:2/2",
    "A:AB$ ChangeZone | Cost$ 3 T Sac<1/CARDNAME> | Origin$ Library | Destination$ Battlefield | ChangeType$ BasicLand | ChangeNum$ 2 | Tapped$ True"]],
  ["wayfarers-bauble-m630", "Wayfarers Bauble M630", "Artifact", "1",
   ["A:AB$ ChangeZone | Cost$ 2 T Sac<1/CARDNAME> | Origin$ Library | Destination$ Battlefield | ChangeType$ BasicLand | Tapped$ True"]],

  // ── Extra batch — bring total to 350.
  ["spire-garden-m630", "Spire Garden M630", "Land", "no cost",
   ["A:AB$ Mana | Cost$ T | Produced$ R G W"]],
  ["luxury-suite-m630", "Luxury Suite M630", "Land", "no cost",
   ["A:AB$ Mana | Cost$ T | Produced$ B R W"]],
  ["bountiful-promenade-m630", "Bountiful Promenade M630", "Land", "no cost",
   ["A:AB$ Mana | Cost$ T | Produced$ G W"]],
  ["sea-of-clouds-m630", "Sea Clouds M630", "Land", "no cost",
   ["A:AB$ Mana | Cost$ T | Produced$ W U"]],
  ["morphic-pool-m630", "Morphic Pool M630", "Land", "no cost",
   ["A:AB$ Mana | Cost$ T | Produced$ U B"]],
  ["training-center-m630", "Training Center M630", "Land", "no cost",
   ["A:AB$ Mana | Cost$ T | Produced$ W U"]],
  ["raffines-tower-m630", "Raffines Tower M630", "Land", "no cost",
   ["A:AB$ Mana | Cost$ T | Produced$ W U B"]],
  ["zianji-tomb-m630", "Zianji Tomb M630", "Legendary Land", "no cost",
   ["A:AB$ Mana | Cost$ T | Produced$ C | Amount$ 2"]],
  ["academy-ruins-m630", "Academy Ruins M630", "Legendary Land", "no cost",
   ["A:AB$ Mana | Cost$ T | Produced$ C",
    "A:AB$ ChangeZone | Cost$ 1 U T | Origin$ Graveyard | Destination$ Library | TargetType$ Card | ValidTgts$ Artifact | LibraryPosition$ 0"]],
  ["volrath-stronghold-m630", "Volrath Stronghold M630", "Legendary Land", "no cost",
   ["A:AB$ Mana | Cost$ T | Produced$ C",
    "A:AB$ ChangeZone | Cost$ 1 B T | Origin$ Graveyard | Destination$ Library | TargetType$ Card | ValidTgts$ Creature | LibraryPosition$ 0"]],
  ["castle-locthwain-m630", "Castle Locthwain M630", "Land", "no cost",
   ["A:AB$ Mana | Cost$ T | Produced$ C",
    "A:AB$ Draw | Cost$ 1 B B B T | NumCards$ 1"]],
  ["castle-ardenvale-m630", "Castle Ardenvale M630", "Land", "no cost",
   ["A:AB$ Mana | Cost$ T | Produced$ C",
    "A:AB$ Token | Cost$ 2 W W T | TokenScript$ w_1_1_human | TokenAmount$ 1"]],
  ["castle-vantress-m630", "Castle Vantress M630", "Land", "no cost",
   ["A:AB$ Mana | Cost$ T | Produced$ C",
    "A:AB$ Effect | Cost$ 2 U U T | SpellDescription$ Scry 2."]],
  ["castle-embereth-m630", "Castle Embereth M630", "Land", "no cost",
   ["A:AB$ Mana | Cost$ T | Produced$ C",
    "A:AB$ PumpAll | Cost$ 1 R R T | ValidCards$ Creature.YouCtrl | NumAtt$ +1 | NumDef$ +1"]],
  ["castle-garenbrig-m630", "Castle Garenbrig M630", "Land", "no cost",
   ["A:AB$ Mana | Cost$ T | Produced$ C",
    "A:AB$ Mana | Cost$ 2 G G T | Produced$ G | Amount$ 6 | RestrictValid$ Creature"]],
  ["serra-paragon-m630", "Serra Paragon M630", "Creature Angel", "3 W W",
   ["PT:3/4",
    "K:Flying",
    "K:Vigilance"]],
  ["sheoldred-the-apocalypse-m630", "Sheoldred Apocalypse M630", "Legendary Creature Phyrexian Praetor", "2 B B",
   ["PT:4/5",
    "K:Deathtouch"]],
  ["urabrask-the-hidden-m630", "Urabrask Hidden M630", "Legendary Creature Phyrexian", "3 R R",
   ["PT:4/4",
    "K:Haste"]],
  ["jin-gitaxias-m630", "Jin Gitaxias M630", "Legendary Creature Phyrexian Praetor", "5 U U U",
   ["PT:5/4",
    "K:Flash"]],
  ["elesh-norn-grand-cenobite-m630", "Elesh Norn Grand Cenobite M630", "Legendary Creature Phyrexian Praetor", "5 W W",
   ["PT:4/7",
    "K:Vigilance"]],
  ["vorinclex-voice-of-hunger-m630", "Vorinclex Voice Hunger M630", "Legendary Creature Phyrexian Praetor", "6 G G",
   ["PT:7/6",
    "K:Trample"]],
  ["griselbrand-m630", "Griselbrand M630", "Legendary Creature Demon", "4 B B B B",
   ["PT:7/7",
    "K:Flying",
    "K:Lifelink"]],
  ["emrakul-the-aeons-torn-m630", "Emrakul Aeons Torn M630", "Legendary Creature Eldrazi", "15",
   ["PT:15/15",
    "K:Flying",
    "K:Trample",
    "K:Protection from colored spells",
    "K:Annihilator:6"]],
  ["ulamog-the-ceaseless-hunger-m630", "Ulamog Ceaseless Hunger M630", "Legendary Creature Eldrazi", "10",
   ["PT:10/10",
    "K:Indestructible"]],
  ["kozilek-butcher-of-truth-m630", "Kozilek Butcher Truth M630", "Legendary Creature Eldrazi", "10",
   ["PT:12/12",
    "K:Annihilator:4"]],
];

const seedStart = 0xc000;
let i = 2435;
let seed = seedStart;
let out = "";
for (const [stem, name, types, cost, lines] of CARDS) {
  const fullName = name + " M630";
  const id = stem + (stem.endsWith("-m630") ? "" : "-m630");
  out += "\n  // " + i + ". " + fullName + " ETB.\n";
  out += "  {\n";
  out += "    id: \"" + id + "\",\n";
  out += "    description: \"" + fullName + " ETB.\",\n";
  out += "    seed: 0x" + seed.toString(16) + ",\n";
  out += "    cards: {\n";
  out += "      \"" + fullName + "\": `Name:" + fullName + "\nManaCost:" + cost + "\nTypes:" + types + "\n";
  for (const ln of lines) out += ln + "\n";
  out += "Oracle:" + fullName.split(" ").map(w => w[0]).join("") + " parse.\n`,\n";
  out += "    },\n";
  out += "    players: [\n";
  out += "      { life: 20, hand: [\"" + fullName + "\"], battlefield: [] },\n";
  out += "      { life: 20, hand: [], battlefield: [] },\n";
  out += "    ],\n";
  out += "    actions: [{ kind: \"etb\", cardName: \"" + fullName + "\", controller: SEAT0 }],\n";
  out += "  },\n";
  i++;
  seed++;
}
console.error("// generated " + CARDS.length + " scenarios; next i=" + i + ", next seed=0x" + seed.toString(16));
process.stdout.write(out);
