#!/usr/bin/env node
// SPDX-License-Identifier: GPL-3.0-or-later
//
// Generator for M6.29 wave: produces 300+ ETB scenarios appended to
// scenarios.ts in the synthetic-name (M629 suffix) pattern. Each scenario is
// a self-contained Forge .txt card with a single { kind: "etb" } action.

import fs from "node:fs";
import path from "node:path";

// ── Card list — each entry: [id-stem, name, types, cost, [scriptLines...]]
//   `id-stem` becomes the kebab-case scenario id (with -m629 suffix appended).
//   `name` becomes the in-game card name (with " M629" suffix appended).
//   Lines are spliced literally into the inline cardSource between Types and Oracle.
const CARDS = [
  // ── Sagas — full chapter machinery (Forge fires LORE counter → chapter trigger).
  ["welcome-to-skys-end", "Welcome to Skys End", "Enchantment Saga", "1 W",
   ["T:Mode$ CounterAddedOnce | ValidCard$ Card.Self | CounterType$ LORE | NewCounterAmount$ 1 | Execute$ TrigTok",
    "T:Mode$ CounterAddedOnce | ValidCard$ Card.Self | CounterType$ LORE | NewCounterAmount$ 2 | Execute$ TrigTok",
    "T:Mode$ CounterAddedOnce | ValidCard$ Card.Self | CounterType$ LORE | NewCounterAmount$ 3 | Execute$ TrigChoose",
    "SVar:TrigTok:DB$ Token | TokenScript$ w_1_1_human_soldier | TokenAmount$ 1",
    "SVar:TrigChoose:DB$ ChooseCard | ValidTgts$ Creature.YouCtrl"]],
  ["mending-of-dominaria-saga", "Mending of Dominaria", "Enchantment Saga", "3 G G",
   ["T:Mode$ CounterAddedOnce | ValidCard$ Card.Self | CounterType$ LORE | NewCounterAmount$ 1 | Execute$ TrigSac",
    "T:Mode$ CounterAddedOnce | ValidCard$ Card.Self | CounterType$ LORE | NewCounterAmount$ 2 | Execute$ TrigReturn",
    "T:Mode$ CounterAddedOnce | ValidCard$ Card.Self | CounterType$ LORE | NewCounterAmount$ 3 | Execute$ TrigShuffle",
    "SVar:TrigSac:DB$ Sacrifice | SacValid$ Creature | Amount$ 1",
    "SVar:TrigReturn:DB$ ChangeZone | Origin$ Graveyard | Destination$ Battlefield | TargetType$ Card | ValidTgts$ Creature.YouCtrl",
    "SVar:TrigShuffle:DB$ ChangeZoneAll | ChangeType$ Card.YouOwn | Origin$ Graveyard | Destination$ Library | Shuffle$ True"]],
  ["phyrexian-scriptures-saga", "Phyrexian Scriptures", "Enchantment Saga", "2 B",
   ["T:Mode$ CounterAddedOnce | ValidCard$ Card.Self | CounterType$ LORE | NewCounterAmount$ 1 | Execute$ TrigCntr",
    "T:Mode$ CounterAddedOnce | ValidCard$ Card.Self | CounterType$ LORE | NewCounterAmount$ 2 | Execute$ TrigDestroy",
    "SVar:TrigCntr:DB$ PutCounter | Defined$ Creature.YouCtrl | CounterType$ M1M1 | CounterNum$ 1",
    "SVar:TrigDestroy:DB$ DestroyAll | ValidCards$ Creature.nonArtifact"]],
  ["time-of-ice-saga", "Time of Ice", "Enchantment Saga", "3 U",
   ["T:Mode$ CounterAddedOnce | ValidCard$ Card.Self | CounterType$ LORE | NewCounterAmount$ 1 | Execute$ TrigTap",
    "T:Mode$ CounterAddedOnce | ValidCard$ Card.Self | CounterType$ LORE | NewCounterAmount$ 4 | Execute$ TrigBounce",
    "SVar:TrigTap:DB$ TapAll | ValidCards$ Creature.OpponentCtrl",
    "SVar:TrigBounce:DB$ ChangeZoneAll | ChangeType$ Creature.tapped | Origin$ Battlefield | Destination$ Hand"]],
  ["fall-of-the-thran-saga", "Fall of the Thran", "Enchantment Saga", "5 W",
   ["T:Mode$ CounterAddedOnce | ValidCard$ Card.Self | CounterType$ LORE | NewCounterAmount$ 1 | Execute$ TrigDestroyLand",
    "SVar:TrigDestroyLand:DB$ DestroyAll | ValidCards$ Land"]],
  ["chainer-nightmare-adept-saga", "Chainer Nightmare", "Enchantment Saga", "3 B",
   ["T:Mode$ CounterAddedOnce | ValidCard$ Card.Self | CounterType$ LORE | NewCounterAmount$ 1 | Execute$ TrigDiscard",
    "SVar:TrigDiscard:DB$ Discard | NumCards$ 2 | Mode$ TgtChoose"]],
  ["history-of-benalia-saga2", "History of Benalia", "Enchantment Saga", "1 W W",
   ["T:Mode$ CounterAddedOnce | ValidCard$ Card.Self | CounterType$ LORE | NewCounterAmount$ 1 | Execute$ TrigTokKnight",
    "T:Mode$ CounterAddedOnce | ValidCard$ Card.Self | CounterType$ LORE | NewCounterAmount$ 3 | Execute$ TrigKnightAnthem",
    "SVar:TrigTokKnight:DB$ Token | TokenScript$ w_2_2_knight | TokenAmount$ 1",
    "SVar:TrigKnightAnthem:DB$ PumpAll | ValidCards$ Knight.YouCtrl | NumAtt$ +2 | NumDef$ +1"]],
  ["elspeth-conquers-death-saga", "Elspeth Conquers Death", "Enchantment Saga", "3 W W",
   ["T:Mode$ CounterAddedOnce | ValidCard$ Card.Self | CounterType$ LORE | NewCounterAmount$ 1 | Execute$ TrigExile",
    "T:Mode$ CounterAddedOnce | ValidCard$ Card.Self | CounterType$ LORE | NewCounterAmount$ 3 | Execute$ TrigReturn",
    "SVar:TrigExile:DB$ ChangeZone | Origin$ Battlefield | Destination$ Exile | TargetType$ Card | ValidTgts$ Creature.OppCtrl+cmcGE3",
    "SVar:TrigReturn:DB$ ChangeZone | Origin$ Graveyard | Destination$ Battlefield | TargetType$ Card | ValidTgts$ Creature.YouCtrl"]],
  ["binding-the-old-gods-saga", "Binding the Old Gods", "Enchantment Saga", "2 B G",
   ["T:Mode$ CounterAddedOnce | ValidCard$ Card.Self | CounterType$ LORE | NewCounterAmount$ 1 | Execute$ TrigDestroy",
    "T:Mode$ CounterAddedOnce | ValidCard$ Card.Self | CounterType$ LORE | NewCounterAmount$ 2 | Execute$ TrigSearch",
    "T:Mode$ CounterAddedOnce | ValidCard$ Card.Self | CounterType$ LORE | NewCounterAmount$ 3 | Execute$ TrigPump",
    "SVar:TrigDestroy:DB$ Destroy | TargetType$ Permanent | ValidTgts$ Permanent.OppCtrl+nonCreature+nonLand",
    "SVar:TrigSearch:DB$ ChangeZone | ChangeType$ Forest | Origin$ Library | Destination$ Battlefield",
    "SVar:TrigPump:DB$ PumpAll | ValidCards$ Creature.YouCtrl | NumAtt$ +1 | NumDef$ +1 | KW$ Trample"]],
  ["the-elder-dragon-war-saga", "Elder Dragon War", "Enchantment Saga", "3 R",
   ["T:Mode$ CounterAddedOnce | ValidCard$ Card.Self | CounterType$ LORE | NewCounterAmount$ 1 | Execute$ TrigDmgAll",
    "T:Mode$ CounterAddedOnce | ValidCard$ Card.Self | CounterType$ LORE | NewCounterAmount$ 2 | Execute$ TrigDmgAll",
    "T:Mode$ CounterAddedOnce | ValidCard$ Card.Self | CounterType$ LORE | NewCounterAmount$ 3 | Execute$ TrigTokDragon",
    "SVar:TrigDmgAll:DB$ DamageAll | NumDmg$ 1 | ValidCards$ Creature.OppCtrl",
    "SVar:TrigTokDragon:DB$ Token | TokenScript$ r_4_4_dragon_flying | TokenAmount$ 1"]],

  // ── Class — level-up chains (Forge: ChangesZone+CounterAdded for K_LEVEL).
  ["bard-class", "Bard Class", "Enchantment Class", "1 R G",
   ["T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigEntered",
    "K:Class:1:R G",
    "K:Class:2:1 R G",
    "K:Class:3:2 R G",
    "SVar:TrigEntered:DB$ Token | TokenScript$ rg_2_2_human_warrior | TokenAmount$ 1"]],
  ["cleric-class", "Cleric Class", "Enchantment Class", "W",
   ["T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigGain",
    "K:Class:1:W",
    "K:Class:2:1 W",
    "K:Class:3:3 W",
    "SVar:TrigGain:DB$ GainLife | LifeAmount$ 2"]],
  ["wizard-class", "Wizard Class", "Enchantment Class", "U",
   ["T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigDraw",
    "K:Class:1:U",
    "K:Class:2:2 U",
    "K:Class:3:4 U",
    "SVar:TrigDraw:DB$ Draw | NumCards$ 1"]],
  ["warlock-class", "Warlock Class", "Enchantment Class", "1 B",
   ["T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigLoseLife",
    "K:Class:1:1 B",
    "K:Class:2:3 B",
    "K:Class:3:5 B",
    "SVar:TrigLoseLife:DB$ LoseLife | LifeAmount$ 1 | Defined$ Player.Opponent"]],
  ["monk-class", "Monk Class", "Enchantment Class", "G",
   ["T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigPump",
    "K:Class:1:G",
    "K:Class:2:1 G",
    "K:Class:3:3 G",
    "SVar:TrigPump:DB$ PumpAll | ValidCards$ Creature.YouCtrl | NumAtt$ +1 | NumDef$ +1"]],
  ["barbarian-class", "Barbarian Class", "Enchantment Class", "1 R",
   ["T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigDmg",
    "K:Class:1:1 R",
    "K:Class:2:R",
    "K:Class:3:2 R",
    "SVar:TrigDmg:DB$ DealDamage | NumDmg$ 1 | DefinedTarget$ Player.Opponent"]],
  ["paladin-class", "Paladin Class", "Enchantment Class", "1 W",
   ["T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigToken",
    "K:Class:1:1 W",
    "K:Class:2:2 W",
    "K:Class:3:3 W",
    "SVar:TrigToken:DB$ Token | TokenScript$ w_1_1_soldier | TokenAmount$ 2"]],
  ["ranger-class", "Ranger Class", "Enchantment Class", "1 G",
   ["T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigToken",
    "K:Class:1:1 G",
    "K:Class:2:2 G",
    "K:Class:3:4 G",
    "SVar:TrigToken:DB$ Token | TokenScript$ g_1_1_wolf | TokenAmount$ 2"]],
  ["rogue-class", "Rogue Class", "Enchantment Class", "1 B",
   ["T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigCreate",
    "K:Class:1:1 B",
    "K:Class:2:2 B",
    "K:Class:3:4 B",
    "SVar:TrigCreate:DB$ Token | TokenScript$ b_1_1_rogue | TokenAmount$ 1"]],
  ["sorcerer-class", "Sorcerer Class", "Enchantment Class", "U R",
   ["T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigDraw",
    "K:Class:1:U R",
    "K:Class:2:1 U R",
    "K:Class:3:2 U R",
    "SVar:TrigDraw:DB$ Draw | NumCards$ 1"]],

  // ── Battles — defense counters + transform on defeat.
  ["invasion-of-ikoria-battle", "Invasion Ikoria", "Battle Siege", "5 G",
   ["T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigPlace",
    "Defense$ 5",
    "SVar:TrigPlace:DB$ ChangeZone | Origin$ Library | Destination$ Hand | ChangeType$ Creature | ChangeNum$ 1"]],
  ["invasion-of-karsus-battle", "Invasion Karsus", "Battle Siege", "5 R",
   ["T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigDmg",
    "Defense$ 4",
    "SVar:TrigDmg:DB$ DealDamage | NumDmg$ 5 | DefinedTarget$ Creature.OppCtrl"]],
  ["invasion-of-zendikar-battle", "Invasion Zendikar", "Battle Siege", "4 G",
   ["T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigSearch",
    "Defense$ 4",
    "SVar:TrigSearch:DB$ ChangeZone | Origin$ Library | Destination$ Battlefield | ChangeType$ Land | ChangeNum$ 2"]],
  ["invasion-of-arcavios-battle", "Invasion Arcavios", "Battle Siege", "3 U U",
   ["T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigSearch",
    "Defense$ 4",
    "SVar:TrigSearch:DB$ ChangeZone | Origin$ Library | Destination$ Hand | ChangeType$ Instant,Sorcery | ChangeNum$ 1"]],
  ["invasion-of-fiora-battle", "Invasion Fiora", "Battle Siege", "3 W B",
   ["T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigDestroyAll",
    "Defense$ 4",
    "SVar:TrigDestroyAll:DB$ DestroyAll | ValidCards$ Creature.OppCtrl"]],
  ["invasion-of-kaldheim-battle", "Invasion Kaldheim", "Battle Siege", "3 R G",
   ["T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigToken",
    "Defense$ 5",
    "SVar:TrigToken:DB$ Token | TokenScript$ rg_3_3_giant | TokenAmount$ 2"]],
  ["invasion-of-ravnica-battle", "Invasion Ravnica", "Battle Siege", "5 W U",
   ["T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigCounter",
    "Defense$ 6",
    "SVar:TrigCounter:DB$ Counter | TargetType$ Spell | ValidTgts$ Card"]],
  ["invasion-of-eldraine-battle", "Invasion Eldraine", "Battle Siege", "1 W",
   ["T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigToken",
    "Defense$ 2",
    "SVar:TrigToken:DB$ Token | TokenScript$ wb_1_1_human | TokenAmount$ 2"]],

  // ── Day/Night flip-cards (front face + game-flag flip on cast counts).
  ["reckless-stormseeker-werewolf", "Reckless Stormseeker", "Creature Werewolf", "2 R",
   ["PT:3/3",
    "K:Daybound",
    "T:Mode$ Attacks | ValidCard$ Creature.YouCtrl | TriggerZones$ Battlefield | Execute$ TrigPump",
    "SVar:TrigPump:DB$ Pump | Defined$ TriggeredAttacker | NumAtt$ +1 | KW$ Haste"]],
  ["tovolar-dire-overlord-werewolf", "Tovolar Dire Overlord", "Legendary Creature Werewolf", "2 R G",
   ["PT:3/3",
    "K:Daybound",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigDraw",
    "SVar:TrigDraw:DB$ Draw | NumCards$ 1"]],
  ["arlinn-the-packs-hope-walker", "Arlinn Packs Hope", "Legendary Planeswalker", "2 G W",
   ["Loyalty:4",
    "A:AB$ Token | Cost$ AddCounter<1/LOYALTY> | TokenScript$ g_2_2_wolf | TokenAmount$ 1"]],
  ["sun-titan-werewolf-dayflip", "Sun Titan Daybound", "Creature Giant", "4 W W",
   ["PT:6/6",
    "K:Vigilance",
    "K:Daybound",
    "T:Mode$ Attacks | ValidCard$ Card.Self | Execute$ TrigReturn",
    "SVar:TrigReturn:DB$ ChangeZone | Origin$ Graveyard | Destination$ Battlefield | TargetType$ Card | ValidTgts$ Permanent.YouCtrl+cmcLE3"]],
  ["moon-flip-tracker-werewolf", "Moonflip Tracker", "Creature Werewolf", "2 G",
   ["PT:3/2",
    "K:Daybound",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigSearch",
    "SVar:TrigSearch:DB$ ChangeZone | Origin$ Library | Destination$ Hand | ChangeType$ Land | ChangeNum$ 1"]],

  // ── Plot — exile from hand for cost, cast next turn.
  ["beastbond-outcaster-plot", "Beastbond Outcaster", "Creature Human Druid", "G",
   ["PT:1/1",
    "K:Plot:1 G"]],
  ["slick-sequence-plot", "Slick Sequence", "Sorcery", "U R",
   ["A:SP$ Pump | Cost$ U R | TargetType$ Creature | ValidTgts$ Creature | NumAtt$ +1 | NumDef$ +0",
    "K:Plot:1 U R"]],
  ["pawpatch-formation-plot", "Pawpatch Formation", "Instant", "1 G",
   ["A:SP$ PumpAll | Cost$ 1 G | ValidCards$ Creature.YouCtrl | NumAtt$ +1 | NumDef$ +1",
    "K:Plot:G"]],
  ["heartfire-immolator-plot", "Heartfire Immolator", "Creature Human Wizard", "1 R",
   ["PT:2/2",
    "K:Plot:R",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigDmg",
    "SVar:TrigDmg:DB$ DealDamage | NumDmg$ 2 | DefinedTarget$ Any"]],
  ["caustic-bronco-plot", "Caustic Bronco", "Creature Horse", "1 B",
   ["PT:2/2",
    "K:Plot:1 B",
    "K:Menace"]],

  // ── Suspend full timer.
  ["ancestral-vision-suspend", "Ancestral Vision", "Sorcery", "noCost",
   ["K:Suspend:4:U",
    "A:SP$ Draw | Cost$ U | NumCards$ 3 | Defined$ You | SpellDescription$ AV"]],
  ["lotus-bloom-suspend", "Lotus Bloom", "Artifact", "noCost",
   ["K:Suspend:3:0",
    "A:AB$ Mana | Cost$ T Sac<1/CARDNAME> | Produced$ Any | Amount$ 3"]],
  ["wheel-of-fate-suspend", "Wheel of Fate", "Sorcery", "noCost",
   ["K:Suspend:4:R",
    "A:SP$ Draw | Cost$ R | NumCards$ 7 | Defined$ Player"]],
  ["restore-balance-suspend", "Restore Balance", "Sorcery", "noCost",
   ["K:Suspend:6:W",
    "A:SP$ Effect | Cost$ W | SpellDescription$ Equalize"]],
  ["greater-gargadon-suspend", "Greater Gargadon", "Creature Beast", "8 R",
   ["PT:9/7",
    "K:Suspend:10:R",
    "A:AB$ Effect | Cost$ Sac<1/Permanent.YouCtrl/permanent>"]],
  ["search-for-tomorrow-suspend", "Search for Tomorrow", "Sorcery", "2 G",
   ["A:SP$ ChangeZone | Cost$ 2 G | Origin$ Library | Destination$ Battlefield | ChangeType$ BasicLand | ChangeNum$ 1",
    "K:Suspend:2:G"]],
  ["rift-bolt-suspend", "Rift Bolt", "Sorcery", "2 R",
   ["A:SP$ DealDamage | Cost$ 2 R | NumDmg$ 3 | ValidTgts$ Any",
    "K:Suspend:1:R"]],

  // ── Foretell — cast for less from exile.
  ["augury-raven-foretell", "Augury Raven", "Creature Bird", "3 U",
   ["PT:2/3",
    "K:Flying",
    "K:Foretell:1 U",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigScry",
    "SVar:TrigScry:DB$ Scry | ScryNum$ 2"]],
  ["behold-the-multiverse-foretell", "Behold Multiverse", "Instant", "3 U",
   ["A:SP$ Draw | Cost$ 3 U | NumCards$ 2 | SubAbility$ DBScry",
    "K:Foretell:1 U",
    "SVar:DBScry:DB$ Scry | ScryNum$ 2"]],
  ["cosmic-intervention-foretell", "Cosmic Intervention", "Instant", "2 W W",
   ["A:SP$ Effect | Cost$ 2 W W | SpellDescription$ Indestructible.",
    "K:Foretell:1 W"]],
  ["disdainful-stroke-foretell", "Disdainful Stroke F", "Instant", "1 U",
   ["A:SP$ Counter | Cost$ 1 U | TargetType$ Spell | ValidTgts$ Card.cmcGE4",
    "K:Foretell:U"]],
  ["doomskar-foretell", "Doomskar", "Sorcery", "3 W W",
   ["A:SP$ DestroyAll | Cost$ 3 W W | ValidCards$ Creature",
    "K:Foretell:2 W"]],
  ["saw-it-coming-foretell", "Saw It Coming", "Instant", "2 U",
   ["A:SP$ Counter | Cost$ 2 U | TargetType$ Spell | ValidTgts$ Card",
    "K:Foretell:1 U"]],
  ["the-trickster-god-foretell", "Trickster God", "Legendary Creature God", "1 U",
   ["PT:2/2",
    "K:Foretell:U"]],

  // ── Adventure cards — both halves printed.
  ["bonecrusher-giant-adventure-m629", "Bonecrusher Giant", "Creature Giant", "1 R",
   ["PT:4/3",
    "ALTERNATE",
    "Name:Stomp Adventure",
    "ManaCost:1 R",
    "Types:Instant Adventure",
    "A:SP$ DealDamage | Cost$ 1 R | NumDmg$ 2 | ValidTgts$ Creature,Player"]],
  ["murderous-rider-adventure-m629", "Murderous Rider", "Creature Zombie Knight", "1 B B",
   ["PT:2/3",
    "K:Lifelink",
    "ALTERNATE",
    "Name:Swift End",
    "ManaCost:1 B B",
    "Types:Instant Adventure",
    "A:SP$ Destroy | Cost$ 1 B B | TargetType$ Creature,Planeswalker | ValidTgts$ Creature.nonBlack,Planeswalker"]],
  ["lovestruck-beast-adventure-m629", "Lovestruck Beast", "Creature Beast Noble", "1 G G",
   ["PT:5/5",
    "ALTERNATE",
    "Name:Heart's Desire",
    "ManaCost:G",
    "Types:Sorcery Adventure",
    "A:SP$ Token | Cost$ G | TokenScript$ g_1_1_human | TokenAmount$ 1"]],
  ["brazen-borrower-adventure-m629", "Brazen Borrower", "Creature Faerie Rogue", "1 U U",
   ["PT:3/1",
    "K:Flash",
    "K:Flying",
    "ALTERNATE",
    "Name:Petty Theft",
    "ManaCost:1 U",
    "Types:Instant Adventure",
    "A:SP$ ChangeZone | Cost$ 1 U | Origin$ Battlefield | Destination$ Hand | TargetType$ Permanent | ValidTgts$ Permanent.OppCtrl+nonLand"]],
  ["fae-of-wishes-adventure-m629", "Fae of Wishes", "Creature Faerie Wizard", "1 U",
   ["PT:1/4",
    "K:Flying",
    "ALTERNATE",
    "Name:Granted",
    "ManaCost:1 U",
    "Types:Sorcery Adventure",
    "A:SP$ ChangeZone | Cost$ 1 U | Origin$ Sideboard | Destination$ Hand"]],
  ["realm-cloaked-giant-adventure-m629", "Realm Cloaked Giant", "Creature Giant", "5 W W",
   ["PT:7/7",
    "K:Vigilance",
    "ALTERNATE",
    "Name:Cast Off",
    "ManaCost:2 W",
    "Types:Sorcery Adventure",
    "A:SP$ DestroyAll | Cost$ 2 W | ValidCards$ Creature.nonGiant"]],

  // ── Vehicles + Crew.
  ["smugglers-copter-m629", "Smugglers Copter", "Artifact Vehicle", "2",
   ["PT:3/3",
    "K:Crew:1",
    "K:Flying",
    "T:Mode$ Attacks | ValidCard$ Card.Self | Execute$ TrigLootAttacks",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigLootETB",
    "SVar:TrigLootAttacks:DB$ Draw | NumCards$ 1 | SubAbility$ DBDiscard",
    "SVar:TrigLootETB:DB$ Effect",
    "SVar:DBDiscard:DB$ Discard | Defined$ You | NumCards$ 1 | Mode$ TgtChoose"]],
  ["skysovereign-consul-flagship-m629", "Skysovereign Consul Flagship", "Artifact Vehicle", "6",
   ["PT:6/5",
    "K:Crew:3",
    "K:Flying",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigDmg",
    "T:Mode$ Attacks | ValidCard$ Card.Self | Execute$ TrigDmg",
    "SVar:TrigDmg:DB$ DealDamage | NumDmg$ 3 | DefinedTarget$ Creature.OppCtrl,Planeswalker.OppCtrl"]],
  ["heart-of-kiran-m629", "Heart of Kiran", "Artifact Vehicle", "2",
   ["PT:4/4",
    "K:Flying",
    "K:Vigilance",
    "K:Crew:3"]],
  ["aetherflux-saber-m629", "Aetherflux Saber", "Artifact Vehicle", "1",
   ["PT:2/3",
    "K:Crew:2"]],
  ["fleetwheel-cruiser-m629", "Fleetwheel Cruiser", "Artifact Vehicle", "4",
   ["PT:5/3",
    "K:Crew:2",
    "K:Trample",
    "K:Haste"]],

  // ── Mounts + Saddle.
  ["roxanne-starfall-mount-m629", "Roxanne Starfall", "Legendary Creature Human Cowboy", "2 R G",
   ["PT:3/3",
    "K:Saddle:2",
    "T:Mode$ Attacks | ValidCard$ Card.Self+saddled | Execute$ TrigToken",
    "SVar:TrigToken:DB$ Token | TokenScript$ c_a_meteorite | TokenAmount$ 1"]],
  ["goldvein-hydra-mount-m629", "Goldvein Hydra", "Creature Hydra Mount", "X G",
   ["PT:0/0",
    "K:Saddle:3",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigCntr",
    "SVar:TrigCntr:DB$ PutCounter | Defined$ Self | CounterType$ P1P1 | CounterNum$ X | References$ X",
    "SVar:X:Count$xPaid"]],
  ["bristly-bill-mount-m629", "Bristly Bill", "Legendary Creature Boar Mount", "1 G",
   ["PT:2/2",
    "K:Saddle:2",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigCntr",
    "SVar:TrigCntr:DB$ PutCounter | Defined$ Land.YouCtrl | CounterType$ P1P1 | CounterNum$ 1"]],
  ["nimble-brigand-mount-m629", "Nimble Brigand", "Creature Human Outlaw", "1 R",
   ["PT:2/2",
    "K:Menace"]],

  // ── Cipher full encode + cast-copy.
  ["stolen-identity-cipher-m629", "Stolen Identity", "Sorcery", "4 U U",
   ["A:SP$ CopyPermanent | Cost$ 4 U U | TargetType$ Creature,Artifact | ValidTgts$ Permanent.nonLand+nonToken",
    "K:Cipher"]],
  ["whispering-madness-cipher-m629", "Whispering Madness", "Sorcery", "2 U B",
   ["A:SP$ Discard | Cost$ 2 U B | NumCards$ 7 | Defined$ Player | Mode$ Hand",
    "K:Cipher"]],
  ["last-thoughts-cipher-m629", "Last Thoughts", "Sorcery", "3 U",
   ["A:SP$ Draw | Cost$ 3 U | NumCards$ 3",
    "K:Cipher"]],
  ["shadow-slice-cipher-m629", "Shadow Slice", "Sorcery", "3 B",
   ["A:SP$ Effect | Cost$ 3 B | SpellDescription$ Discard.",
    "K:Cipher"]],

  // ── Storm.
  ["tendrils-of-agony-storm-m629", "Tendrils of Agony", "Sorcery", "2 B B",
   ["A:SP$ LoseLife | Cost$ 2 B B | LifeAmount$ 2 | Defined$ Player.Opponent | SubAbility$ DBGain",
    "K:Storm",
    "SVar:DBGain:DB$ GainLife | LifeAmount$ 2"]],
  ["empty-the-warrens-storm-m629", "Empty Warrens", "Sorcery", "3 R",
   ["A:SP$ Token | Cost$ 3 R | TokenScript$ r_1_1_goblin | TokenAmount$ 2",
    "K:Storm"]],
  ["brain-freeze-storm-m629", "Brain Freeze", "Instant", "1 U",
   ["A:SP$ Mill | Cost$ 1 U | NumCards$ 3 | TargetType$ Player",
    "K:Storm"]],
  ["mind-fly-storm-m629", "Mind Fly", "Sorcery", "1 U",
   ["A:SP$ Draw | Cost$ 1 U | NumCards$ 1",
    "K:Storm"]],
  ["grapeshot-storm-m629", "Grapeshot", "Sorcery", "1 R",
   ["A:SP$ DealDamage | Cost$ 1 R | NumDmg$ 1 | ValidTgts$ Any",
    "K:Storm"]],

  // ── Cascade.
  ["bloodbraid-elf-cascade-m629", "Bloodbraid Elf", "Creature Elf Berserker", "2 R G",
   ["PT:3/2",
    "K:Haste",
    "K:Cascade"]],
  ["maelstrom-wanderer-cascade-m629", "Maelstrom Wanderer", "Legendary Creature Elemental", "5 U R G",
   ["PT:7/5",
    "K:Haste",
    "K:Cascade",
    "K:Cascade"]],
  ["shardless-agent-cascade-m629", "Shardless Agent", "Artifact Creature Human Rogue", "U G",
   ["PT:2/2",
    "K:Cascade"]],
  ["bituminous-blast-cascade-m629", "Bituminous Blast", "Instant", "2 B R",
   ["A:SP$ DealDamage | Cost$ 2 B R | NumDmg$ 3 | ValidTgts$ Creature",
    "K:Cascade"]],
  ["enlisted-wurm-cascade-m629", "Enlisted Wurm", "Creature Wurm", "4 G W",
   ["PT:5/5",
    "K:Cascade"]],
  ["captured-sunlight-cascade-m629", "Captured Sunlight", "Instant", "3 G W",
   ["A:SP$ GainLife | Cost$ 3 G W | LifeAmount$ 4",
    "K:Cascade"]],

  // ── Mutate.
  ["auspicious-starrix-mutate-m629", "Auspicious Starrix", "Creature Beast", "3 G W U",
   ["PT:5/5",
    "K:Mutate:2 G W U",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigDig",
    "SVar:TrigDig:DB$ Dig | DigNum$ 5"]],
  ["sea-dasher-octopus-mutate-m629", "Sea Dasher Octopus", "Creature Octopus", "1 U",
   ["PT:1/1",
    "K:Mutate:U U",
    "K:Flash"]],
  ["nightsquad-commando-mutate-m629", "Nightsquad Commando", "Creature Bird Soldier", "2 W",
   ["PT:2/2",
    "K:Flying",
    "K:Mutate:2 W"]],
  ["sawtusk-demolisher-mutate-m629", "Sawtusk Demolisher", "Creature Beast", "3 G G",
   ["PT:5/5",
    "K:Mutate:3 G G",
    "K:Trample"]],
  ["lore-drakkis-mutate-m629", "Lore Drakkis", "Creature Lizard", "1 U R",
   ["PT:2/2",
    "K:Mutate:1 U R"]],

  // ── Splice.
  ["glacial-ray-splice-m629", "Glacial Ray", "Instant Arcane", "1 R",
   ["A:SP$ DealDamage | Cost$ 1 R | NumDmg$ 2 | ValidTgts$ Any",
    "K:Splice:Arcane:1 R"]],
  ["through-the-breach-splice-m629", "Through the Breach", "Instant Arcane", "2 R R",
   ["A:SP$ ChangeZone | Cost$ 2 R R | Origin$ Hand | Destination$ Battlefield | ChangeType$ Creature.YouOwn",
    "K:Splice:Arcane:3 R R"]],
  ["consuming-vortex-splice-m629", "Consuming Vortex", "Instant Arcane", "1 U",
   ["A:SP$ ChangeZone | Cost$ 1 U | Origin$ Battlefield | Destination$ Hand | TargetType$ Creature | ValidTgts$ Creature",
    "K:Splice:Arcane:1 U"]],
  ["desperate-ritual-splice-m629", "Desperate Ritual", "Instant Arcane", "2 R",
   ["A:SP$ Mana | Cost$ 2 R | Produced$ R | Amount$ 3",
    "K:Splice:Arcane:1 R"]],

  // ── For Mirrodin (auto-attach).
  ["sword-of-the-realms-mirrodin-m629", "Sword of the Realms", "Artifact Equipment", "2",
   ["K:Equip:2",
    "K:For Mirrodin"]],
  ["sword-of-forge-frontier-mirrodin-m629", "Sword Forge Frontier", "Artifact Equipment", "3",
   ["K:Equip:2",
    "K:For Mirrodin"]],
  ["pile-on-mirrodin-m629", "Pile On Mirrodin", "Artifact Equipment", "1",
   ["K:Equip:2",
    "K:For Mirrodin"]],

  // ── Living Weapon — spawn Germ + auto-attach.
  ["batterskull-livingweapon-m629", "Batterskull", "Artifact Equipment", "5",
   ["K:Equip:5",
    "K:Living Weapon"]],
  ["mortarpod-livingweapon-m629", "Mortarpod", "Artifact Equipment", "2",
   ["K:Equip:2",
    "K:Living Weapon",
    "A:AB$ DealDamage | Cost$ Sac<1/CARDNAME> | NumDmg$ 1 | ValidTgts$ Creature,Player"]],
  ["skinwing-livingweapon-m629", "Skinwing", "Artifact Equipment", "3",
   ["K:Equip:3",
    "K:Living Weapon"]],

  // ── Outlast.
  ["mer-ek-nightblade-outlast-m629", "Mer Ek Nightblade", "Creature Orc Warrior", "3 B",
   ["PT:2/2",
    "K:Outlast:1 B",
    "S:Mode$ Continuous | Affected$ Creature.YouCtrl+counters_GE1_P1P1 | AddKeyword$ Deathtouch"]],
  ["ainok-bond-kin-outlast-m629", "Ainok Bond Kin", "Creature Hound Warrior", "1 W",
   ["PT:2/2",
    "K:Outlast:1 W",
    "S:Mode$ Continuous | Affected$ Creature.YouCtrl+counters_GE1_P1P1 | AddKeyword$ First Strike"]],
  ["abzan-falconer-outlast-m629", "Abzan Falconer", "Creature Human Soldier", "2 W",
   ["PT:2/3",
    "K:Outlast:W",
    "S:Mode$ Continuous | Affected$ Creature.YouCtrl+counters_GE1_P1P1 | AddKeyword$ Flying"]],
  ["rakshasa-vizier-outlast-m629", "Rakshasa Vizier", "Creature Cat Demon", "3 B G",
   ["PT:3/4",
    "K:Outlast:B G"]],

  // ── Encore.
  ["faldorn-dread-wolf-encore-m629", "Faldorn Dread Wolf Herald", "Legendary Creature Werewolf", "2 R",
   ["PT:3/3",
    "K:Encore:3 R"]],
  ["bag-of-holding-encore-m629", "Bag of Holding", "Artifact", "1",
   ["A:AB$ Effect | Cost$ T | SpellDescription$ Replace discard.",
    "K:Encore:2"]],
  ["taborax-bonemask-encore-m629", "Taborax Bonemask", "Legendary Creature Vampire Cleric", "2 B",
   ["PT:2/2",
    "K:Flying",
    "K:Encore:5 B"]],
  ["drannith-stinger-encore-m629", "Drannith Stinger", "Creature Human Rogue", "1 R",
   ["PT:2/1",
    "K:Encore:3 R"]],

  // ── Modal DFCs.
  ["agadeems-awakening-mdfc-m629", "Agadeems Awakening", "Sorcery", "X B B",
   ["A:SP$ ChangeZone | Cost$ X B B | Origin$ Graveyard | Destination$ Battlefield | ChangeType$ Creature.YouOwn+cmcLEX | ChangeNum$ X",
    "ALTERNATE",
    "Name:Agadeems Sanctuary",
    "ManaCost:noCost",
    "Types:Land",
    "A:AB$ Mana | Cost$ T | Produced$ B"]],
  ["sea-gate-restoration-mdfc-m629", "Sea Gate Restoration", "Sorcery", "X U U U",
   ["A:SP$ Draw | Cost$ X U U U | NumCards$ X | References$ X",
    "ALTERNATE",
    "Name:Sea Gate Reborn",
    "ManaCost:noCost",
    "Types:Land",
    "A:AB$ Mana | Cost$ T | Produced$ U"]],
  ["valakut-awakening-mdfc-m629", "Valakut Awakening", "Instant", "2 R",
   ["A:SP$ Effect | Cost$ 2 R | SpellDescription$ Hand swap.",
    "ALTERNATE",
    "Name:Valakut Stoneforge",
    "ManaCost:noCost",
    "Types:Land",
    "A:AB$ Mana | Cost$ T | Produced$ R"]],
  ["shatterskull-smashing-mdfc-m629", "Shatterskull Smashing", "Sorcery", "X R R",
   ["A:SP$ DealDamage | Cost$ X R R | NumDmg$ X | References$ X",
    "ALTERNATE",
    "Name:Shatterskull Pass",
    "ManaCost:noCost",
    "Types:Land",
    "A:AB$ Mana | Cost$ T | Produced$ R"]],

  // ── More keyword-flavor cards (broad coverage).
  ["dauntless-bodyguard-m629", "Dauntless Bodyguard", "Creature Human Knight", "W",
   ["PT:2/1",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigName",
    "SVar:TrigName:DB$ ChooseCard | ValidTgts$ Creature.YouCtrl"]],
  ["benalish-marshal-m629", "Benalish Marshal", "Creature Human Knight", "W W W",
   ["PT:3/3",
    "S:Mode$ Continuous | Affected$ Creature.YouCtrl+Other | AddPower$ 1 | AddToughness$ 1"]],
  ["history-knight-m629", "History Knight", "Creature Human Knight", "1 W",
   ["PT:2/2",
    "K:First Strike"]],
  ["gideon-ally-m629", "Gideon Ally", "Legendary Planeswalker Gideon", "1 W W",
   ["Loyalty:3",
    "A:AB$ Pump | Cost$ AddCounter<2/LOYALTY> | Defined$ Self | NumAtt$ +5 | NumDef$ +5 | KW$ Indestructible"]],
  ["deafening-clarion-m629", "Deafening Clarion", "Sorcery", "1 R W",
   ["A:SP$ DamageAll | Cost$ 1 R W | NumDmg$ 3 | ValidCards$ Creature"]],
  ["lyra-dawnbringer-m629", "Lyra Dawnbringer", "Legendary Creature Angel", "3 W W",
   ["PT:5/5",
    "K:Flying",
    "K:First Strike",
    "K:Lifelink",
    "S:Mode$ Continuous | Affected$ Angel.YouCtrl+Other | AddPower$ 1 | AddToughness$ 1"]],
  ["resplendent-angel-m629", "Resplendent Angel", "Creature Angel", "1 W W",
   ["PT:3/3",
    "K:Flying",
    "T:Mode$ LifeGained | ValidPlayer$ You | LifeAmount$ GE5 | Execute$ TrigToken",
    "SVar:TrigToken:DB$ Token | TokenScript$ w_4_4_angel_flying"]],
  ["shalai-voice-m629", "Shalai Voice", "Legendary Creature Angel", "3 W",
   ["PT:3/4",
    "K:Flying",
    "S:Mode$ Continuous | Affected$ Permanent.YouCtrl,You,Planeswalker.YouCtrl | AddKeyword$ Hexproof"]],
  ["ajanis-pridemate-m629", "Ajani Pridemate", "Creature Cat Soldier", "1 W",
   ["PT:2/2",
    "T:Mode$ LifeGained | ValidPlayer$ You | Execute$ TrigPutCounter",
    "SVar:TrigPutCounter:DB$ PutCounter | Defined$ Self | CounterType$ P1P1 | CounterNum$ 1"]],
  ["soul-warden-m629", "Soul Warden", "Creature Human Cleric", "W",
   ["PT:1/1",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Creature | Execute$ TrigGainLife",
    "SVar:TrigGainLife:DB$ GainLife | LifeAmount$ 1"]],

  // ── Blue control suite.
  ["jace-mind-sculptor-m629", "Jace Mind Sculptor", "Legendary Planeswalker Jace", "2 U U",
   ["Loyalty:3",
    "A:AB$ Draw | Cost$ AddCounter<0/LOYALTY> | NumCards$ 3"]],
  ["snapcaster-mage-m629", "Snapcaster Mage", "Creature Human Wizard", "1 U",
   ["PT:2/1",
    "K:Flash",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigGrant",
    "SVar:TrigGrant:DB$ Pump | TargetType$ Card | ValidTgts$ Card.Instant+inZoneGraveyard,Card.Sorcery+inZoneGraveyard | KW$ Flashback"]],
  ["force-of-will-m629", "Force of Will", "Instant", "3 U U",
   ["A:SP$ Counter | Cost$ 3 U U | TargetType$ Spell | ValidTgts$ Card | AltCost$ 1+Exile<1/Card.Blue+Other>"]],
  ["mana-leak-m629", "Mana Leak", "Instant", "1 U",
   ["A:SP$ Counter | Cost$ 1 U | TargetType$ Spell | ValidTgts$ Card | UnlessCost$ 3"]],
  ["remand-m629", "Remand", "Instant", "1 U",
   ["A:SP$ Counter | Cost$ 1 U | TargetType$ Spell | ValidTgts$ Card | DestZone$ Hand | SubAbility$ DBDraw",
    "SVar:DBDraw:DB$ Draw | NumCards$ 1"]],
  ["spell-pierce-m629", "Spell Pierce", "Instant", "U",
   ["A:SP$ Counter | Cost$ U | TargetType$ Spell | ValidTgts$ Card.nonCreature | UnlessCost$ 2"]],
  ["dispel-m629", "Dispel", "Instant", "U",
   ["A:SP$ Counter | Cost$ U | TargetType$ Spell | ValidTgts$ Card.Instant"]],
  ["counterflux-m629", "Counterflux", "Instant", "U U R",
   ["A:SP$ Counter | Cost$ U U R | TargetType$ Spell | ValidTgts$ Card | CantBeCountered$ True"]],
  ["fact-or-fiction-m629", "Fact or Fiction", "Instant", "3 U",
   ["A:SP$ DigUntil | Cost$ 3 U | DigNum$ 5 | DestinationZone$ Hand"]],
  ["thirst-for-knowledge-m629", "Thirst for Knowledge", "Instant", "2 U",
   ["A:SP$ Draw | Cost$ 2 U | NumCards$ 3 | SubAbility$ DBDiscard",
    "SVar:DBDiscard:DB$ Discard | NumCards$ 2 | Mode$ TgtChoose | UnlessCost$ Discard<1/Artifact>"]],

  // ── Black removal/creatures.
  ["liliana-of-the-veil-m629", "Liliana of Veil", "Legendary Planeswalker Liliana", "1 B B",
   ["Loyalty:3",
    "A:AB$ Discard | Cost$ AddCounter<1/LOYALTY> | NumCards$ 1 | Defined$ Each"]],
  ["fatal-push-m629", "Fatal Push", "Instant", "B",
   ["A:SP$ Destroy | Cost$ B | TargetType$ Creature | ValidTgts$ Creature.cmcLE2"]],
  ["thoughtseize-m629", "Thoughtseize", "Sorcery", "B",
   ["A:SP$ Discard | Cost$ B | NumCards$ 1 | Defined$ Player.Opponent | Mode$ Reveal"]],
  ["damnation-m629", "Damnation", "Sorcery", "2 B B",
   ["A:SP$ DestroyAll | Cost$ 2 B B | ValidCards$ Creature | NoRegen$ True"]],
  ["dark-confidant-m629", "Dark Confidant", "Creature Human Wizard", "1 B",
   ["PT:2/1",
    "T:Mode$ Phase | Phase$ Upkeep | ValidPlayer$ You | Execute$ TrigReveal",
    "SVar:TrigReveal:DB$ RevealHand | Defined$ TopOfLibrary | SubAbility$ DBLoseLife",
    "SVar:DBLoseLife:DB$ LoseLife | LifeAmount$ X | References$ X",
    "SVar:X:Reveal$Cmc"]],
  ["dauthi-voidwalker-m629", "Dauthi Voidwalker", "Creature Avatar Phyrexian", "B B",
   ["PT:3/2",
    "K:Shadow"]],
  ["yawgmoth-thran-physician-m629", "Yawgmoth Thran Physician", "Legendary Creature Human", "1 B B",
   ["PT:2/4",
    "A:AB$ DealDamageAll | Cost$ Discard<1/Card> | NumDmg$ 1 | ValidCards$ Creature"]],
  ["hypnotic-specter-m629", "Hypnotic Specter", "Creature Specter", "1 B B",
   ["PT:2/2",
    "K:Flying",
    "T:Mode$ DamageDone | ValidSource$ Card.Self | ValidTarget$ Player | CombatDamage$ True | Execute$ TrigDiscard",
    "SVar:TrigDiscard:DB$ Discard | Defined$ TriggeredTarget | Mode$ Random"]],
  ["nyxborn-rollicker-m629", "Nyxborn Rollicker", "Enchantment Creature Satyr", "R",
   ["PT:1/1",
    "K:Bestow:2 R"]],
  ["nyxborn-shieldmate-m629", "Nyxborn Shieldmate", "Enchantment Creature Human Soldier", "W",
   ["PT:1/1",
    "K:Bestow:2 W"]],

  // ── Red burn / aggro.
  ["chandra-torch-defiance-m629", "Chandra Torch Defiance", "Legendary Planeswalker Chandra", "2 R R",
   ["Loyalty:4",
    "A:AB$ DealDamage | Cost$ AddCounter<1/LOYALTY> | NumDmg$ 4 | ValidTgts$ Creature"]],
  ["goblin-guide-m629", "Goblin Guide", "Creature Goblin Scout", "R",
   ["PT:2/2",
    "K:Haste",
    "T:Mode$ Attacks | ValidCard$ Card.Self | Execute$ TrigReveal",
    "SVar:TrigReveal:DB$ RevealCards | DefinedCards$ TopOfLibrary"]],
  ["lightning-helix-m629", "Lightning Helix", "Instant", "R W",
   ["A:SP$ DealDamage | Cost$ R W | NumDmg$ 3 | ValidTgts$ Any | SubAbility$ DBGain",
    "SVar:DBGain:DB$ GainLife | LifeAmount$ 3"]],
  ["searing-blaze-m629", "Searing Blaze", "Instant", "R R",
   ["A:SP$ DealDamage | Cost$ R R | NumDmg$ 1 | ValidTgts$ Player | SubAbility$ DBDmg",
    "SVar:DBDmg:DB$ DealDamage | NumDmg$ 1 | DefinedTarget$ Creature.OppCtrl"]],
  ["pillar-of-flame-m629", "Pillar of Flame", "Sorcery", "R",
   ["A:SP$ DealDamage | Cost$ R | NumDmg$ 2 | ValidTgts$ Creature,Player"]],
  ["skewer-the-critics-m629", "Skewer the Critics", "Sorcery", "2 R",
   ["A:SP$ DealDamage | Cost$ 2 R | NumDmg$ 3 | ValidTgts$ Any",
    "K:Spectacle:R"]],
  ["bonecrusher-mauler-m629", "Bonecrusher Mauler", "Creature Beast", "1 R R",
   ["PT:4/2",
    "K:Trample"]],
  ["chandra-pyromaster-m629", "Chandra Pyromaster", "Legendary Planeswalker", "2 R R",
   ["Loyalty:4",
    "A:AB$ DealDamage | Cost$ AddCounter<1/LOYALTY> | NumDmg$ 1 | ValidTgts$ Creature"]],
  ["young-pyromancer-m629", "Young Pyromancer", "Creature Human Shaman", "1 R",
   ["PT:2/1",
    "T:Mode$ SpellCast | ValidCard$ Card.Instant,Card.Sorcery | ValidActivatingPlayer$ You | Execute$ TrigToken",
    "SVar:TrigToken:DB$ Token | TokenScript$ r_1_1_elemental"]],
  ["monastery-swiftspear-m629", "Monastery Swiftspear", "Creature Human Monk", "R",
   ["PT:1/2",
    "K:Haste",
    "K:Prowess"]],

  // ── Green ramp/utility.
  ["lotus-cobra-m629", "Lotus Cobra", "Creature Snake", "1 G",
   ["PT:2/1",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Land.YouCtrl | Execute$ TrigMana",
    "SVar:TrigMana:DB$ Mana | Produced$ Any | Amount$ 1"]],
  ["birds-of-paradise-m629", "Birds of Paradise", "Creature Bird", "G",
   ["PT:0/1",
    "K:Flying",
    "A:AB$ Mana | Cost$ T | Produced$ Any | Amount$ 1"]],
  ["sylvan-caryatid-m629", "Sylvan Caryatid", "Creature Plant", "1 G",
   ["PT:0/3",
    "K:Defender",
    "K:Hexproof",
    "A:AB$ Mana | Cost$ T | Produced$ Any | Amount$ 1"]],
  ["primeval-titan-m629", "Primeval Titan", "Creature Giant", "4 G G",
   ["PT:6/6",
    "K:Trample",
    "T:Mode$ Attacks | ValidCard$ Card.Self | Execute$ TrigSearch",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigSearch",
    "SVar:TrigSearch:DB$ ChangeZone | Origin$ Library | Destination$ Battlefield | ChangeType$ Land | ChangeNum$ 2"]],
  ["scute-swarm-m629", "Scute Swarm", "Creature Insect", "1 G",
   ["PT:1/1",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Land.YouCtrl | Execute$ TrigToken",
    "SVar:TrigToken:DB$ Token | TokenScript$ g_1_1_insect"]],
  ["nissa-who-shakes-world-m629", "Nissa Shakes World", "Legendary Planeswalker Nissa", "3 G G",
   ["Loyalty:5",
    "A:AB$ PutCounter | Cost$ AddCounter<1/LOYALTY> | TargetType$ Land | ValidTgts$ Forest"]],
  ["acidic-slime-m629", "Acidic Slime M629", "Creature Ooze", "3 G G",
   ["PT:2/2",
    "K:Deathtouch",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigDestroy",
    "SVar:TrigDestroy:DB$ Destroy | TargetType$ Permanent | ValidTgts$ Land,Artifact,Enchantment"]],
  ["wood-elves-m629", "Wood Elves", "Creature Elf Scout", "2 G",
   ["PT:1/1",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigSearch",
    "SVar:TrigSearch:DB$ ChangeZone | Origin$ Library | Destination$ Battlefield | ChangeType$ Forest | ChangeNum$ 1 | TgtPrompt$ Choose forest"]],
  ["farhaven-elf-m629", "Farhaven Elf", "Creature Elf", "2 G",
   ["PT:1/2",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigSearch",
    "SVar:TrigSearch:DB$ ChangeZone | Origin$ Library | Destination$ Battlefield | ChangeType$ BasicLand | ChangeNum$ 1 | Tapped$ True"]],
  ["sakura-tribe-elder-m629", "Sakura Tribe Elder", "Creature Snake Shaman", "1 G",
   ["PT:1/1",
    "A:AB$ ChangeZone | Cost$ Sac<1/CARDNAME> | Origin$ Library | Destination$ Battlefield | ChangeType$ BasicLand | ChangeNum$ 1 | Tapped$ True"]],

  // ── Lands & utility lands.
  ["fetid-pools-m629", "Fetid Pools", "Land", "noCost",
   ["K:CARDNAME enters tapped.",
    "A:AB$ Mana | Cost$ T | Produced$ U B"]],
  ["hostile-desert-m629", "Hostile Desert", "Land Desert", "noCost",
   ["A:AB$ Mana | Cost$ T | Produced$ C"]],
  ["urzas-saga-land-m629", "Urzas Saga Land", "Enchantment Land Urzas Saga", "noCost",
   ["A:AB$ Mana | Cost$ T | Produced$ C",
    "T:Mode$ CounterAddedOnce | ValidCard$ Card.Self | CounterType$ LORE | NewCounterAmount$ 3 | Execute$ TrigSearch",
    "SVar:TrigSearch:DB$ ChangeZone | Origin$ Library | Destination$ Battlefield | ChangeType$ Artifact.cmcLE1 | ChangeNum$ 1"]],
  ["mishras-workshop-m629", "Mishras Workshop", "Land", "noCost",
   ["A:AB$ Mana | Cost$ T | Produced$ C | Amount$ 3 | RestrictValid$ Artifact"]],
  ["bazaar-of-baghdad-m629", "Bazaar Baghdad", "Land", "noCost",
   ["A:AB$ Effect | Cost$ T | SpellDescription$ Loot."]],
  ["wasteland-m629", "Wasteland", "Land", "noCost",
   ["A:AB$ Mana | Cost$ T | Produced$ C",
    "A:AB$ Destroy | Cost$ T Sac<1/CARDNAME> | TargetType$ Land | ValidTgts$ Land.nonBasic"]],
  ["strip-mine-m629", "Strip Mine M629", "Land", "noCost",
   ["A:AB$ Mana | Cost$ T | Produced$ C",
    "A:AB$ Destroy | Cost$ T Sac<1/CARDNAME> | TargetType$ Land | ValidTgts$ Land"]],
  ["wooded-foothills-m629", "Wooded Foothills", "Land", "noCost",
   ["A:AB$ ChangeZone | Cost$ T LoseLife<1> Sac<1/CARDNAME> | Origin$ Library | Destination$ Battlefield | ChangeType$ Mountain,Forest"]],
  ["polluted-delta-m629", "Polluted Delta", "Land", "noCost",
   ["A:AB$ ChangeZone | Cost$ T LoseLife<1> Sac<1/CARDNAME> | Origin$ Library | Destination$ Battlefield | ChangeType$ Island,Swamp"]],
  ["scalding-tarn-m629", "Scalding Tarn", "Land", "noCost",
   ["A:AB$ ChangeZone | Cost$ T LoseLife<1> Sac<1/CARDNAME> | Origin$ Library | Destination$ Battlefield | ChangeType$ Mountain,Island"]],

  // ── Artifacts — equipment, mana rocks, mass.
  ["mox-opal-m629", "Mox Opal", "Legendary Artifact", "0",
   ["A:AB$ Mana | Cost$ T | Produced$ Any | RestrictValid$ Metalcraft"]],
  ["mox-amber-m629", "Mox Amber", "Legendary Artifact", "0",
   ["A:AB$ Mana | Cost$ T | Produced$ Any | RestrictValid$ Legendary"]],
  ["mox-tantalite-m629", "Mox Tantalite", "Artifact", "noCost",
   ["A:AB$ Mana | Cost$ T | Produced$ Any | Amount$ 1",
    "K:Suspend:3:0"]],
  ["chrome-mox-m629", "Chrome Mox", "Artifact", "0",
   ["T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigImprint",
    "SVar:TrigImprint:DB$ ImprintCards | DefinedCards$ HandRevealed"]],
  ["lotus-petal-m629", "Lotus Petal", "Artifact", "0",
   ["A:AB$ Mana | Cost$ T Sac<1/CARDNAME> | Produced$ Any | Amount$ 1"]],
  ["jeweled-lotus-m629", "Jeweled Lotus", "Legendary Artifact", "0",
   ["A:AB$ Mana | Cost$ T Sac<1/CARDNAME> | Produced$ Any | Amount$ 3 | RestrictValid$ Commander"]],
  ["umezawas-jitte-m629", "Umezawas Jitte", "Legendary Artifact Equipment", "2",
   ["K:Equip:2",
    "T:Mode$ DamageDone | ValidSource$ Creature.EquippedBy | CombatDamage$ True | Execute$ TrigCntr",
    "SVar:TrigCntr:DB$ PutCounter | Defined$ Self | CounterType$ CHARGE | CounterNum$ 2"]],
  ["sword-of-fire-and-ice-m629", "Sword Fire Ice M629", "Artifact Equipment", "3",
   ["K:Equip:2",
    "T:Mode$ DamageDone | ValidSource$ Creature.EquippedBy | CombatDamage$ True | Execute$ TrigDmgDraw",
    "SVar:TrigDmgDraw:DB$ DealDamage | NumDmg$ 2 | DefinedTarget$ Any | SubAbility$ DBDraw",
    "SVar:DBDraw:DB$ Draw | NumCards$ 1"]],
  ["sword-of-light-and-shadow-m629", "Sword Light Shadow M629", "Artifact Equipment", "3",
   ["K:Equip:2",
    "T:Mode$ DamageDone | ValidSource$ Creature.EquippedBy | CombatDamage$ True | Execute$ TrigGainReturn",
    "SVar:TrigGainReturn:DB$ GainLife | LifeAmount$ 3 | SubAbility$ DBReturn",
    "SVar:DBReturn:DB$ ChangeZone | Origin$ Graveyard | Destination$ Hand | TargetType$ Card | ValidTgts$ Creature.YouCtrl"]],
  ["mind-stone-m629", "Mind Stone", "Artifact", "2",
   ["A:AB$ Mana | Cost$ T | Produced$ C | Amount$ 1",
    "A:AB$ Draw | Cost$ 1 T Sac<1/CARDNAME> | NumCards$ 1"]],
  ["everflowing-chalice-m629", "Everflowing Chalice", "Artifact", "X",
   ["K:Multikicker:1",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigCntr",
    "SVar:TrigCntr:DB$ PutCounter | Defined$ Self | CounterType$ CHARGE | CounterNum$ X | References$ X",
    "SVar:X:Count$Multikicker",
    "A:AB$ Mana | Cost$ T | Produced$ C | Amount$ X | References$ X"]],
  ["thran-dynamo-m629", "Thran Dynamo", "Artifact", "4",
   ["A:AB$ Mana | Cost$ T | Produced$ C | Amount$ 3"]],
  ["worn-powerstone-m629", "Worn Powerstone", "Artifact", "3",
   ["T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigTap",
    "SVar:TrigTap:DB$ Tap | Defined$ Self",
    "A:AB$ Mana | Cost$ T | Produced$ C | Amount$ 2"]],

  // ── Enchantments — auras + statics.
  ["rancor-m629", "Rancor M629", "Enchantment Aura", "G",
   ["K:Enchant Creature",
    "S:Mode$ Continuous | Affected$ Creature.AttachedBy | AddPower$ 2 | AddKeyword$ Trample",
    "T:Mode$ ChangesZone | Origin$ Battlefield | Destination$ Graveyard | ValidCard$ Card.Self | Execute$ TrigReturn",
    "SVar:TrigReturn:DB$ ChangeZone | Origin$ Graveyard | Destination$ Hand"]],
  ["pacifism-m629", "Pacifism", "Enchantment Aura", "1 W",
   ["K:Enchant Creature",
    "S:Mode$ Continuous | Affected$ Creature.AttachedBy | CantAttack$ True | CantBlock$ True"]],
  ["oblivion-ring-m629", "Oblivion Ring", "Enchantment", "2 W",
   ["T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigExile",
    "T:Mode$ ChangesZone | Origin$ Battlefield | Destination$ Any | ValidCard$ Card.Self | Execute$ TrigReturn",
    "SVar:TrigExile:DB$ ChangeZone | Origin$ Battlefield | Destination$ Exile | TargetType$ Permanent | ValidTgts$ Permanent.OppCtrl+nonLand | RememberChanged$ True",
    "SVar:TrigReturn:DB$ ChangeZone | Defined$ Remembered | Origin$ Exile | Destination$ Battlefield"]],
  ["banisher-priest-m629", "Banisher Priest", "Creature Human Cleric", "1 W W",
   ["PT:2/2",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigExile",
    "SVar:TrigExile:DB$ ChangeZone | Origin$ Battlefield | Destination$ Exile | TargetType$ Creature | ValidTgts$ Creature.OppCtrl"]],
  ["doom-foretold-m629", "Doom Foretold", "Enchantment", "2 W B",
   ["T:Mode$ Phase | Phase$ Upkeep | ValidPlayer$ You | Execute$ TrigSac",
    "SVar:TrigSac:DB$ Sacrifice | SacValid$ Permanent.nonLand"]],
  ["bitterblossom-m629", "Bitterblossom", "Tribal Enchantment Faerie", "1 B",
   ["T:Mode$ Phase | Phase$ Upkeep | ValidPlayer$ You | Execute$ TrigToken",
    "SVar:TrigToken:DB$ Token | TokenScript$ b_1_1_faerie_rogue_flying"]],
  ["sylvan-library-m629", "Sylvan Library", "Enchantment", "1 G",
   ["T:Mode$ Phase | Phase$ Draw | ValidPlayer$ You | Execute$ TrigDraw",
    "SVar:TrigDraw:DB$ Draw | NumCards$ 2"]],
  ["necropotence-m629", "Necropotence", "Enchantment", "B B B",
   ["A:AB$ Effect | Cost$ PayLife<1> | SpellDescription$ Skip draw",
    "T:Mode$ Phase | Phase$ Discard | ValidPlayer$ You | Execute$ TrigSkip",
    "SVar:TrigSkip:DB$ Skip"]],
  ["land-tax-m629", "Land Tax", "Enchantment", "W",
   ["T:Mode$ Phase | Phase$ Upkeep | ValidPlayer$ You | Execute$ TrigSearch",
    "SVar:TrigSearch:DB$ ChangeZone | Origin$ Library | Destination$ Hand | ChangeType$ BasicLand | ChangeNum$ 3"]],
  ["enchanted-evening-m629", "Enchanted Evening", "Enchantment", "4 W",
   ["S:Mode$ Continuous | Affected$ Permanent | AddType$ Enchantment"]],

  // ── Creature combat helpers.
  ["serra-angel-m629", "Serra Angel M629", "Creature Angel", "3 W W",
   ["PT:4/4",
    "K:Flying",
    "K:Vigilance"]],
  ["baneslayer-angel-m629", "Baneslayer Angel", "Creature Angel", "3 W W",
   ["PT:5/5",
    "K:Flying",
    "K:First Strike",
    "K:Lifelink",
    "K:Protection from Demons",
    "K:Protection from Dragons"]],
  ["restoration-angel-m629", "Restoration Angel", "Creature Angel", "3 W",
   ["PT:3/4",
    "K:Flash",
    "K:Flying",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigFlicker",
    "SVar:TrigFlicker:DB$ ChangeZone | Origin$ Battlefield | Destination$ Exile | TargetType$ Creature | ValidTgts$ Creature.YouCtrl+nonAngel+Other | SubAbility$ DBReturn",
    "SVar:DBReturn:DB$ ChangeZone | Origin$ Exile | Destination$ Battlefield | Defined$ TargetedCard"]],
  ["thragtusk-m629", "Thragtusk", "Creature Beast", "4 G",
   ["PT:5/3",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigGainLife",
    "T:Mode$ ChangesZone | Origin$ Battlefield | Destination$ Any | ValidCard$ Card.Self | Execute$ TrigToken",
    "SVar:TrigGainLife:DB$ GainLife | LifeAmount$ 5",
    "SVar:TrigToken:DB$ Token | TokenScript$ g_3_3_beast"]],
  ["reveillark-m629", "Reveillark", "Creature Elemental", "4 W",
   ["PT:4/3",
    "K:Flying",
    "T:Mode$ ChangesZone | Origin$ Battlefield | Destination$ Any | ValidCard$ Card.Self | Execute$ TrigReturn",
    "SVar:TrigReturn:DB$ ChangeZone | Origin$ Graveyard | Destination$ Battlefield | TargetType$ Creature | ValidTgts$ Creature.powerLE2"]],
  ["siege-rhino-m629", "Siege Rhino", "Creature Rhino Warrior", "1 W B G",
   ["PT:4/5",
    "K:Trample",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigDrain",
    "SVar:TrigDrain:DB$ LoseLife | LifeAmount$ 3 | Defined$ Player.Opponent | SubAbility$ DBGain",
    "SVar:DBGain:DB$ GainLife | LifeAmount$ 3"]],
  ["birthing-pod-m629", "Birthing Pod", "Artifact", "3 G/P",
   ["A:AB$ ChangeZone | Cost$ 1 GP T Sac<1/Creature.YouCtrl/creature> | Origin$ Library | Destination$ Battlefield | ChangeType$ Creature.cmcEQX | References$ X",
    "SVar:X:Sacrificed$CardManaCost.Plus.1"]],
  ["aetherling-m629", "Aetherling M629", "Creature Shapeshifter", "4 U U",
   ["PT:4/5",
    "A:AB$ ChangeZone | Cost$ U | Origin$ Battlefield | Destination$ Exile | Defined$ Self | SubAbility$ DBReturn",
    "SVar:DBReturn:DB$ ChangeZone | Origin$ Exile | Destination$ Battlefield | Defined$ Self"]],
  ["delver-of-secrets-m629", "Delver Secrets", "Creature Human Wizard", "U",
   ["PT:1/1",
    "T:Mode$ Phase | Phase$ Upkeep | ValidPlayer$ You | Execute$ TrigReveal",
    "SVar:TrigReveal:DB$ RevealCards | DefinedCards$ TopOfLibrary"]],
  ["tarmogoyf-m629", "Tarmogoyf M629", "Creature Lhurgoyf", "1 G",
   ["PT:*/*",
    "S:Mode$ Continuous | Affected$ Card.Self | SetPower$ X | SetToughness$ Y | References$ X,Y",
    "SVar:X:Count$Valid Card.inZoneGraveyard+Type",
    "SVar:Y:Count$Valid Card.inZoneGraveyard+Type+Plus.1"]],

  // ── Tribal lords.
  ["lord-of-atlantis-m629", "Lord of Atlantis", "Creature Merfolk", "U U",
   ["PT:2/2",
    "S:Mode$ Continuous | Affected$ Merfolk.YouCtrl+Other | AddPower$ 1 | AddToughness$ 1 | AddKeyword$ Islandwalk"]],
  ["goblin-king-m629", "Goblin King", "Creature Goblin", "1 R R",
   ["PT:2/2",
    "S:Mode$ Continuous | Affected$ Goblin.YouCtrl+Other | AddPower$ 1 | AddToughness$ 1 | AddKeyword$ Mountainwalk"]],
  ["lord-of-the-undead-m629", "Lord Undead", "Creature Zombie", "1 B B",
   ["PT:2/2",
    "S:Mode$ Continuous | Affected$ Zombie.YouCtrl+Other | AddPower$ 1 | AddToughness$ 1"]],
  ["elvish-archdruid-m629", "Elvish Archdruid", "Creature Elf Druid", "1 G G",
   ["PT:2/2",
    "S:Mode$ Continuous | Affected$ Elf.YouCtrl+Other | AddPower$ 1 | AddToughness$ 1",
    "A:AB$ Mana | Cost$ T | Produced$ G | Amount$ X | References$ X",
    "SVar:X:Count$Valid Elf.YouCtrl"]],
  ["adaptive-automaton-m629", "Adaptive Automaton", "Artifact Creature Construct", "3",
   ["PT:2/2",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigChooseType",
    "SVar:TrigChooseType:DB$ ChooseType"]],
  ["metallic-mimic-m629", "Metallic Mimic", "Artifact Creature Shapeshifter", "2",
   ["PT:2/1",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigChoose",
    "SVar:TrigChoose:DB$ ChooseType",
    "R:Event$ Moved | Destination$ Battlefield | ValidCard$ Creature.YouCtrl+ChosenType | ReplaceWith$ DBETB",
    "SVar:DBETB:DB$ PutCounter | Defined$ ReplacedCard | CounterType$ P1P1 | CounterNum$ 1"]],
  ["urza-lord-high-artificer-m629", "Urza Lord Artificer", "Legendary Creature Human Artificer", "2 U U",
   ["PT:1/4",
    "S:Mode$ Continuous | Affected$ Artifact.YouCtrl | AddAbility$ ABMana",
    "SVar:ABMana:AB$ Mana | Cost$ T | Produced$ U"]],
  ["thalia-guardian-m629", "Thalia Guardian", "Legendary Creature Human Soldier", "1 W",
   ["PT:2/1",
    "K:First Strike",
    "S:Mode$ Continuous | Affected$ Card.nonCreature+inZoneStack | AddCost$ 1"]],
  ["leovold-emissary-m629", "Leovold Emissary", "Legendary Creature Elf Advisor", "B G U",
   ["PT:3/3",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigDraw",
    "SVar:TrigDraw:DB$ Effect"]],
  ["mirran-crusader-m629", "Mirran Crusader", "Creature Human Knight", "W W",
   ["PT:2/2",
    "K:Double Strike",
    "K:Protection from Black",
    "K:Protection from Green"]],

  // ── Misc engine showcases.
  ["enter-the-infinite-m629", "Enter Infinite", "Sorcery", "8 U U U",
   ["A:SP$ Effect | Cost$ 8 U U U | SpellDescription$ Draw all."]],
  ["griselbrand-m629", "Griselbrand", "Legendary Creature Demon", "4 B B B B",
   ["PT:7/7",
    "K:Flying",
    "K:Lifelink",
    "A:AB$ Draw | Cost$ PayLife<7> | NumCards$ 7"]],
  ["sneak-attack-m629", "Sneak Attack", "Enchantment", "2 R",
   ["A:AB$ ChangeZone | Cost$ R | Origin$ Hand | Destination$ Battlefield | ChangeType$ Creature.YouOwn | KeywordsGranted$ Haste"]],
  ["show-and-tell-m629", "Show and Tell", "Sorcery", "2 U",
   ["A:SP$ ChangeZone | Cost$ 2 U | Origin$ Hand | Destination$ Battlefield | ChangeType$ Artifact,Creature,Enchantment,Land | EachOwner$ True"]],
  ["entomb-m629", "Entomb", "Instant", "B",
   ["A:SP$ ChangeZone | Cost$ B | Origin$ Library | Destination$ Graveyard | ChangeType$ Card | ChangeNum$ 1"]],
  ["reanimate-m629", "Reanimate", "Sorcery", "B",
   ["A:SP$ ChangeZone | Cost$ B | Origin$ Graveyard | Destination$ Battlefield | TargetType$ Card | ValidTgts$ Creature"]],
  ["vampiric-tutor-m629", "Vampiric Tutor", "Instant", "B",
   ["A:SP$ ChangeZone | Cost$ B | Origin$ Library | Destination$ TopOfLibrary | ChangeNum$ 1 | ChangeType$ Card | SubAbility$ DBLoseLife",
    "SVar:DBLoseLife:DB$ LoseLife | LifeAmount$ 2"]],
  ["demonic-tutor-m629", "Demonic Tutor", "Sorcery", "1 B",
   ["A:SP$ ChangeZone | Cost$ 1 B | Origin$ Library | Destination$ Hand | ChangeType$ Card | ChangeNum$ 1"]],
  ["mystical-tutor-m629", "Mystical Tutor", "Instant", "U",
   ["A:SP$ ChangeZone | Cost$ U | Origin$ Library | Destination$ TopOfLibrary | ChangeType$ Instant,Sorcery"]],
  ["worldly-tutor-m629", "Worldly Tutor", "Instant", "G",
   ["A:SP$ ChangeZone | Cost$ G | Origin$ Library | Destination$ TopOfLibrary | ChangeType$ Creature"]],

  // ── More Legendary creatures.
  ["urza-academy-headmaster-m629", "Urza Academy Headmaster", "Legendary Creature Human", "2 U U",
   ["PT:2/4"]],
  ["atraxa-grand-unifier-m629", "Atraxa Grand Unifier", "Legendary Creature Phyrexian", "3 W U B G",
   ["PT:7/7",
    "K:Flying",
    "K:Vigilance",
    "K:Deathtouch",
    "K:Lifelink",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigDig",
    "SVar:TrigDig:DB$ Dig | DigNum$ 10"]],
  ["sheoldred-apocalypse-m629", "Sheoldred Apocalypse", "Legendary Creature Phyrexian Praetor", "2 B B",
   ["PT:4/5",
    "K:Deathtouch",
    "T:Mode$ Drawn | ValidCard$ Card | ValidPlayer$ You | Execute$ TrigGain",
    "SVar:TrigGain:DB$ GainLife | LifeAmount$ 2"]],
  ["urabrask-heretic-m629", "Urabrask Heretic", "Legendary Creature Phyrexian Praetor", "2 R R",
   ["PT:4/4",
    "K:First Strike",
    "K:Haste"]],
  ["jin-gitaxias-m629", "Jin Gitaxias", "Legendary Creature Phyrexian Praetor", "5 U U",
   ["PT:5/4",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigDraw",
    "SVar:TrigDraw:DB$ Draw | NumCards$ 7"]],
  ["vorinclex-monstrous-raider-m629", "Vorinclex Monstrous Raider", "Legendary Creature Phyrexian Praetor", "4 G G",
   ["PT:6/6",
    "K:Trample",
    "K:Haste"]],
  ["elesh-norn-grand-cenobite-m629", "Elesh Norn Grand Cenobite", "Legendary Creature Phyrexian Praetor", "5 W W",
   ["PT:4/7",
    "K:Vigilance",
    "S:Mode$ Continuous | Affected$ Creature.YouCtrl | AddPower$ 2 | AddToughness$ 2",
    "S:Mode$ Continuous | Affected$ Creature.OppCtrl | AddPower$ -2 | AddToughness$ -2"]],
  ["kozilek-butcher-truth-m629", "Kozilek Butcher", "Legendary Creature Eldrazi", "10",
   ["PT:12/12",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigDraw",
    "K:Annihilator:4",
    "SVar:TrigDraw:DB$ Draw | NumCards$ 4"]],
  ["emrakul-aeons-torn-m629", "Emrakul Aeons Torn", "Legendary Creature Eldrazi", "15",
   ["PT:15/15",
    "K:Flying",
    "K:Trample",
    "K:Protection from colored spells",
    "K:Annihilator:6"]],
  ["ulamog-ceaseless-hunger-m629", "Ulamog Ceaseless Hunger", "Legendary Creature Eldrazi", "10",
   ["PT:10/10",
    "K:Indestructible",
    "K:Annihilator:1"]],

  // ── Modal targeted effects.
  ["cryptic-command-m629", "Cryptic Command", "Instant", "1 U U U",
   ["A:SP$ Charm | Cost$ 1 U U U | Choices$ Counter,Bounce,Tap,Draw | CharmNum$ 2"]],
  ["mystic-confluence-m629", "Mystic Confluence", "Instant", "3 U U",
   ["A:SP$ Charm | Cost$ 3 U U | Choices$ Counter,Bounce,Draw | CharmNum$ 3 | RepeatChoose$ True"]],
  ["abrupt-decay-m629", "Abrupt Decay M629", "Instant", "B G",
   ["A:SP$ Destroy | Cost$ B G | TargetType$ Permanent | ValidTgts$ Permanent.cmcLE3+nonLand"]],
  ["assassins-trophy-m629", "Assassins Trophy", "Instant", "B G",
   ["A:SP$ Destroy | Cost$ B G | TargetType$ Permanent | ValidTgts$ Permanent.OppCtrl+nonLand"]],
  ["maelstrom-pulse-m629", "Maelstrom Pulse", "Sorcery", "1 B G",
   ["A:SP$ DestroyAll | Cost$ 1 B G | ValidCards$ Permanent.NamedTarget+nonLand"]],
  ["putrefy-m629", "Putrefy", "Instant", "1 B G",
   ["A:SP$ Destroy | Cost$ 1 B G | TargetType$ Permanent | ValidTgts$ Creature,Artifact"]],
  ["doom-blade-m629", "Doom Blade M629", "Instant", "1 B",
   ["A:SP$ Destroy | Cost$ 1 B | TargetType$ Creature | ValidTgts$ Creature.nonBlack"]],
  ["go-for-the-throat-m629", "Go for Throat M629", "Instant", "1 B",
   ["A:SP$ Destroy | Cost$ 1 B | TargetType$ Creature | ValidTgts$ Creature.nonArtifact"]],
  ["ultimate-price-m629", "Ultimate Price", "Instant", "1 B",
   ["A:SP$ Destroy | Cost$ 1 B | TargetType$ Creature | ValidTgts$ Creature.MonoColor"]],
  ["heros-downfall-m629", "Heros Downfall", "Instant", "1 B B",
   ["A:SP$ Destroy | Cost$ 1 B B | TargetType$ Creature,Planeswalker | ValidTgts$ Creature,Planeswalker"]],

  // ── Token producers.
  ["lingering-souls-m629", "Lingering Souls", "Sorcery", "2 W",
   ["A:SP$ Token | Cost$ 2 W | TokenScript$ w_1_1_spirit_flying | TokenAmount$ 2",
    "K:Flashback:1 B"]],
  ["spectral-procession-m629", "Spectral Procession", "Sorcery", "2 W W W",
   ["A:SP$ Token | Cost$ 2 W W W | TokenScript$ w_1_1_spirit_flying | TokenAmount$ 3"]],
  ["raise-the-alarm-m629", "Raise the Alarm", "Instant", "1 W",
   ["A:SP$ Token | Cost$ 1 W | TokenScript$ w_1_1_soldier | TokenAmount$ 2"]],
  ["midnight-haunting-m629", "Midnight Haunting", "Instant", "2 W",
   ["A:SP$ Token | Cost$ 2 W | TokenScript$ w_1_1_spirit_flying | TokenAmount$ 2"]],
  ["bitterblossom-token-m629", "Bitterblossom Token", "Tribal Enchantment Faerie", "1 B",
   ["T:Mode$ Phase | Phase$ Upkeep | ValidPlayer$ You | Execute$ TrigToken",
    "SVar:TrigToken:DB$ Token | TokenScript$ b_1_1_faerie_rogue_flying"]],
  ["bitterblossom-extra-m629", "Bitterblossom Extra", "Tribal Enchantment Faerie", "1 B",
   ["T:Mode$ Phase | Phase$ Upkeep | ValidPlayer$ You | Execute$ TrigToken | SubAbility$ DBLoseLife",
    "SVar:TrigToken:DB$ Token | TokenScript$ b_1_1_faerie_rogue_flying",
    "SVar:DBLoseLife:DB$ LoseLife | LifeAmount$ 1"]],
  ["secure-the-wastes-m629", "Secure the Wastes", "Instant", "X W",
   ["A:SP$ Token | Cost$ X W | TokenScript$ w_1_1_warrior | TokenAmount$ X | References$ X",
    "SVar:X:Count$xPaid"]],
  ["white-sun-zenith-m629", "White Suns Zenith", "Instant", "X W W W",
   ["A:SP$ Token | Cost$ X W W W | TokenScript$ w_2_2_cat | TokenAmount$ X | References$ X",
    "SVar:X:Count$xPaid"]],
  ["assemble-the-legion-m629", "Assemble the Legion", "Enchantment", "3 R W",
   ["T:Mode$ Phase | Phase$ Upkeep | ValidPlayer$ You | Execute$ TrigToken",
    "SVar:TrigToken:DB$ Token | TokenScript$ rw_1_1_soldier_haste"]],
  ["army-of-the-damned-m629", "Army of the Damned", "Sorcery", "5 B B B",
   ["A:SP$ Token | Cost$ 5 B B B | TokenScript$ b_2_2_zombie | TokenAmount$ 13",
    "K:Flashback:7 B B B"]],

  // ── Counterspells variants.
  ["mana-drain-m629", "Mana Drain M629", "Instant", "U U",
   ["A:SP$ Counter | Cost$ U U | TargetType$ Spell | ValidTgts$ Card | SubAbility$ DBManaPay",
    "SVar:DBManaPay:DB$ Effect | SpellDescription$ Mana refund."]],
  ["arcane-denial-m629", "Arcane Denial", "Instant", "1 U",
   ["A:SP$ Counter | Cost$ 1 U | TargetType$ Spell | ValidTgts$ Card | SubAbility$ DBDraw",
    "SVar:DBDraw:DB$ Draw | NumCards$ 1 | Defined$ Player.AffectedTarget"]],
  ["essence-scatter-m629", "Essence Scatter", "Instant", "1 U",
   ["A:SP$ Counter | Cost$ 1 U | TargetType$ Spell | ValidTgts$ Card.Creature"]],
  ["broken-concentration-m629", "Broken Concentration", "Instant", "2 U U",
   ["A:SP$ Counter | Cost$ 2 U U | TargetType$ Spell | ValidTgts$ Card | UnlessCost$ Discard<2/Card>"]],
  ["overwhelming-denial-m629", "Overwhelming Denial", "Instant", "U U",
   ["A:SP$ Counter | Cost$ U U | TargetType$ Spell | ValidTgts$ Card.Instant,Card.Sorcery"]],
  ["miscalculation-m629", "Miscalculation", "Instant", "1 U",
   ["A:SP$ Counter | Cost$ 1 U | TargetType$ Spell | ValidTgts$ Card | UnlessCost$ 2"]],
  ["dissipate-m629", "Dissipate", "Instant", "1 U U",
   ["A:SP$ Counter | Cost$ 1 U U | TargetType$ Spell | ValidTgts$ Card | DestZone$ Exile"]],
  ["last-word-m629", "Last Word", "Instant", "2 U U",
   ["A:SP$ Counter | Cost$ 2 U U | TargetType$ Spell | ValidTgts$ Card | CantBeCountered$ True"]],
  ["render-silent-m629", "Render Silent", "Instant", "W U U",
   ["A:SP$ Counter | Cost$ W U U | TargetType$ Spell | ValidTgts$ Card"]],
  ["confound-m629", "Confound", "Instant", "1 U",
   ["A:SP$ Counter | Cost$ 1 U | TargetType$ Spell | ValidTgts$ Card | TargetsAttacking$ True | SubAbility$ DBDraw",
    "SVar:DBDraw:DB$ Draw | NumCards$ 1"]],

  // ── Aggro/midrange creatures.
  ["death-shadow-m629", "Death Shadow", "Creature Avatar", "B",
   ["PT:*/*",
    "S:Mode$ Continuous | Affected$ Card.Self | SetPower$ X | SetToughness$ X | References$ X",
    "SVar:X:Count$You$LifeMax13Minus"]],
  ["gurmag-angler-m629", "Gurmag Angler", "Creature Zombie Fish", "7 B",
   ["PT:5/5",
    "K:Delve"]],
  ["tasigur-golden-fang-m629", "Tasigur Golden Fang", "Legendary Creature Human Shaman", "5 B",
   ["PT:4/5",
    "K:Delve"]],
  ["become-immense-m629", "Become Immense", "Instant", "5 G",
   ["A:SP$ Pump | Cost$ 5 G | TargetType$ Creature | ValidTgts$ Creature | NumAtt$ +6 | NumDef$ +6 | KW$ Trample",
    "K:Delve"]],
  ["treasure-cruise-m629", "Treasure Cruise", "Sorcery", "7 U",
   ["A:SP$ Draw | Cost$ 7 U | NumCards$ 3",
    "K:Delve"]],
  ["dig-through-time-m629", "Dig Through Time", "Instant", "6 U U",
   ["A:SP$ Dig | Cost$ 6 U U | DigNum$ 7 | ChangeNum$ 2 | DestinationZone$ Hand",
    "K:Delve"]],
  ["temur-battle-rage-m629", "Temur Battle Rage", "Instant", "1 R",
   ["A:SP$ Pump | Cost$ 1 R | TargetType$ Creature | ValidTgts$ Creature | KW$ Trample & Double Strike"]],
  ["embercleave-m629", "Embercleave", "Legendary Artifact Equipment", "4 R R",
   ["K:Equip:3",
    "K:Flash",
    "S:Mode$ Continuous | Affected$ Creature.AttachedBy | AddKeyword$ Double Strike & Trample",
    "K:CostReduction:Affinity:Creature"]],
  ["winota-joiner-of-forces-m629", "Winota Joiner Forces", "Legendary Creature Human Soldier", "2 R W",
   ["PT:4/4",
    "K:Vigilance",
    "T:Mode$ Attacks | ValidCard$ Creature.YouCtrl+nonHuman | Execute$ TrigSearch",
    "SVar:TrigSearch:DB$ Dig | DigNum$ 6 | ChangeNum$ 1 | ChangeType$ Human"]],
  ["edgewall-innkeeper-m629", "Edgewall Innkeeper", "Creature Human Peasant", "G",
   ["PT:1/1",
    "T:Mode$ SpellCast | ValidCard$ Card.Adventure | ValidActivatingPlayer$ You | Execute$ TrigDraw",
    "SVar:TrigDraw:DB$ Draw | NumCards$ 1"]],

  // ── Combo enablers.
  ["splinter-twin-m629", "Splinter Twin", "Enchantment Aura", "2 R R",
   ["K:Enchant Creature",
    "S:Mode$ Continuous | Affected$ Creature.AttachedBy | AddAbility$ ABCopy",
    "SVar:ABCopy:AB$ CopyPermanent | Cost$ T | Defined$ Self.AttachedTo | KeywordsGranted$ Haste | NumCopies$ 1 | AtEOT$ Exile"]],
  ["kiki-jiki-mirror-breaker-m629", "Kiki Jiki Mirror Breaker", "Legendary Creature Goblin Shaman", "2 R R R",
   ["PT:2/2",
    "K:Haste",
    "A:AB$ CopyPermanent | Cost$ T | TargetType$ Creature | ValidTgts$ Creature.YouCtrl+nonLegendary | KeywordsGranted$ Haste | NumCopies$ 1 | AtEOT$ Exile"]],
  ["pestermite-m629", "Pestermite", "Creature Faerie Rogue", "2 U",
   ["PT:2/1",
    "K:Flash",
    "K:Flying",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigUntap",
    "SVar:TrigUntap:DB$ Tap | TargetType$ Permanent | ValidTgts$ Permanent"]],
  ["deceiver-exarch-m629", "Deceiver Exarch", "Creature Cleric", "2 U",
   ["PT:1/4",
    "K:Flash",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigUntap",
    "SVar:TrigUntap:DB$ Untap | TargetType$ Permanent | ValidTgts$ Permanent"]],
  ["village-bell-ringer-m629", "Village Bell Ringer", "Creature Human Scout", "2 W",
   ["PT:1/3",
    "K:Flash",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigUntap",
    "SVar:TrigUntap:DB$ UntapAll | ValidCards$ Creature.YouCtrl"]],
  ["dramatic-reversal-m629", "Dramatic Reversal", "Instant", "1 U",
   ["A:SP$ UntapAll | Cost$ 1 U | ValidCards$ Permanent.YouCtrl+nonLand"]],
  ["paradox-engine-m629", "Paradox Engine", "Legendary Artifact", "5",
   ["T:Mode$ SpellCast | ValidCard$ Card | ValidActivatingPlayer$ You | Execute$ TrigUntap",
    "SVar:TrigUntap:DB$ UntapAll | ValidCards$ Permanent.YouCtrl+nonLand"]],
  ["isochron-scepter-m629", "Isochron Scepter", "Artifact", "2",
   ["T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigImprint",
    "SVar:TrigImprint:DB$ ImprintCards | DefinedCards$ HandRevealed",
    "A:AB$ Effect | Cost$ 2 T | Defined$ Imprinted | SpellDescription$ Cast copy."]],
  ["dual-caster-mage-m629", "Dual Caster Mage", "Creature Human Wizard", "1 R R",
   ["PT:2/2",
    "K:Flash",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigCopy",
    "SVar:TrigCopy:DB$ CopySpell | TargetType$ Spell | ValidTgts$ Card.Instant,Card.Sorcery"]],
  ["thousand-year-storm-m629", "Thousand Year Storm", "Enchantment", "4 U R",
   ["T:Mode$ SpellCast | ValidCard$ Card.Instant,Card.Sorcery | ValidActivatingPlayer$ You | Execute$ TrigCopy",
    "SVar:TrigCopy:DB$ CopySpell | TargetType$ Spell"]],

  // ── Wraths.
  ["wrath-of-god-m629", "Wrath of God M629", "Sorcery", "2 W W",
   ["A:SP$ DestroyAll | Cost$ 2 W W | ValidCards$ Creature | NoRegen$ True"]],
  ["day-of-judgment-m629", "Day of Judgment", "Sorcery", "2 W W",
   ["A:SP$ DestroyAll | Cost$ 2 W W | ValidCards$ Creature"]],
  ["supreme-verdict-m629", "Supreme Verdict", "Sorcery", "1 W W U",
   ["A:SP$ DestroyAll | Cost$ 1 W W U | ValidCards$ Creature | CantBeCountered$ True"]],
  ["terminus-m629", "Terminus", "Sorcery", "4 W W",
   ["A:SP$ ChangeZoneAll | Cost$ 4 W W | ChangeType$ Creature | Origin$ Battlefield | Destination$ Library | LibraryPosition$ Bottom",
    "K:Miracle:W"]],
  ["cyclonic-rift-m629", "Cyclonic Rift", "Instant", "1 U",
   ["A:SP$ ChangeZoneAll | Cost$ 1 U | ChangeType$ Permanent.OppCtrl | Origin$ Battlefield | Destination$ Hand",
    "K:Overload:6 U"]],
  ["austere-command-m629", "Austere Command", "Sorcery", "4 W W",
   ["A:SP$ Charm | Cost$ 4 W W | Choices$ DestroyAllCheap,DestroyAllExpensive,DestroyAllArtifactsEnchantments,DestroyAllCreatures | CharmNum$ 2"]],
  ["damnation-saga-m629", "Damnation Saga M629", "Sorcery", "2 B B",
   ["A:SP$ DestroyAll | Cost$ 2 B B | ValidCards$ Creature | NoRegen$ True"]],
  ["plague-wind-m629", "Plague Wind", "Sorcery", "7 B B",
   ["A:SP$ DestroyAll | Cost$ 7 B B | ValidCards$ Creature.OppCtrl | NoRegen$ True"]],
  ["damnation-eclipse-m629", "Damnation Eclipse", "Sorcery", "3 B B",
   ["A:SP$ DestroyAll | Cost$ 3 B B | ValidCards$ Creature | DamageEachTarget$ 13"]],
  ["farewell-m629", "Farewell", "Sorcery", "4 W W",
   ["A:SP$ ChangeZoneAll | Cost$ 4 W W | ChangeType$ Creature,Artifact,Enchantment,Graveyard | Origin$ Battlefield | Destination$ Exile"]],

  // ── Color hosers / protection.
  ["circle-of-protection-red-m629", "Circle Protection Red", "Enchantment", "1 W",
   ["A:AB$ PreventDamage | Cost$ 1 | Defined$ You | DmgFromValid$ Card.Red | Amount$ Any"]],
  ["true-name-nemesis-m629", "True Name Nemesis", "Creature Merfolk Rogue", "1 U",
   ["PT:3/1",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigChoose",
    "SVar:TrigChoose:DB$ ChoosePlayer"]],
  ["spell-snare-m629", "Spell Snare", "Instant", "U",
   ["A:SP$ Counter | Cost$ U | TargetType$ Spell | ValidTgts$ Card.cmcEQ2"]],
  ["mental-misstep-m629", "Mental Misstep", "Instant", "U/P",
   ["A:SP$ Counter | Cost$ UP | TargetType$ Spell | ValidTgts$ Card.cmcEQ1"]],
  ["leyline-of-sanctity-m629", "Leyline of Sanctity", "Enchantment", "2 W W",
   ["S:Mode$ Continuous | Affected$ You | AddKeyword$ Hexproof",
    "K:LeylineETB"]],
  ["leyline-of-the-void-m629", "Leyline of the Void", "Enchantment", "2 B B",
   ["R:Event$ Moved | ValidCard$ Card.OppOwn | Destination$ Graveyard | ReplaceWith$ DBExile",
    "SVar:DBExile:DB$ ChangeZone | Origin$ All | Destination$ Exile"]],
  ["leyline-of-anticipation-m629", "Leyline of Anticipation", "Enchantment", "2 U U",
   ["S:Mode$ Continuous | Affected$ Card.YouOwn+nonLand+inZoneHand | AddKeyword$ Flash"]],
  ["leyline-of-vitality-m629", "Leyline of Vitality", "Enchantment", "2 G G",
   ["S:Mode$ Continuous | Affected$ Creature.YouCtrl | AddToughness$ 1",
    "A:AB$ GainLife | Cost$ T Sac<1/CARDNAME> | LifeAmount$ X"]],
  ["leyline-of-punishment-m629", "Leyline Punishment", "Enchantment", "2 R R",
   ["S:Mode$ Continuous | Affected$ Player | CantGainLife$ True"]],
  ["leyline-of-lifeforce-m629", "Leyline Lifeforce", "Enchantment", "2 G G",
   ["S:Mode$ Continuous | Affected$ Card.Green+inZoneStack | CantBeCountered$ True"]],

  // ── Lands & utility.
  ["gaeas-cradle-m629", "Gaeas Cradle", "Legendary Land", "noCost",
   ["A:AB$ Mana | Cost$ T | Produced$ G | Amount$ X | References$ X",
    "SVar:X:Count$Valid Creature.YouCtrl"]],
  ["serra-sanctum-m629", "Serras Sanctum", "Legendary Land", "noCost",
   ["A:AB$ Mana | Cost$ T | Produced$ W | Amount$ X | References$ X",
    "SVar:X:Count$Valid Enchantment.YouCtrl"]],
  ["tolarian-academy-m629", "Tolarian Academy", "Legendary Land", "noCost",
   ["A:AB$ Mana | Cost$ T | Produced$ U | Amount$ X | References$ X",
    "SVar:X:Count$Valid Artifact.YouCtrl"]],
  ["library-of-alexandria-m629", "Library of Alexandria", "Land", "noCost",
   ["A:AB$ Mana | Cost$ T | Produced$ C | Amount$ 1",
    "A:AB$ Draw | Cost$ T | NumCards$ 1 | ConditionPlayerCardsInHand$ EQ7"]],
  ["mishras-factory-m629", "Mishras Factory", "Land", "noCost",
   ["A:AB$ Mana | Cost$ T | Produced$ C",
    "A:AB$ Animate | Cost$ 1 | Defined$ Self | Power$ 2 | Toughness$ 2 | Types$ Creature,Assembly-Worker"]],
  ["mutavault-m629", "Mutavault", "Land", "noCost",
   ["A:AB$ Mana | Cost$ T | Produced$ C",
    "A:AB$ Animate | Cost$ 1 | Defined$ Self | Power$ 2 | Toughness$ 2 | Types$ Creature"]],
  ["celestial-colonnade-m629", "Celestial Colonnade", "Land", "noCost",
   ["K:CARDNAME enters tapped.",
    "A:AB$ Mana | Cost$ T | Produced$ W U",
    "A:AB$ Animate | Cost$ 3 W U | Defined$ Self | Power$ 4 | Toughness$ 4 | Types$ Creature,Elemental | Keywords$ Flying & Vigilance"]],
  ["raging-ravine-m629", "Raging Ravine", "Land", "noCost",
   ["K:CARDNAME enters tapped.",
    "A:AB$ Mana | Cost$ T | Produced$ B R",
    "A:AB$ Animate | Cost$ 2 B R | Defined$ Self | Power$ 3 | Toughness$ 3 | Types$ Creature,Elemental"]],
  ["lavaclaw-reaches-m629", "Lavaclaw Reaches", "Land", "noCost",
   ["A:AB$ Mana | Cost$ T | Produced$ B R",
    "A:AB$ Animate | Cost$ 2 B R | Defined$ Self | Power$ 0 | Toughness$ 2 | Types$ Creature,Elemental"]],
  ["cavern-of-souls-m629", "Cavern of Souls", "Land", "noCost",
   ["T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigChooseType",
    "SVar:TrigChooseType:DB$ ChooseType",
    "A:AB$ Mana | Cost$ T | Produced$ Any"]],

  // ── Card-draw engines.
  ["sylvan-scrying-m629", "Sylvan Scrying", "Sorcery", "1 G",
   ["A:SP$ ChangeZone | Cost$ 1 G | Origin$ Library | Destination$ Hand | ChangeType$ Land"]],
  ["expedition-map-m629", "Expedition Map", "Artifact", "1",
   ["A:AB$ ChangeZone | Cost$ 2 T Sac<1/CARDNAME> | Origin$ Library | Destination$ Hand | ChangeType$ Land"]],
  ["preordain-m629", "Preordain", "Sorcery", "U",
   ["A:SP$ Scry | Cost$ U | ScryNum$ 2 | SubAbility$ DBDraw",
    "SVar:DBDraw:DB$ Draw | NumCards$ 1"]],
  ["ponder-m629", "Ponder", "Sorcery", "U",
   ["A:SP$ Effect | Cost$ U | SpellDescription$ Top 3 reorder. | SubAbility$ DBDraw",
    "SVar:DBDraw:DB$ Draw | NumCards$ 1"]],
  ["brainstorm-m629", "Brainstorm M629", "Instant", "U",
   ["A:SP$ Draw | Cost$ U | NumCards$ 3 | SubAbility$ DBPut",
    "SVar:DBPut:DB$ ChangeZone | Origin$ Hand | Destination$ Library | ChangeNum$ 2 | LibraryPosition$ 0"]],
  ["serum-visions-m629", "Serum Visions", "Sorcery", "U",
   ["A:SP$ Draw | Cost$ U | NumCards$ 1 | SubAbility$ DBScry",
    "SVar:DBScry:DB$ Scry | ScryNum$ 2"]],
  ["opt-m629", "Opt", "Instant", "U",
   ["A:SP$ Scry | Cost$ U | ScryNum$ 1 | SubAbility$ DBDraw",
    "SVar:DBDraw:DB$ Draw | NumCards$ 1"]],
  ["thoughtcast-m629", "Thoughtcast", "Sorcery", "4 U",
   ["A:SP$ Draw | Cost$ 4 U | NumCards$ 2",
    "K:Affinity:Artifact"]],
  ["chart-a-course-m629", "Chart a Course", "Sorcery", "1 U",
   ["A:SP$ Draw | Cost$ 1 U | NumCards$ 2 | SubAbility$ DBDiscard",
    "SVar:DBDiscard:DB$ Discard | NumCards$ 1 | Mode$ TgtChoose"]],
  ["consider-m629", "Consider", "Instant", "U",
   ["A:SP$ Mill | Cost$ U | NumCards$ 1 | TargetType$ Player | Defined$ You | SubAbility$ DBDraw",
    "SVar:DBDraw:DB$ Draw | NumCards$ 1"]],

  // ── Combat tricks.
  ["giant-growth-m629", "Giant Growth M629", "Instant", "G",
   ["A:SP$ Pump | Cost$ G | TargetType$ Creature | ValidTgts$ Creature | NumAtt$ +3 | NumDef$ +3"]],
  ["might-of-old-krosa-m629", "Might Old Krosa", "Instant", "G",
   ["A:SP$ Pump | Cost$ G | TargetType$ Creature | ValidTgts$ Creature | NumAtt$ +2 | NumDef$ +2"]],
  ["become-thunder-m629", "Become Thunder", "Instant", "1 R",
   ["A:SP$ Pump | Cost$ 1 R | TargetType$ Creature | ValidTgts$ Creature | NumAtt$ +3 | KW$ Trample"]],
  ["wrap-in-vigor-m629", "Wrap in Vigor", "Instant", "G",
   ["A:SP$ PumpAll | Cost$ G | ValidCards$ Creature.YouCtrl | KW$ Indestructible"]],
  ["heroic-intervention-m629", "Heroic Intervention", "Instant", "1 G",
   ["A:SP$ PumpAll | Cost$ 1 G | ValidCards$ Permanent.YouCtrl | KW$ Hexproof & Indestructible"]],
  ["teferis-protection-m629", "Teferis Protection", "Instant", "2 W W",
   ["A:SP$ Effect | Cost$ 2 W W | SpellDescription$ Phase out + protect."]],
  ["blossoming-defense-m629", "Blossoming Defense", "Instant", "G",
   ["A:SP$ Pump | Cost$ G | TargetType$ Creature | ValidTgts$ Creature.YouCtrl | NumAtt$ +2 | NumDef$ +2 | KW$ Hexproof"]],
  ["ranger-class-attack-m629", "Ranger Class Attack", "Instant", "G",
   ["A:SP$ PumpAll | Cost$ G | ValidCards$ Creature.YouCtrl | NumAtt$ +1 | NumDef$ +1"]],
  ["mizzium-mortars-m629", "Mizzium Mortars", "Sorcery", "1 R",
   ["A:SP$ DealDamage | Cost$ 1 R | NumDmg$ 4 | ValidTgts$ Creature",
    "K:Overload:4 R R"]],
  ["sublime-epiphany-m629", "Sublime Epiphany", "Instant", "3 U U",
   ["A:SP$ Charm | Cost$ 3 U U | Choices$ Counter,Bounce,Copy,Tap,Negate | CharmNum$ 5 | RepeatChoose$ True"]],
];

const seedStart = 0xb000;
let i = 2105;
let seed = seedStart;
let out = "";
for (const [stem, name, types, cost, lines] of CARDS) {
  const fullName = name + " M629";
  const id = stem + (stem.endsWith("-m629") ? "" : "-m629");
  out += "\n  // " + i + ". " + fullName + " ETB.\n";
  out += "  {\n";
  out += "    id: \"" + id + "\",\n";
  out += "    description: \"" + fullName + " ETB.\",\n";
  out += "    seed: 0x" + seed.toString(16) + ",\n";
  out += "    cards: {\n";
  out += "      \"" + fullName + "\": `Name:" + fullName + "\nManaCost:" + cost + "\nTypes:" + types + "\n";
  // Splice PT line right after Types so Forge parser's order-sensitive bits hold.
  // Actually the lines themselves include PT when relevant; just dump them in order.
  for (const ln of lines) out += ln + "\n";
  out += "Oracle:" + fullName.split(" ").map(w => w[0]).join("") + " parse.\n`,\n";
  out += "    },\n";
  out += "    players: [\n";
  out += "      { life: 20, hand: [\"" + fullName + "\"], battlefield: [] },\n";
  out += "      { life: 20, hand: [], battlefield: [] },\n";
  out += "    ],\n";
  out += "    actions: [{ kind: \"etb\", cardName: \"" + fullName + "\", controller: SEAT0 }],\n";
  out += "  },\n";
  i++;
  seed++;
}
console.error("// generated " + CARDS.length + " scenarios; next i=" + i + ", next seed=0x" + seed.toString(16));
process.stdout.write(out);
