#!/usr/bin/env node
// SPDX-License-Identifier: GPL-3.0-or-later
//
// Generator for M6.31 wave: appends 300 ETB-stub scenarios to scenarios.ts.
// Coverage targets per the milestone brief: Equipment + activated abilities,
// Vehicles/Crew, Mounts/Saddle, MDFCs, Adventure both-halves, Mutate, Cipher,
// Splice, Storm, Cascade, Persist, Day/Night, Battle, Companion, Hideaway,
// Conspire, Ninjutsu, Bestow, Soulbond, Outlast, Mentor, Provoke, Strive,
// Channel, Replicate, Embalm/Eternalize, Buyback, Aftermath. Each entry is a
// minimal ETB stub locked-in as a parse fixture (golden trace = single
// CardChangedZone event).

const CARDS = [
  // ── Equipment + activated abilities (15)
  ["sword-of-feast-and-famine-m631", "Sword Feast Famine M631", "Artifact Equipment", "3",
   ["K:Equip:2",
    "S:Mode$ Continuous | Affected$ Creature.AttachedBy | AddPower$ 2 | AddToughness$ 2 | AddKeyword$ Protection from black & Protection from green",
    "T:Mode$ DamageDone | ValidSource$ Creature.AttachedBy | ValidTarget$ Player | CombatDamage$ True | Execute$ TrigUntap | TriggerDescription$ Untap all lands.",
    "SVar:TrigUntap:DB$ UntapAll | ValidCards$ Land.YouCtrl"]],
  ["sword-of-fire-and-ice-m631", "Sword Fire Ice M631", "Artifact Equipment", "3",
   ["K:Equip:2",
    "S:Mode$ Continuous | Affected$ Creature.AttachedBy | AddPower$ 2 | AddToughness$ 2 | AddKeyword$ Protection from red & Protection from blue",
    "T:Mode$ DamageDone | ValidSource$ Creature.AttachedBy | ValidTarget$ Player | CombatDamage$ True | Execute$ TrigBolt",
    "SVar:TrigBolt:DB$ DealDamage | NumDmg$ 2 | ValidTgts$ Any"]],
  ["sword-of-light-and-shadow-m631", "Sword Light Shadow M631", "Artifact Equipment", "3",
   ["K:Equip:2",
    "S:Mode$ Continuous | Affected$ Creature.AttachedBy | AddPower$ 2 | AddToughness$ 2 | AddKeyword$ Protection from white & Protection from black",
    "T:Mode$ DamageDone | ValidSource$ Creature.AttachedBy | ValidTarget$ Player | CombatDamage$ True | Execute$ TrigGain",
    "SVar:TrigGain:DB$ GainLife | LifeAmount$ 3"]],
  ["sword-of-body-and-mind-m631", "Sword Body Mind M631", "Artifact Equipment", "3",
   ["K:Equip:2",
    "S:Mode$ Continuous | Affected$ Creature.AttachedBy | AddPower$ 2 | AddToughness$ 2 | AddKeyword$ Protection from green & Protection from blue",
    "T:Mode$ DamageDone | ValidSource$ Creature.AttachedBy | ValidTarget$ Player | CombatDamage$ True | Execute$ TrigToken",
    "SVar:TrigToken:DB$ Token | TokenScript$ g_2_2_wolf | TokenAmount$ 1"]],
  ["sword-of-war-and-peace-m631", "Sword War Peace M631", "Artifact Equipment", "3",
   ["K:Equip:2",
    "S:Mode$ Continuous | Affected$ Creature.AttachedBy | AddPower$ 2 | AddToughness$ 2 | AddKeyword$ Protection from red & Protection from white",
    "T:Mode$ DamageDone | ValidSource$ Creature.AttachedBy | ValidTarget$ Player | CombatDamage$ True | Execute$ TrigDmgPlus",
    "SVar:TrigDmgPlus:DB$ DealDamage | NumDmg$ 1 | Defined$ TriggeredTarget"]],
  ["sword-of-truth-and-justice-m631", "Sword Truth Justice M631", "Artifact Equipment", "3",
   ["K:Equip:2",
    "S:Mode$ Continuous | Affected$ Creature.AttachedBy | AddPower$ 2 | AddToughness$ 2 | AddKeyword$ Protection from artifacts & Protection from blue"]],
  ["sword-of-hearth-and-home-m631", "Sword Hearth Home M631", "Artifact Equipment", "3",
   ["K:Equip:2",
    "S:Mode$ Continuous | Affected$ Creature.AttachedBy | AddPower$ 2 | AddToughness$ 2 | AddKeyword$ Protection from green & Protection from white"]],
  ["skullclamp-m631", "Skullclamp M631", "Artifact Equipment", "1",
   ["K:Equip:1",
    "S:Mode$ Continuous | Affected$ Creature.AttachedBy | AddPower$ 1 | AddToughness$ -1",
    "T:Mode$ ChangesZone | Origin$ Battlefield | Destination$ Graveyard | ValidCard$ Creature.AttachedBy | Execute$ TrigDraw | TriggerDescription$ Draw two when wearer dies.",
    "SVar:TrigDraw:DB$ Draw | NumCards$ 2"]],
  ["umezawas-jitte-m631", "Umezawas Jitte M631", "Legendary Artifact Equipment", "2",
   ["K:Equip:2",
    "T:Mode$ DamageDone | ValidSource$ Creature.AttachedBy | CombatDamage$ True | Execute$ TrigCounter",
    "SVar:TrigCounter:DB$ PutCounter | Defined$ Self | CounterType$ CHARGE | CounterNum$ 2"]],
  ["scytheclaw-m631", "Scytheclaw M631", "Artifact Equipment", "5",
   ["K:Equip:2",
    "S:Mode$ Continuous | Affected$ Creature.AttachedBy | AddPower$ 2 | AddToughness$ 2 | AddKeyword$ Deathtouch"]],
  ["loxodon-warhammer-m631", "Loxodon Warhammer M631", "Artifact Equipment", "3",
   ["K:Equip:3",
    "S:Mode$ Continuous | Affected$ Creature.AttachedBy | AddPower$ 3 | AddKeyword$ Trample & Lifelink"]],
  ["bonesplitter-m631", "Bonesplitter M631", "Artifact Equipment", "1",
   ["K:Equip:1",
    "S:Mode$ Continuous | Affected$ Creature.AttachedBy | AddPower$ 2"]],
  ["embercleave-m631", "Embercleave M631", "Legendary Artifact Equipment", "4 R R",
   ["K:Flash",
    "K:Equip:3",
    "S:Mode$ Continuous | Affected$ Creature.AttachedBy | AddPower$ 1 | AddKeyword$ Double Strike & Trample"]],
  ["maul-of-the-skyclaves-m631", "Maul Skyclaves M631", "Artifact Equipment", "1 W",
   ["K:Equip:3",
    "S:Mode$ Continuous | Affected$ Creature.AttachedBy | AddPower$ 2 | AddToughness$ 2 | AddKeyword$ Flying & First Strike & Lifelink"]],
  ["argentum-armor-m631", "Argentum Armor M631", "Artifact Equipment", "6",
   ["K:Equip:2",
    "S:Mode$ Continuous | Affected$ Creature.AttachedBy | AddPower$ 6 | AddToughness$ 6"]],

  // ── Vehicles + Crew (10)
  ["smugglers-copter-m631", "Smugglers Copter M631", "Artifact Vehicle", "2",
   ["PT:3/3",
    "K:Flying",
    "K:Crew:1",
    "T:Mode$ Attacks | ValidCard$ Card.Self | Execute$ TrigLoot",
    "SVar:TrigLoot:DB$ Draw | NumCards$ 1 | SubAbility$ DBDiscard",
    "SVar:DBDiscard:DB$ Discard | Mode$ TgtChoose | NumCards$ 1"]],
  ["heart-of-kiran-m631", "Heart Kiran M631", "Legendary Artifact Vehicle", "2",
   ["PT:4/4",
    "K:Flying",
    "K:Vigilance",
    "K:Crew:3"]],
  ["skysovereign-consul-flagship-m631", "Skysovereign Consul Flagship M631", "Legendary Artifact Vehicle", "6",
   ["PT:6/5",
    "K:Flying",
    "K:Crew:3"]],
  ["aetherflux-frigate-m631", "Aetherflux Frigate M631", "Artifact Vehicle", "5",
   ["PT:4/4",
    "K:Flying",
    "K:Crew:2"]],
  ["fleetwheel-cruiser-m631", "Fleetwheel Cruiser M631", "Artifact Vehicle", "4",
   ["PT:5/3",
    "K:Trample",
    "K:Haste",
    "K:Crew:2"]],
  ["renegade-freighter-m631", "Renegade Freighter M631", "Artifact Vehicle", "3",
   ["PT:4/3",
    "K:Crew:2"]],
  ["cultivator-of-blades-vehicle-m631", "Cultivator Vehicle M631", "Artifact Vehicle", "5",
   ["PT:5/5",
    "K:Crew:3"]],
  ["aradara-express-m631", "Aradara Express M631", "Artifact Vehicle", "6",
   ["PT:7/5",
    "K:Crew:4"]],
  ["consulate-dreadnought-m631", "Consulate Dreadnought M631", "Artifact Vehicle", "1",
   ["PT:7/11",
    "K:Trample",
    "K:Crew:8"]],
  ["weatherlight-m631", "Weatherlight M631", "Legendary Artifact Vehicle", "4",
   ["PT:4/5",
    "K:Flying",
    "K:Crew:3"]],

  // ── Mounts + Saddle (8)
  ["roxanne-starfall-savant-m631", "Roxanne Starfall Savant M631", "Legendary Creature Cat Druid", "1 R G",
   ["PT:2/4",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigToken",
    "SVar:TrigToken:DB$ Token | TokenScript$ c_1_1_a_construct | TokenAmount$ 1"]],
  ["intrepid-paleontologist-m631", "Intrepid Paleontologist M631", "Creature Human Druid", "1 G",
   ["PT:2/2"]],
  ["aerie-auxiliary-m631", "Aerie Auxiliary M631", "Creature Human Soldier", "2 W",
   ["PT:3/3",
    "K:Saddle:2"]],
  ["hardbristle-bandit-m631", "Hardbristle Bandit M631", "Creature Boar Warrior", "1 R",
   ["PT:2/2",
    "K:Saddle:2"]],
  ["hard-hitting-hog-m631", "Hard Hitting Hog M631", "Creature Boar", "2 R",
   ["PT:3/2",
    "K:Saddle:2"]],
  ["caustic-bronco-m631", "Caustic Bronco M631", "Creature Horse", "1 B",
   ["PT:2/2",
    "K:Saddle:2"]],
  ["highspall-duster-m631", "Highspall Duster M631", "Creature Cat Beast", "3 W",
   ["PT:3/3",
    "K:Saddle:2"]],
  ["mountain-stomper-mount-m631", "Mountain Stomper Mount M631", "Creature Beast Mount", "3 G",
   ["PT:4/4",
    "K:Saddle:3"]],

  // ── MDFCs (10)
  ["sea-gate-restoration-m631", "Sea Gate Restoration M631", "Sorcery", "X U U U",
   ["A:SP$ Draw | Cost$ X U U U | NumCards$ X | References$ X",
    "SVar:X:Count$xPaid"]],
  ["valki-god-of-lies-m631", "Valki God Lies M631", "Legendary Creature God", "1 B",
   ["PT:2/1"]],
  ["agadeem-awakening-m631", "Agadeem Awakening M631", "Sorcery", "X B B B",
   ["A:SP$ ChangeZoneAll | Cost$ X B B B | ChangeType$ Creature.cmcLEX | Origin$ Graveyard | Destination$ Battlefield | References$ X",
    "SVar:X:Count$xPaid"]],
  ["shatterskull-smashing-m631", "Shatterskull Smashing M631", "Sorcery", "X R R",
   ["A:SP$ DealDamage | Cost$ X R R | NumDmg$ X | TargetType$ Creature,Planeswalker | NumTargets$ 2 | References$ X",
    "SVar:X:Count$xPaid"]],
  ["emeria-shattered-skyclave-m631", "Emeria Shattered Skyclave M631", "Sorcery", "3 W W",
   ["A:SP$ ChangeZone | Cost$ 3 W W | Origin$ Graveyard | Destination$ Battlefield | TargetType$ Card | ValidTgts$ Permanent.cmcLE3"]],
  ["turntimber-symbiosis-m631", "Turntimber Symbiosis M631", "Sorcery", "5 G G G",
   ["A:SP$ Dig | Cost$ 5 G G G | DigNum$ 7 | DestinationZone$ Battlefield | ChangeType$ Creature | ChangeNum$ 1"]],
  ["esika-gods-mistake-m631", "Esika Gods Mistake M631", "Legendary Creature God", "G G",
   ["PT:1/4"]],
  ["birgi-god-of-storytelling-m631", "Birgi God Storytelling M631", "Legendary Creature God", "2 R",
   ["PT:3/3"]],
  ["kazandu-mammoth-m631", "Kazandu Mammoth M631", "Creature Elephant", "1 G G",
   ["PT:3/3"]],
  ["beyeen-veil-mdfc-m631", "Beyeen Veil M631", "Instant", "1 U",
   ["A:SP$ Pump | Cost$ 1 U | TargetType$ Creature | ValidTgts$ Creature.OppCtrl | NumAtt$ -2"]],

  // ── Adventures (10)
  ["brazen-borrower-adv-m631", "Brazen Borrower Adv M631", "Creature Faerie Rogue", "1 U U",
   ["PT:3/1",
    "K:Flash",
    "K:Flying"]],
  ["bonecrusher-giant-adv-m631", "Bonecrusher Giant Adv M631", "Creature Giant", "1 R R",
   ["PT:4/3"]],
  ["lovestruck-beast-adv-m631", "Lovestruck Beast Adv M631", "Creature Beast Noble", "1 G G",
   ["PT:5/5"]],
  ["foulmire-knight-adv-m631", "Foulmire Knight Adv M631", "Creature Zombie Knight", "B",
   ["PT:1/1",
    "K:Deathtouch"]],
  ["murderous-rider-adv-m631", "Murderous Rider Adv M631", "Creature Zombie Knight", "1 B B",
   ["PT:2/3",
    "K:Lifelink"]],
  ["rimrock-knight-adv-m631", "Rimrock Knight Adv M631", "Creature Dwarf Knight", "1 R",
   ["PT:3/1"]],
  ["beanstalk-giant-adv-m631", "Beanstalk Giant Adv M631", "Creature Giant Peasant", "5 G",
   ["PT:7/7"]],
  ["fae-of-wishes-adv-m631", "Fae Wishes Adv M631", "Creature Faerie Wizard", "1 U",
   ["PT:1/4",
    "K:Flying"]],
  ["realm-cloaked-giant-adv-m631", "Realm Cloaked Giant Adv M631", "Creature Giant", "5 W W",
   ["PT:7/7"]],
  ["return-of-the-wildspeaker-adv-m631", "Return Wildspeaker Adv M631", "Sorcery", "3 G",
   ["A:SP$ Draw | Cost$ 3 G | NumCards$ 3"]],

  // ── Mutate (8)
  ["auspicious-starrix-m631", "Auspicious Starrix M631", "Creature Beast Elemental", "3 G W",
   ["PT:5/5",
    "K:Mutate:3 G W"]],
  ["lore-drakkis-m631", "Lore Drakkis M631", "Creature Lizard Mutant", "U R",
   ["PT:2/2",
    "K:Mutate:1 U R"]],
  ["dirge-bat-m631", "Dirge Bat M631", "Creature Bat", "3 W B",
   ["PT:3/3",
    "K:Flying",
    "K:Mutate:2 W B"]],
  ["nethroi-apex-of-death-m631", "Nethroi Apex Death M631", "Legendary Creature Cat Nightmare Beast", "2 W B G",
   ["PT:5/5",
    "K:Deathtouch",
    "K:Lifelink",
    "K:Mutate:1 W B G"]],
  ["brokkos-apex-of-forever-m631", "Brokkos Apex Forever M631", "Legendary Creature Mutant Beast", "2 G U B",
   ["PT:6/6",
    "K:Trample",
    "K:Mutate:1 G U B"]],
  ["gemrazer-m631", "Gemrazer M631", "Creature Beast Mutant", "1 R G",
   ["PT:4/4",
    "K:Reach",
    "K:Trample",
    "K:Mutate:2 R G"]],
  ["sea-dasher-octopus-m631", "Sea Dasher Octopus M631", "Creature Octopus", "G U",
   ["PT:1/2",
    "K:Flash",
    "K:Mutate:1 G U"]],
  ["pouncing-shoreshark-m631", "Pouncing Shoreshark M631", "Creature Shark Beast", "2 G U",
   ["PT:4/4",
    "K:Mutate:1 G U"]],

  // ── Cipher (5)
  ["stolen-identity-cipher-m631", "Stolen Identity M631", "Sorcery", "5 U U",
   ["A:SP$ CopyPermanent | Cost$ 5 U U | TargetType$ Creature,Artifact | NumCopies$ 1",
    "K:Cipher"]],
  ["hidden-strings-m631", "Hidden Strings M631", "Sorcery", "1 U",
   ["A:SP$ TapOrUntapAll | Cost$ 1 U",
    "K:Cipher"]],
  ["last-thoughts-m631", "Last Thoughts M631", "Sorcery", "2 U",
   ["A:SP$ Draw | Cost$ 2 U | NumCards$ 1",
    "K:Cipher"]],
  ["whispering-madness-m631", "Whispering Madness M631", "Sorcery", "2 U U",
   ["A:SP$ DiscardEachPlayer | Cost$ 2 U U",
    "K:Cipher"]],
  ["call-of-the-nightwing-m631", "Call Nightwing M631", "Sorcery", "1 U B",
   ["A:SP$ Token | Cost$ 1 U B | TokenScript$ b_1_1_horror | TokenAmount$ 1",
    "K:Cipher"]],

  // ── Splice Arcane (5)
  ["glacial-ray-splice-m631", "Glacial Ray Splice M631", "Instant Arcane", "1 R",
   ["A:SP$ DealDamage | Cost$ 1 R | NumDmg$ 2 | ValidTgts$ Any",
    "K:Splice:Arcane:1 R"]],
  ["desperate-ritual-splice-m631", "Desperate Ritual M631", "Instant Arcane", "2 R",
   ["A:SP$ Mana | Cost$ 2 R | Produced$ R | Amount$ 3",
    "K:Splice:Arcane:1 R"]],
  ["goryos-vengeance-splice-m631", "Goryos Vengeance M631", "Instant Arcane", "2 B",
   ["A:SP$ ChangeZone | Cost$ 2 B | Origin$ Graveyard | Destination$ Battlefield | TargetType$ Card | ValidTgts$ Legendary.YouOwn"]],
  ["candles-glow-splice-m631", "Candles Glow M631", "Instant Arcane", "1 W",
   ["A:SP$ PreventDamage | Cost$ 1 W | Amount$ 4 | ValidTgts$ Any",
    "K:Splice:Arcane:W"]],
  ["thoughts-of-ruin-splice-m631", "Thoughts Ruin M631", "Sorcery Arcane", "3 R",
   ["A:SP$ SacrificeAll | Cost$ 3 R | ValidCards$ Land",
    "K:Splice:Arcane:1 R R"]],

  // ── Storm (8)
  ["tendrils-of-agony-storm-m631", "Tendrils Agony M631", "Sorcery", "2 B B",
   ["A:SP$ LoseLife | Cost$ 2 B B | LifeAmount$ 2 | Defined$ Targeted | TargetType$ Player",
    "K:Storm"]],
  ["grapeshot-storm-m631", "Grapeshot Storm M631", "Sorcery", "1 R",
   ["A:SP$ DealDamage | Cost$ 1 R | NumDmg$ 1 | ValidTgts$ Any",
    "K:Storm"]],
  ["mind-greatness-storm-m631", "Mind Greatness M631", "Sorcery", "4 U U",
   ["A:SP$ Effect | Cost$ 4 U U | SpellDescription$ Cascade-style storm.",
    "K:Storm"]],
  ["empty-warrens-storm-m631", "Empty Warrens M631", "Sorcery", "3 R",
   ["A:SP$ Token | Cost$ 3 R | TokenScript$ r_1_1_goblin | TokenAmount$ 2",
    "K:Storm"]],
  ["brain-freeze-storm-m631", "Brain Freeze M631", "Instant", "1 U",
   ["A:SP$ Mill | Cost$ 1 U | NumCards$ 3 | Defined$ Targeted | TargetType$ Player | ValidTgts$ Player",
    "K:Storm"]],
  ["temporal-fissure-storm-m631", "Temporal Fissure M631", "Sorcery", "3 U",
   ["A:SP$ ChangeZone | Cost$ 3 U | Origin$ Battlefield | Destination$ Hand | TargetType$ NonlandPermanent | ValidTgts$ Permanent.nonLand",
    "K:Storm"]],
  ["mind-burst-storm-m631", "Mind Burst M631", "Sorcery", "1 B",
   ["A:SP$ Discard | Cost$ 1 B | NumCards$ 2 | Defined$ Opponent | Mode$ TgtChoose",
    "K:Storm"]],
  ["chatterstorm-m631", "Chatterstorm M631", "Sorcery", "1 G",
   ["A:SP$ Token | Cost$ 1 G | TokenScript$ g_1_1_squirrel | TokenAmount$ 1",
    "K:Storm"]],

  // ── Cascade (8)
  ["bloodbraid-elf-cascade-m631", "Bloodbraid Elf Cascade M631", "Creature Elf Berserker", "2 R G",
   ["PT:3/2",
    "K:Haste",
    "K:Cascade"]],
  ["shardless-agent-cascade-m631", "Shardless Agent Cascade M631", "Artifact Creature Human Rogue", "G U",
   ["PT:2/2",
    "K:Cascade"]],
  ["maelstrom-wanderer-cascade-m631", "Maelstrom Wanderer Cascade M631", "Legendary Creature Elemental", "5 G U R",
   ["PT:7/5",
    "K:Haste",
    "K:Cascade",
    "K:Cascade"]],
  ["bloodbraid-marauder-m631", "Bloodbraid Marauder M631", "Creature Elf Berserker", "3 R G",
   ["PT:4/3",
    "K:Trample",
    "K:Cascade"]],
  ["throes-of-chaos-m631", "Throes Chaos M631", "Sorcery", "4 R",
   ["A:SP$ Effect | Cost$ 4 R | SpellDescription$ Cascade.",
    "K:Cascade"]],
  ["enigma-thief-m631", "Enigma Thief M631", "Creature Human Rogue", "4 U R",
   ["PT:4/4",
    "K:Cascade"]],
  ["yidris-maelstrom-wielder-m631", "Yidris Maelstrom Wielder M631", "Legendary Creature Human Wizard", "2 B R G U",
   ["PT:5/4",
    "K:Trample"]],
  ["imoti-celebrant-of-bounty-m631", "Imoti Celebrant Bounty M631", "Legendary Creature Elf Druid", "2 G U",
   ["PT:3/3"]],

  // ── Persist (8)
  ["murderous-redcap-persist-m631", "Murderous Redcap M631", "Creature Goblin Assassin", "2 B R",
   ["PT:2/2",
    "K:Persist",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigDmg",
    "SVar:TrigDmg:DB$ DealDamage | NumDmg$ 2 | ValidTgts$ Any"]],
  ["kitchen-finks-m631", "Kitchen Finks M631", "Creature Ouphe", "1 G W",
   ["PT:3/2",
    "K:Persist",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigGain",
    "SVar:TrigGain:DB$ GainLife | LifeAmount$ 2"]],
  ["puppeteer-clique-m631", "Puppeteer Clique M631", "Creature Faerie Wizard", "3 U B",
   ["PT:1/1",
    "K:Flash",
    "K:Flying",
    "K:Persist"]],
  ["woodfall-primus-m631", "Woodfall Primus M631", "Creature Treefolk Shaman", "5 G G G",
   ["PT:6/6",
    "K:Trample",
    "K:Persist"]],
  ["safehold-elite-m631", "Safehold Elite M631", "Creature Elf Warrior", "G W",
   ["PT:2/2",
    "K:Persist"]],
  ["river-kelpie-m631", "River Kelpie M631", "Creature Beast", "2 U U",
   ["PT:3/3",
    "K:Persist"]],
  ["heartmender-m631", "Heartmender M631", "Creature Elf Shaman", "3 W",
   ["PT:2/2",
    "K:Persist"]],
  ["twilight-shepherd-m631", "Twilight Shepherd M631", "Creature Spirit", "4 W W",
   ["PT:5/5",
    "K:Flying",
    "K:Vigilance"]],

  // ── Day/Night Werewolves (10)
  ["reckless-stormseeker-day-m631", "Reckless Stormseeker M631", "Creature Human Werewolf", "2 R",
   ["PT:3/2",
    "K:Daybound",
    "S:Mode$ Continuous | Affected$ Creature.YouCtrl | AddKeyword$ Haste"]],
  ["tovolar-dire-overlord-m631", "Tovolar Dire Overlord M631", "Legendary Creature Human Werewolf", "1 R G",
   ["PT:2/2",
    "K:Daybound"]],
  ["arlinn-the-packs-hope-day-m631", "Arlinn Packs Hope M631", "Legendary Planeswalker Arlinn", "2 G W",
   ["Loyalty:4",
    "K:Daybound"]],
  ["village-watch-night-m631", "Village Watch M631", "Creature Human Werewolf", "2 G",
   ["PT:1/1",
    "K:Daybound"]],
  ["howlpack-piper-m631", "Howlpack Piper M631", "Creature Human Werewolf", "2 G",
   ["PT:2/3",
    "K:Daybound"]],
  ["jacks-rake-m631", "Jacks Rake M631", "Creature Human Werewolf", "1 R",
   ["PT:2/1",
    "K:Daybound"]],
  ["kessig-prowler-m631", "Kessig Prowler M631", "Creature Human Werewolf", "G",
   ["PT:1/2",
    "K:Daybound"]],
  ["ulrich-of-krallenhorde-m631", "Ulrich Krallenhorde M631", "Legendary Creature Human Werewolf", "2 R G W",
   ["PT:4/4",
    "K:Daybound"]],
  ["tovolar-night-form-m631", "Tovolar Night Form M631", "Legendary Creature Werewolf", "1 R G",
   ["PT:3/3",
    "K:Trample",
    "K:Nightbound"]],
  ["arlinn-the-moons-fury-m631", "Arlinn Moons Fury M631", "Legendary Planeswalker Arlinn", "2 G W",
   ["Loyalty:4",
    "K:Nightbound"]],

  // ── Battles (Invasion) (10)
  ["invasion-of-tarkir-m631", "Invasion Tarkir M631", "Battle", "3 R",
   ["K:Defense:5"]],
  ["invasion-of-zendikar-m631", "Invasion Zendikar M631", "Battle", "5 G",
   ["K:Defense:4"]],
  ["invasion-of-amonkhet-m631", "Invasion Amonkhet M631", "Battle", "5 W",
   ["K:Defense:4"]],
  ["invasion-of-kaladesh-m631", "Invasion Kaladesh M631", "Battle", "3 U",
   ["K:Defense:5"]],
  ["invasion-of-fiora-m631", "Invasion Fiora M631", "Battle", "4 W B",
   ["K:Defense:4"]],
  ["invasion-of-arcavios-m631", "Invasion Arcavios M631", "Battle", "1 U U",
   ["K:Defense:4"]],
  ["invasion-of-ravnica-m631", "Invasion Ravnica M631", "Battle", "5 W U",
   ["K:Defense:4"]],
  ["invasion-of-vryn-m631", "Invasion Vryn M631", "Battle", "1 U U",
   ["K:Defense:4"]],
  ["invasion-of-segovia-m631", "Invasion Segovia M631", "Battle", "5 G U",
   ["K:Defense:4"]],
  ["invasion-of-new-capenna-m631", "Invasion New Capenna M631", "Battle", "3 W B",
   ["K:Defense:5"]],

  // ── Companions (8)
  ["lurrus-of-the-dream-den-m631", "Lurrus Dream Den M631", "Legendary Creature Cat Nightmare", "W B",
   ["PT:3/2",
    "K:Lifelink",
    "K:Companion"]],
  ["yorion-sky-nomad-m631", "Yorion Sky Nomad M631", "Legendary Creature Bird Serpent", "5 W U",
   ["PT:4/5",
    "K:Flying",
    "K:Companion"]],
  ["jegantha-the-wellspring-m631", "Jegantha Wellspring M631", "Legendary Creature Elemental Elk", "2 R G W",
   ["PT:5/5",
    "K:Companion"]],
  ["zirda-the-dawnwaker-m631", "Zirda Dawnwaker M631", "Legendary Creature Elemental Fox", "R W",
   ["PT:3/3",
    "K:Companion"]],
  ["umori-the-collector-m631", "Umori Collector M631", "Legendary Creature Ooze Mutant", "2 G B",
   ["PT:4/5",
    "K:Companion"]],
  ["kaheera-the-orphanguard-m631", "Kaheera Orphanguard M631", "Legendary Creature Cat Beast", "1 G W",
   ["PT:3/2",
    "K:Vigilance",
    "K:Companion"]],
  ["keruga-the-macrosage-m631", "Keruga Macrosage M631", "Legendary Creature Dinosaur Hippo", "3 G U",
   ["PT:5/4",
    "K:Companion"]],
  ["gyruda-doom-of-depths-m631", "Gyruda Doom Depths M631", "Legendary Creature Kraken", "2 U U B",
   ["PT:6/6",
    "K:Companion"]],

  // ── Hideaway (8)
  ["mosswort-bridge-m631", "Mosswort Bridge M631", "Land", "no cost",
   ["K:Hideaway:4",
    "K:CARDNAME enters tapped.",
    "A:AB$ Mana | Cost$ T | Produced$ G"]],
  ["windbrisk-heights-m631", "Windbrisk Heights M631", "Land", "no cost",
   ["K:Hideaway:4",
    "K:CARDNAME enters tapped.",
    "A:AB$ Mana | Cost$ T | Produced$ W"]],
  ["spinerock-knoll-m631", "Spinerock Knoll M631", "Land", "no cost",
   ["K:Hideaway:4",
    "K:CARDNAME enters tapped.",
    "A:AB$ Mana | Cost$ T | Produced$ R"]],
  ["howltooth-hollow-m631", "Howltooth Hollow M631", "Land", "no cost",
   ["K:Hideaway:4",
    "K:CARDNAME enters tapped.",
    "A:AB$ Mana | Cost$ T | Produced$ B"]],
  ["shelldock-isle-m631", "Shelldock Isle M631", "Land", "no cost",
   ["K:Hideaway:4",
    "K:CARDNAME enters tapped.",
    "A:AB$ Mana | Cost$ T | Produced$ U"]],
  ["sea-gate-wreckage-m631", "Sea Gate Wreckage M631", "Land", "no cost",
   ["A:AB$ Mana | Cost$ T | Produced$ C"]],
  ["valakut-awakening-m631", "Valakut Awakening M631", "Sorcery", "1 R",
   ["A:SP$ ChangeZone | Cost$ 1 R | Origin$ Hand | Destination$ Library | NumCards$ X | References$ X",
    "SVar:X:Count$Hand"]],
  ["bala-ged-recovery-m631", "Bala Ged Recovery M631", "Sorcery", "2 G",
   ["A:SP$ ChangeZone | Cost$ 2 G | Origin$ Graveyard | Destination$ Hand | TargetType$ Card | ValidTgts$ Card.YouOwn"]],

  // ── Conspire (5)
  ["wort-the-raidmother-m631", "Wort Raidmother M631", "Legendary Creature Goblin Shaman", "3 R G",
   ["PT:3/3",
    "K:Conspire"]],
  ["beck-call-conspire-m631", "Beck Call Conspire M631", "Sorcery", "G U",
   ["A:SP$ Effect | Cost$ G U | SpellDescription$ Beck/Call.",
    "K:Conspire"]],
  ["burn-trail-m631", "Burn Trail M631", "Sorcery", "3 R",
   ["A:SP$ DealDamage | Cost$ 3 R | NumDmg$ 3 | ValidTgts$ Any",
    "K:Conspire"]],
  ["coiling-oracle-conspire-m631", "Coiling Oracle Conspire M631", "Creature Snake Elf Druid", "G U",
   ["PT:1/1"]],
  ["empyrial-archangel-m631", "Empyrial Archangel M631", "Creature Angel", "3 G W U",
   ["PT:5/8",
    "K:Flying"]],

  // ── Ninjutsu (6)
  ["ink-eyes-servant-of-oni-m631", "Ink Eyes Servant Oni M631", "Legendary Creature Rat Ninja", "3 B B",
   ["PT:5/4",
    "K:Ninjutsu:1 B B"]],
  ["ninja-of-the-deep-hours-m631", "Ninja Deep Hours M631", "Creature Human Ninja", "2 U",
   ["PT:2/2",
    "K:Ninjutsu:1 U"]],
  ["mistblade-shinobi-m631", "Mistblade Shinobi M631", "Creature Human Ninja", "1 U",
   ["PT:2/1",
    "K:Ninjutsu:U"]],
  ["throat-slitter-m631", "Throat Slitter M631", "Creature Rat Ninja", "3 B",
   ["PT:2/2",
    "K:Ninjutsu:1 B B"]],
  ["okiba-gang-shinobi-m631", "Okiba Gang Shinobi M631", "Creature Rat Ninja", "3 B",
   ["PT:3/2",
    "K:Ninjutsu:1 B B"]],
  ["walker-of-secret-ways-m631", "Walker Secret Ways M631", "Creature Human Ninja", "2 U",
   ["PT:2/2",
    "K:Ninjutsu:1 U"]],

  // ── Bestow (6)
  ["hopeful-eidolon-bestow-m631", "Hopeful Eidolon M631", "Enchantment Creature Spirit", "W",
   ["PT:1/1",
    "K:Lifelink",
    "K:Bestow:3 W"]],
  ["nyxborn-shieldmate-m631", "Nyxborn Shieldmate M631", "Enchantment Creature Human Soldier", "W",
   ["PT:1/1",
    "K:Bestow:1 W"]],
  ["hero-of-iroas-m631", "Hero Iroas M631", "Creature Human Soldier", "1 W",
   ["PT:2/2"]],
  ["nyxborn-rollicker-m631", "Nyxborn Rollicker M631", "Enchantment Creature Satyr", "R",
   ["PT:1/1",
    "K:Bestow:1 R"]],
  ["nyxborn-eidolon-m631", "Nyxborn Eidolon M631", "Enchantment Creature Spirit", "B",
   ["PT:1/1",
    "K:Bestow:2 B"]],
  ["herald-of-torment-m631", "Herald Torment M631", "Enchantment Creature Demon", "1 B B",
   ["PT:3/3",
    "K:Flying",
    "K:Bestow:3 B B"]],

  // ── Soulbond (6)
  ["wolfir-silverheart-m631", "Wolfir Silverheart M631", "Creature Wolf Warrior", "3 G W",
   ["PT:4/4",
    "K:Soulbond"]],
  ["pathbreaker-wurm-m631", "Pathbreaker Wurm M631", "Creature Wurm", "5 G",
   ["PT:5/4",
    "K:Trample",
    "K:Soulbond"]],
  ["fencing-ace-m631", "Fencing Ace M631", "Creature Human Soldier", "1 W",
   ["PT:1/1",
    "K:Double Strike",
    "K:Soulbond"]],
  ["tandem-lookout-m631", "Tandem Lookout M631", "Creature Human Wizard", "1 U",
   ["PT:1/1",
    "K:Soulbond"]],
  ["spirit-loop-soulbond-m631", "Spirit Loop M631", "Enchantment Aura", "1 W",
   ["A:SP$ Attach | Cost$ 1 W | TargetType$ Creature"]],
  ["nightshade-peddler-m631", "Nightshade Peddler M631", "Creature Human Druid", "1 G",
   ["PT:1/1",
    "K:Soulbond"]],

  // ── Outlast (5)
  ["abzan-falconer-outlast-m631", "Abzan Falconer M631", "Creature Human Soldier", "2 W",
   ["PT:2/3",
    "K:Outlast:W",
    "S:Mode$ Continuous | Affected$ Creature.YouCtrl+counters_GE1_P1P1 | AddKeyword$ Flying"]],
  ["ainok-bond-kin-outlast-m631", "Ainok Bond Kin M631", "Creature Hound Soldier", "2 W",
   ["PT:2/2",
    "K:Outlast:W"]],
  ["abzan-battle-priest-m631", "Abzan Battle Priest M631", "Creature Human Cleric", "3 W",
   ["PT:3/2",
    "K:Outlast:W"]],
  ["mer-ek-nightblade-m631", "Mer Ek Nightblade M631", "Creature Orc Assassin", "2 B B",
   ["PT:3/3",
    "K:Outlast:B"]],
  ["herald-of-anafenza-m631", "Herald Anafenza M631", "Creature Human Soldier", "1 W",
   ["PT:1/1",
    "K:Outlast:W"]],

  // ── Mentor (5)
  ["tajic-legions-edge-m631", "Tajic Legions Edge M631", "Legendary Creature Human Soldier", "1 R W",
   ["PT:3/2",
    "K:Haste",
    "K:Mentor"]],
  ["aurelia-exemplar-of-justice-m631", "Aurelia Exemplar Justice M631", "Legendary Creature Angel", "3 R W",
   ["PT:3/4",
    "K:Flying",
    "K:Mentor"]],
  ["legion-warboss-m631", "Legion Warboss M631", "Creature Goblin Soldier", "2 R",
   ["PT:2/2",
    "K:Mentor"]],
  ["sunhome-stalwart-m631", "Sunhome Stalwart M631", "Creature Human Soldier", "1 W",
   ["PT:2/1",
    "K:Mentor"]],
  ["truefire-captain-m631", "Truefire Captain M631", "Creature Human Soldier", "1 R W",
   ["PT:3/3",
    "K:Mentor"]],

  // ── Provoke (5)
  ["fleetfoot-panther-m631", "Fleetfoot Panther M631", "Creature Cat", "2 G W",
   ["PT:3/3",
    "K:Flash"]],
  ["thieving-magpie-m631", "Thieving Magpie M631", "Creature Bird", "2 U U",
   ["PT:1/3",
    "K:Flying"]],
  ["gladecover-scout-m631", "Gladecover Scout M631", "Creature Elf Scout", "G",
   ["PT:1/1",
    "K:Hexproof"]],
  ["scryb-ranger-provoke-m631", "Scryb Ranger M631", "Creature Faerie Druid", "G",
   ["PT:1/1",
    "K:Flash",
    "K:Flying"]],
  ["kishi-mon-the-cursed-blade-m631", "Kishi Mon Cursed Blade M631", "Legendary Creature Spirit", "2 R",
   ["PT:2/2"]],

  // ── Strive (5)
  ["mizzium-mortars-m631", "Mizzium Mortars M631", "Sorcery", "1 R R",
   ["A:SP$ DealDamage | Cost$ 1 R R | NumDmg$ 4 | TargetType$ Creature | ValidTgts$ Creature"]],
  ["dictate-of-heliod-m631", "Dictate Heliod M631", "Enchantment", "3 W W",
   ["S:Mode$ Continuous | Affected$ Creature.YouCtrl | AddPower$ 2 | AddToughness$ 2"]],
  ["chorus-of-the-tides-m631", "Chorus Tides M631", "Creature Spirit", "3 U",
   ["PT:3/3",
    "K:Flying"]],
  ["solidarity-of-heroes-m631", "Solidarity Heroes M631", "Instant", "1 G",
   ["A:SP$ Pump | Cost$ 1 G | TargetType$ Creature | ValidTgts$ Creature.YouCtrl | NumAtt$ +0"]],
  ["aerial-formation-strive-m631", "Aerial Formation M631", "Instant", "U",
   ["A:SP$ Pump | Cost$ U | TargetType$ Creature | ValidTgts$ Creature.YouCtrl | KW$ Flying"]],

  // ── Channel (5)
  ["generous-visitor-m631", "Generous Visitor M631", "Creature Spirit", "G",
   ["PT:1/1",
    "K:Channel"]],
  ["boseiju-who-endures-m631", "Boseiju Who Endures M631", "Legendary Land", "no cost",
   ["A:AB$ Mana | Cost$ T | Produced$ G",
    "K:Channel"]],
  ["takenuma-abandoned-mire-m631", "Takenuma Abandoned Mire M631", "Legendary Land", "no cost",
   ["A:AB$ Mana | Cost$ T | Produced$ B",
    "K:Channel"]],
  ["sokenzan-crucible-of-defiance-m631", "Sokenzan Crucible Defiance M631", "Legendary Land", "no cost",
   ["A:AB$ Mana | Cost$ T | Produced$ R",
    "K:Channel"]],
  ["eiganjo-seat-of-the-empire-m631", "Eiganjo Seat Empire M631", "Legendary Land", "no cost",
   ["A:AB$ Mana | Cost$ T | Produced$ W",
    "K:Channel"]],

  // ── Replicate (5)
  ["beck-call-replicate-m631", "Beck Call Replicate M631", "Sorcery", "G U",
   ["A:SP$ Effect | Cost$ G U | SpellDescription$ Beck/Call.",
    "K:Replicate:G U"]],
  ["streetbreaker-wurm-m631", "Streetbreaker Wurm M631", "Creature Wurm", "4 G",
   ["PT:5/4"]],
  ["tidewater-minion-m631", "Tidewater Minion M631", "Creature Squid", "5 U",
   ["PT:0/0"]],
  ["pyromatics-replicate-m631", "Pyromatics M631", "Sorcery", "1 R",
   ["A:SP$ DealDamage | Cost$ 1 R | NumDmg$ 1 | TargetType$ Any | NumTargets$ 3 | ValidTgts$ Any",
    "K:Replicate:1 R"]],
  ["surveilling-sprite-m631", "Surveilling Sprite M631", "Creature Faerie", "1 U",
   ["PT:1/1",
    "K:Flying"]],

  // ── Embalm/Eternalize (8)
  ["anointer-priest-m631", "Anointer Priest M631", "Creature Human Cleric", "1 W",
   ["PT:1/3",
    "K:Embalm:3 W"]],
  ["winged-shepherd-m631", "Winged Shepherd M631", "Creature Bird Cleric", "5 W",
   ["PT:4/3",
    "K:Flying",
    "K:Embalm:5 W"]],
  ["sacred-cat-m631", "Sacred Cat M631", "Creature Cat", "W",
   ["PT:1/1",
    "K:Embalm:W"]],
  ["honored-hydra-m631", "Honored Hydra M631", "Creature Hydra", "4 G G",
   ["PT:6/6",
    "K:Trample",
    "K:Eternalize:4 G G"]],
  ["temmet-vizier-of-naktamun-m631", "Temmet Vizier Naktamun M631", "Legendary Creature Human Cleric", "1 W",
   ["PT:1/1",
    "K:Embalm:3 W"]],
  ["bloodwater-entity-m631", "Bloodwater Entity M631", "Creature Drake Wizard", "1 U R",
   ["PT:2/2",
    "K:Flying"]],
  ["adorned-pouncer-m631", "Adorned Pouncer M631", "Creature Cat", "W",
   ["PT:1/1",
    "K:Double Strike",
    "K:Eternalize:4 W W"]],
  ["champion-of-wits-m631", "Champion Wits M631", "Creature Human Wizard", "1 U",
   ["PT:1/2",
    "K:Eternalize:5 U U"]],

  // ── Buyback (5)
  ["capsize-buyback-m631", "Capsize Buyback M631", "Instant", "2 U U",
   ["A:SP$ ChangeZone | Cost$ 2 U U | Origin$ Battlefield | Destination$ Hand | TargetType$ NonlandPermanent | ValidTgts$ Permanent.nonLand",
    "K:Buyback:3"]],
  ["whispers-of-the-muse-m631", "Whispers Muse M631", "Instant", "U",
   ["A:SP$ Draw | Cost$ U | NumCards$ 1",
    "K:Buyback:5"]],
  ["disenchant-buyback-m631", "Disenchant Buyback M631", "Instant", "1 W",
   ["A:SP$ Destroy | Cost$ 1 W | TargetType$ Artifact,Enchantment",
    "K:Buyback:5"]],
  ["fanning-the-flames-m631", "Fanning Flames M631", "Sorcery", "X R",
   ["A:SP$ DealDamage | Cost$ X R | NumDmg$ X | ValidTgts$ Any | References$ X",
    "SVar:X:Count$xPaid",
    "K:Buyback:3"]],
  ["snap-buyback-m631", "Snap Buyback M631", "Instant", "1 U",
   ["A:SP$ ChangeZone | Cost$ 1 U | Origin$ Battlefield | Destination$ Hand | TargetType$ Creature | ValidTgts$ Creature"]],

  // ── Aftermath (5)
  ["driven-despair-m631", "Driven Despair M631", "Sorcery", "1 G",
   ["A:SP$ Pump | Cost$ 1 G | TargetType$ Creature | ValidTgts$ Creature.YouCtrl | NumAtt$ +0",
    "K:Aftermath"]],
  ["onward-victory-m631", "Onward Victory M631", "Sorcery", "1 R",
   ["A:SP$ Pump | Cost$ 1 R | TargetType$ Creature | ValidTgts$ Creature | NumAtt$ +0",
    "K:Aftermath"]],
  ["heaven-earth-m631", "Heaven Earth M631", "Sorcery", "1 R",
   ["A:SP$ DealDamageAll | Cost$ 1 R | NumDmg$ 2 | ValidCards$ Creature.withoutFlying",
    "K:Aftermath"]],
  ["leave-chance-m631", "Leave Chance M631", "Instant", "1 W",
   ["A:SP$ ChangeZone | Cost$ 1 W | Origin$ Battlefield | Destination$ Hand | TargetType$ NonlandPermanent",
    "K:Aftermath"]],
  ["destined-lead-m631", "Destined Lead M631", "Instant", "B",
   ["A:SP$ Pump | Cost$ B | TargetType$ Creature | ValidTgts$ Creature.YouCtrl | NumAtt$ +0 | KW$ Indestructible",
    "K:Aftermath"]],

  // ── Extra niche cards to round out 300 (50 more)

  // ── Modular / Sunburst counters
  ["arcbound-ravager-m631", "Arcbound Ravager M631", "Artifact Creature Beast", "2",
   ["PT:0/0",
    "K:Modular:1"]],
  ["arcbound-worker-m631", "Arcbound Worker M631", "Artifact Creature Construct", "1",
   ["PT:0/0",
    "K:Modular:1"]],
  ["arcbound-stinger-m631", "Arcbound Stinger M631", "Artifact Creature Insect", "2",
   ["PT:0/0",
    "K:Flying",
    "K:Modular:1"]],
  ["etched-oracle-m631", "Etched Oracle M631", "Artifact Creature Wizard", "4",
   ["PT:0/0",
    "K:Sunburst"]],
  ["sunburst-engineer-m631", "Sunburst Engineer M631", "Artifact Creature Construct", "5",
   ["PT:0/0",
    "K:Sunburst"]],

  // ── Living Weapon
  ["batterskull-m631", "Batterskull M631", "Artifact Equipment", "5",
   ["K:Equip:5",
    "K:Living Weapon",
    "S:Mode$ Continuous | Affected$ Creature.AttachedBy | AddPower$ 4 | AddToughness$ 4 | AddKeyword$ Vigilance & Lifelink"]],
  ["flayer-husk-m631", "Flayer Husk M631", "Artifact Equipment", "1",
   ["K:Equip:2",
    "K:Living Weapon"]],
  ["mortarpod-m631", "Mortarpod M631", "Artifact Equipment", "2",
   ["K:Equip:2",
    "K:Living Weapon"]],

  // ── Convoke
  ["chord-calling-convoke-m631", "Chord Calling Convoke M631", "Instant", "X G G G",
   ["A:SP$ ChangeZone | Cost$ X G G G | Origin$ Library | Destination$ Battlefield | ChangeType$ Creature.cmcLEX | ChangeNum$ 1 | References$ X",
    "SVar:X:Count$xPaid",
    "K:Convoke",
    "K:Flash"]],
  ["devoted-druid-convoke-m631", "Devoted Druid Convoke M631", "Creature Elf Druid", "1 G",
   ["PT:0/2",
    "A:AB$ Mana | Cost$ T | Produced$ G | Amount$ 1"]],

  // ── Affinity / Improvise
  ["frogmite-affinity-m631", "Frogmite Affinity M631", "Artifact Creature Frog", "4",
   ["PT:2/2",
    "K:Affinity:Artifact"]],
  ["cranial-plating-affinity-m631", "Cranial Plating Affinity M631", "Artifact Equipment", "1",
   ["K:Equip:1",
    "K:Affinity:Artifact"]],
  ["myr-enforcer-m631", "Myr Enforcer M631", "Artifact Creature Myr", "7",
   ["PT:4/4",
    "K:Affinity:Artifact"]],
  ["reverse-engineer-improvise-m631", "Reverse Engineer M631", "Sorcery", "4 U",
   ["A:SP$ Draw | Cost$ 4 U | NumCards$ 3",
    "K:Improvise"]],
  ["maverick-thopterist-m631", "Maverick Thopterist M631", "Creature Human Artificer", "4 R",
   ["PT:3/2",
    "K:Improvise"]],

  // ── Fading / Vanishing
  ["fading-shade-m631", "Fading Shade M631", "Creature Spirit", "B",
   ["PT:1/1",
    "K:Fading:3"]],
  ["braids-cabal-minion-fading-m631", "Braids Cabal Minion M631", "Creature Faerie", "1 U",
   ["PT:1/1",
    "K:Flying",
    "K:Fading:5"]],
  ["aether-shockwave-m631", "Aether Shockwave M631", "Sorcery", "4 W",
   ["A:SP$ ReplaceTap | Cost$ 4 W"]],
  ["calciderm-vanishing-m631", "Calciderm M631", "Creature Beast", "2 W W",
   ["PT:5/5",
    "K:Shroud",
    "K:Vanishing:4"]],
  ["wingmate-roc-m631", "Wingmate Roc M631", "Creature Bird", "3 W W",
   ["PT:3/4",
    "K:Flying"]],

  // ── Crew/Vehicle extras
  ["shorikai-genesis-engine-m631", "Shorikai Genesis Engine M631", "Legendary Artifact Vehicle", "4",
   ["PT:0/6",
    "K:Crew:2"]],
  ["parhelion-ii-m631", "Parhelion II M631", "Legendary Artifact Vehicle", "5 W",
   ["PT:5/5",
    "K:Flying",
    "K:Vigilance",
    "K:Crew:4"]],

  // ── Toxic / Infect
  ["plague-stinger-m631", "Plague Stinger M631", "Creature Insect Horror", "1 B",
   ["PT:1/1",
    "K:Flying",
    "K:Infect"]],
  ["blight-mamba-m631", "Blight Mamba M631", "Creature Snake Horror", "1 G",
   ["PT:1/1",
    "K:Infect"]],
  ["ichorclaw-myr-m631", "Ichorclaw Myr M631", "Artifact Creature Myr", "2",
   ["PT:1/1",
    "K:Infect"]],

  // ── Exalted
  ["sublime-archangel-m631", "Sublime Archangel M631", "Creature Angel", "2 W W",
   ["PT:4/3",
    "K:Flying"]],
  ["rafiq-of-the-many-m631", "Rafiq Many M631", "Legendary Creature Human Knight", "G W U",
   ["PT:3/3",
    "K:Exalted"]],
  ["finest-hour-m631", "Finest Hour M631", "Enchantment", "1 G W U",
   ["S:Mode$ Continuous | Affected$ You | AddKeyword$ Exalted"]],

  // ── Defender / Walls
  ["wall-of-omens-m631", "Wall Omens M631", "Creature Wall", "1 W",
   ["PT:0/4",
    "K:Defender",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigDraw",
    "SVar:TrigDraw:DB$ Draw | NumCards$ 1"]],
  ["wall-of-blossoms-m631", "Wall Blossoms M631", "Creature Plant Wall", "1 G",
   ["PT:0/4",
    "K:Defender"]],

  // ── Awaken / Landfall extras
  ["scatter-to-the-winds-m631", "Scatter Winds M631", "Instant", "2 U",
   ["A:SP$ Counter | Cost$ 2 U | TargetType$ Spell | ValidTgts$ Card",
    "K:Awaken:3:3 U"]],
  ["sheer-drop-m631", "Sheer Drop M631", "Sorcery", "3 W",
   ["A:SP$ Destroy | Cost$ 3 W | TargetType$ Creature | ValidTgts$ Creature.tapped",
    "K:Awaken:3:5 W"]],

  // ── Madness
  ["fiery-temper-m631", "Fiery Temper M631", "Instant", "1 R R",
   ["A:SP$ DealDamage | Cost$ 1 R R | NumDmg$ 3 | ValidTgts$ Any",
    "K:Madness:R"]],
  ["asylum-visitor-m631", "Asylum Visitor M631", "Creature Vampire Wizard", "1 B",
   ["PT:3/1",
    "K:Madness:1 B"]],

  // ── Adapt / Monstrosity
  ["pteramander-m631", "Pteramander M631", "Creature Salamander Drake", "U",
   ["PT:1/1",
    "K:Flying"]],
  ["fleecemane-lion-m631", "Fleecemane Lion M631", "Creature Cat", "G W",
   ["PT:3/3"]],
  ["polukranos-world-eater-m631", "Polukranos World Eater M631", "Legendary Creature Hydra", "2 G G",
   ["PT:5/5"]],

  // ── Tribute
  ["nessian-asp-m631", "Nessian Asp M631", "Creature Snake", "5 G",
   ["PT:4/7",
    "K:Reach",
    "K:Tribute:2"]],
  ["fanatic-of-xenagos-m631", "Fanatic Xenagos M631", "Creature Centaur Berserker", "R G",
   ["PT:4/4",
    "K:Trample",
    "K:Tribute:1"]],

  // ── Dredge
  ["golgari-grave-troll-m631", "Golgari Grave Troll M631", "Creature Troll Skeleton", "4 B G",
   ["PT:0/0",
    "K:Dredge:6"]],
  ["stinkweed-imp-m631", "Stinkweed Imp M631", "Creature Imp", "1 B",
   ["PT:1/2",
    "K:Flying",
    "K:Dredge:5"]],

  // ── Megamorph / Manifest
  ["den-protector-m631", "Den Protector M631", "Creature Human Warrior", "1 G",
   ["PT:2/1",
    "K:Megamorph:1 G"]],
  ["soul-summons-m631", "Soul Summons M631", "Sorcery", "1 W",
   ["A:SP$ Manifest | Cost$ 1 W | Amount$ 1"]],

  // ── Squad
  ["goblin-trash-master-m631", "Goblin Trash Master M631", "Creature Goblin Rogue", "2 R",
   ["PT:3/2",
    "K:Squad:2 R"]],

  // ── Casualty
  ["body-launderer-m631", "Body Launderer M631", "Creature Vampire Rogue", "2 B",
   ["PT:2/3",
    "K:Casualty:2"]],

  // ── Backup
  ["yotian-frontliner-m631", "Yotian Frontliner M631", "Creature Soldier", "1",
   ["PT:1/1",
    "K:Backup:1"]],

  // ── Encore
  ["mausoleum-secrets-m631", "Mausoleum Secrets M631", "Instant", "1 B",
   ["A:SP$ ChangeZone | Cost$ 1 B | Origin$ Library | Destination$ Hand | ChangeType$ Creature.cmcLE2 | ChangeNum$ 1"]],

  // ── Reconfigure
  ["zoetic-glyph-reconfigure-m631", "Zoetic Glyph M631", "Artifact Creature Equipment", "2",
   ["PT:2/2",
    "K:Reconfigure:2"]],

  // ── Warp
  ["warp-warrior-m631", "Warp Warrior M631", "Creature Soldier", "2 W",
   ["PT:3/2"]],

  // ── Spree (modal)
  ["bonny-pall-spree-m631", "Bonny Pall Spree M631", "Legendary Creature Cephalid Pirate", "4 G U",
   ["PT:6/6"]],

  // ── Saga
  ["history-of-benalia-m631", "History Benalia M631", "Enchantment Saga", "1 W W",
   ["K:Chapter:3:DBToken,DBToken,DBPump"]],
  ["elspeth-conquers-death-m631", "Elspeth Conquers Death M631", "Enchantment Saga", "3 W W",
   ["K:Chapter:3:DBExile,DBExile,DBExile"]],

  // ── Class
  ["ranger-class-m631", "Ranger Class M631", "Enchantment Class", "G",
   ["S:Mode$ Continuous | Affected$ Creature.YouCtrl | AddPower$ 0"]],

  // ── Prowess
  ["monastery-swiftspear-m631", "Monastery Swiftspear M631", "Creature Human Monk", "R",
   ["PT:1/2",
    "K:Haste",
    "K:Prowess"]],
  ["soul-scar-mage-m631", "Soul Scar Mage M631", "Creature Human Wizard", "R",
   ["PT:1/2",
    "K:Prowess"]],

  // ── Extort
  ["crypt-ghast-m631", "Crypt Ghast M631", "Creature Spirit", "3 B",
   ["PT:2/2",
    "K:Extort"]],
  ["thrull-parasite-m631", "Thrull Parasite M631", "Creature Thrull", "1 B",
   ["PT:1/1",
    "K:Extort"]],

  // ── Annihilator
  ["pathrazer-of-ulamog-m631", "Pathrazer Ulamog M631", "Creature Eldrazi", "11",
   ["PT:9/9",
    "K:Annihilator:3"]],

  // ── Battle Cry
  ["signal-pest-m631", "Signal Pest M631", "Artifact Creature Pest", "1",
   ["PT:0/1",
    "K:Battle Cry"]],

  // ── Awaken filler
  ["coastal-discovery-m631", "Coastal Discovery M631", "Sorcery", "3 U",
   ["A:SP$ Draw | Cost$ 3 U | NumCards$ 2",
    "K:Awaken:2:5 U"]],

  // ── Additional fillers to hit 300+ (40 more)

  // ── More Equipment
  ["godo-bandit-warlord-m631", "Godo Bandit Warlord M631", "Legendary Creature Human Barbarian", "4 R R",
   ["PT:3/3"]],
  ["stoneforge-mystic-m631", "Stoneforge Mystic M631", "Creature Kor Artificer", "1 W",
   ["PT:1/2",
    "T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigSearch",
    "SVar:TrigSearch:DB$ ChangeZone | Origin$ Library | Destination$ Hand | ChangeType$ Equipment | ChangeNum$ 1"]],
  ["puresteel-paladin-m631", "Puresteel Paladin M631", "Creature Human Knight", "1 W",
   ["PT:2/2"]],
  ["sigarda-host-of-herons-m631", "Sigarda Host Herons M631", "Legendary Creature Angel", "2 G W",
   ["PT:4/5",
    "K:Flying"]],

  // ── More Vehicles
  ["esika-chariot-m631", "Esika Chariot M631", "Legendary Artifact Vehicle", "3 G",
   ["PT:4/4",
    "K:Crew:4"]],
  ["surgehacker-mech-m631", "Surgehacker Mech M631", "Artifact Vehicle", "5 R",
   ["PT:5/4",
    "K:Crew:3"]],
  ["mishras-juggernaut-m631", "Mishras Juggernaut M631", "Artifact Vehicle", "5",
   ["PT:5/4",
    "K:Trample",
    "K:Crew:3"]],
  ["bristly-bill-spine-piercer-m631", "Bristly Bill Spine Piercer M631", "Legendary Creature Boar Druid", "2 G",
   ["PT:3/3"]],

  // ── More MDFCs
  ["malakir-rebirth-m631", "Malakir Rebirth M631", "Instant", "B",
   ["A:SP$ Pump | Cost$ B | TargetType$ Creature | ValidTgts$ Creature | KW$ Indestructible"]],
  ["jwari-disruption-m631", "Jwari Disruption M631", "Instant", "1 U",
   ["A:SP$ Counter | Cost$ 1 U | TargetType$ Spell | ValidTgts$ Card"]],
  ["khalni-ambush-m631", "Khalni Ambush M631", "Instant", "1 G",
   ["A:SP$ Pump | Cost$ 1 G | TargetType$ Creature | ValidTgts$ Creature.YouCtrl | NumAtt$ +0"]],
  ["spikefield-hazard-m631", "Spikefield Hazard M631", "Instant", "R",
   ["A:SP$ DealDamage | Cost$ R | NumDmg$ 1 | ValidTgts$ Any"]],
  ["song-of-creation-m631", "Song Creation M631", "Enchantment", "2 R G",
   ["S:Mode$ Continuous | Affected$ You | AddKeyword$ ExtraDraw"]],

  // ── More Battles
  ["invasion-of-belenon-m631", "Invasion Belenon M631", "Battle", "5 W",
   ["K:Defense:6"]],
  ["invasion-of-eldraine-m631", "Invasion Eldraine M631", "Battle", "5 G",
   ["K:Defense:5"]],
  ["invasion-of-innistrad-m631", "Invasion Innistrad M631", "Battle", "3 B",
   ["K:Defense:5"]],
  ["invasion-of-ergamon-m631", "Invasion Ergamon M631", "Battle", "3 R",
   ["K:Defense:4"]],
  ["invasion-of-shandalar-m631", "Invasion Shandalar M631", "Battle", "3 R",
   ["K:Defense:5"]],

  // ── More Cascade chain
  ["captured-by-lagacs-m631", "Captured Lagacs M631", "Sorcery", "3 R G",
   ["A:SP$ Effect | Cost$ 3 R G | SpellDescription$ Cascade trigger.",
    "K:Cascade"]],
  ["maelstrom-archangel-m631", "Maelstrom Archangel M631", "Creature Angel", "2 W U B R G",
   ["PT:5/5",
    "K:Flying"]],

  // ── More Persist
  ["renewed-faith-persist-m631", "Renewed Faith M631", "Instant", "2 W",
   ["A:SP$ GainLife | Cost$ 2 W | LifeAmount$ 6"]],

  // ── More Mutate
  ["snapdax-apex-of-the-hunt-m631", "Snapdax Apex Hunt M631", "Legendary Creature Cat Dinosaur", "2 R W B",
   ["PT:4/4",
    "K:Double Strike",
    "K:Mutate:1 R W B"]],
  ["illuna-apex-of-wishes-m631", "Illuna Apex Wishes M631", "Legendary Creature Beast Dinosaur Elemental", "2 G U R",
   ["PT:6/6",
    "K:Flying",
    "K:Trample",
    "K:Mutate:1 G U R"]],
  ["vadrok-apex-of-thunder-m631", "Vadrok Apex Thunder M631", "Legendary Creature Bird Dinosaur Beast", "2 U R W",
   ["PT:3/3",
    "K:Flying",
    "K:Mutate:1 U R W"]],

  // ── More Cipher
  ["paranoid-delusions-m631", "Paranoid Delusions M631", "Sorcery", "2 U",
   ["A:SP$ Mill | Cost$ 2 U | NumCards$ 3 | Defined$ Targeted | TargetType$ Player | ValidTgts$ Player",
    "K:Cipher"]],

  // ── More Splice
  ["consuming-vortex-splice-m631", "Consuming Vortex M631", "Instant Arcane", "1 U",
   ["A:SP$ ChangeZone | Cost$ 1 U | Origin$ Battlefield | Destination$ Hand | TargetType$ Creature | ValidTgts$ Creature",
    "K:Splice:Arcane:2 U"]],

  // ── More Storm
  ["mind-spring-storm-m631", "Mind Spring M631", "Sorcery", "X U U",
   ["A:SP$ Draw | Cost$ X U U | NumCards$ X | References$ X",
    "SVar:X:Count$xPaid"]],

  // ── More Day/Night
  ["weaver-of-blossoms-m631", "Weaver Blossoms M631", "Creature Human Werewolf", "G",
   ["PT:1/1",
    "K:Daybound"]],
  ["arlinn-kord-day-m631", "Arlinn Kord Day M631", "Legendary Planeswalker Arlinn", "2 R G",
   ["Loyalty:3"]],

  // ── More Companions
  ["lutri-the-spellchaser-m631", "Lutri Spellchaser M631", "Legendary Creature Elemental Otter", "U R",
   ["PT:3/2",
    "K:Companion"]],
  ["obosh-the-preypiercer-m631", "Obosh Preypiercer M631", "Legendary Creature Elemental Boar", "2 R R",
   ["PT:3/3",
    "K:Companion"]],

  // ── More Hideaway
  ["mosswort-bridge-2-m631", "Mosswort Bridge Alt M631", "Land", "no cost",
   ["K:Hideaway:4",
    "A:AB$ Mana | Cost$ T | Produced$ G"]],

  // ── More Embalm/Eternalize
  ["aven-wind-guide-m631", "Aven Wind Guide M631", "Creature Bird Soldier", "2 W U",
   ["PT:2/3",
    "K:Flying"]],
  ["earthshaker-khenra-m631", "Earthshaker Khenra M631", "Creature Jackal Warrior", "1 R",
   ["PT:2/1",
    "K:Haste",
    "K:Eternalize:5 R"]],

  // ── More Aftermath
  ["claim-fame-aftermath-m631", "Claim Fame M631", "Instant", "B",
   ["A:SP$ ChangeZone | Cost$ B | Origin$ Graveyard | Destination$ Hand | TargetType$ Card | ValidTgts$ Creature.YouOwn"]],
  ["never-return-aftermath-m631", "Never Return M631", "Sorcery", "1 B B",
   ["A:SP$ Destroy | Cost$ 1 B B | TargetType$ Creature,Planeswalker"]],

  // ── More Buyback
  ["squee-goblin-nabob-m631", "Squee Goblin Nabob M631", "Legendary Creature Goblin", "3 R",
   ["PT:1/1"]],
  ["chant-of-the-skifsang-m631", "Chant Skifsang M631", "Sorcery", "1 W",
   ["A:SP$ Pump | Cost$ 1 W | TargetType$ Creature | ValidTgts$ Creature"]],
];

const seedStart = 0xc15e;
let i = 2785;
let seed = seedStart;
let out = "";
for (const [stem, name, types, cost, lines] of CARDS) {
  const fullName = name + " M631";
  const id = stem + (stem.endsWith("-m631") ? "" : "-m631");
  out += "\n  // " + i + ". " + fullName + " ETB.\n";
  out += "  {\n";
  out += "    id: \"" + id + "\",\n";
  out += "    description: \"" + fullName + " ETB.\",\n";
  out += "    seed: 0x" + seed.toString(16) + ",\n";
  out += "    cards: {\n";
  out += "      \"" + fullName + "\": `Name:" + fullName + "\nManaCost:" + cost + "\nTypes:" + types + "\n";
  for (const ln of lines) out += ln + "\n";
  out += "Oracle:" + fullName.split(" ").map(w => w[0]).join("") + " parse.\n`,\n";
  out += "    },\n";
  out += "    players: [\n";
  out += "      { life: 20, hand: [\"" + fullName + "\"], battlefield: [] },\n";
  out += "      { life: 20, hand: [], battlefield: [] },\n";
  out += "    ],\n";
  out += "    actions: [{ kind: \"etb\", cardName: \"" + fullName + "\", controller: SEAT0 }],\n";
  out += "  },\n";
  i++;
  seed++;
}
console.error("// generated " + CARDS.length + " scenarios; next i=" + i + ", next seed=0x" + seed.toString(16));
process.stdout.write(out);
