// SPDX-License-Identifier: GPL-3.0-or-later
import { CORE_VERSION } from "@mtg-forge-ts/core";
export const GAME_VERSION = "0.0.0";
export const LINKED_CORE_VERSION = CORE_VERSION;
export * from "./action/index.js";
export * from "./card.js";
export * from "./combat/index.js";
export * from "./controller/index.js";
export * from "./decision-log/index.js";
export * from "./end/index.js";
export * from "./game-flags.js";
export * from "./game-meta.js";
export * from "./game-rules.js";
export * from "./game.js";
export * from "./mana/index.js";
export * from "./match/index.js";
export * from "./snapshot/index.js";
export * from "./phase/index.js";
export * from "./player.js";
export * from "./registries/index.js";
export * from "./run-game.js";
export * from "./setup/index.js";
export * from "./stack/index.js";
export * from "./target/index.js";
export * from "./terminal-state.js";
export * from "./zone/index.js";
