// SPDX-License-Identifier: GPL-3.0-or-later
import { CORE_VERSION } from "@mtg-forge-ts/core";
export const GAME_VERSION = "0.0.0";
export const LINKED_CORE_VERSION = CORE_VERSION;
export * from "./action/index.js";
export * from "./attachment/index.js";
export * from "./card.js";
export * from "./control-change/index.js";
export * from "./cast/index.js";
export * from "./combat/index.js";
export * from "./continuous/index.js";
export * from "./controller/index.js";
export * from "./copy/index.js";
export * from "./decision-log/index.js";
export * from "./end/index.js";
export * from "./face-down/index.js";
export * from "./game-flags.js";
export * from "./game-meta.js";
export * from "./game-rules.js";
export * from "./game.js";
export * from "./layers/index.js";
export * from "./loop/index.js";
export * from "./mana/index.js";
export * from "./match/index.js";
export * from "./multiface/index.js";
export * from "./phasing/index.js";
export * from "./snapshot/index.js";
export * from "./phase/index.js";
export * from "./player.js";
export * from "./priority/index.js";
export * from "./registries/index.js";
export * from "./replacements/index.js";
export * from "./resolve/index.js";
export * from "./ring/index.js";
export * from "./run-game.js";
export * from "./run-match.js";
export * from "./sba/index.js";
export * from "./setup/index.js";
export * from "./stack/index.js";
export * from "./statics/index.js";
export * from "./target/index.js";
export * from "./terminal-state.js";
export * from "./triggers/index.js";
export * from "./zone/index.js";
export * from "./svar/index.js";
export * from "./cost/parts/index.js";
export * from "./ability/index.js";
