// SPDX-License-Identifier: GPL-3.0-or-later
// Canonical keyword identifiers ported from forge.game.keyword.Keyword.
// Each id is the lowercase_snake_case of the Java enum name.
// displayName mirrors the first constructor arg of the Java enum.
// multipleRedundant mirrors the third constructor arg (isMultipleRedundant0).

interface KeywordMeta {
  readonly id: string;
  readonly displayName: string;
  readonly multipleRedundant: boolean;
}

const META: readonly KeywordMeta[] = [
  { id: "absorb", displayName: "Absorb", multipleRedundant: false },
  { id: "adapt", displayName: "Adapt", multipleRedundant: false },
  { id: "affinity", displayName: "Affinity", multipleRedundant: false },
  { id: "afflict", displayName: "Afflict", multipleRedundant: false },
  { id: "afterlife", displayName: "Afterlife", multipleRedundant: false },
  { id: "aftermath", displayName: "Aftermath", multipleRedundant: false },
  { id: "amplify", displayName: "Amplify", multipleRedundant: false },
  { id: "annihilator", displayName: "Annihilator", multipleRedundant: false },
  { id: "ascend", displayName: "Ascend", multipleRedundant: true },
  { id: "assist", displayName: "Assist", multipleRedundant: true },
  { id: "aura_swap", displayName: "Aura swap", multipleRedundant: false },
  { id: "awaken", displayName: "Awaken", multipleRedundant: false },
  { id: "backup", displayName: "Backup", multipleRedundant: false },
  { id: "banding", displayName: "Banding", multipleRedundant: true },
  { id: "bands_with_other", displayName: "Bands with other", multipleRedundant: false },
  { id: "bargain", displayName: "Bargain", multipleRedundant: false },
  { id: "battle_cry", displayName: "Battle cry", multipleRedundant: false },
  { id: "bestow", displayName: "Bestow", multipleRedundant: false },
  { id: "blitz", displayName: "Blitz", multipleRedundant: false },
  { id: "bloodthirst", displayName: "Bloodthirst", multipleRedundant: false },
  { id: "bushido", displayName: "Bushido", multipleRedundant: false },
  { id: "buyback", displayName: "Buyback", multipleRedundant: false },
  { id: "cascade", displayName: "Cascade", multipleRedundant: false },
  { id: "casualty", displayName: "Casualty", multipleRedundant: false },
  { id: "champion", displayName: "Champion", multipleRedundant: false },
  { id: "channel", displayName: "Channel", multipleRedundant: false },
  { id: "chapter", displayName: "Chapter", multipleRedundant: false },
  { id: "changeling", displayName: "Changeling", multipleRedundant: true },
  { id: "choose_a_background", displayName: "Choose a Background", multipleRedundant: true },
  { id: "cipher", displayName: "Cipher", multipleRedundant: true },
  { id: "companion", displayName: "Companion", multipleRedundant: true },
  { id: "compleated", displayName: "Compleated", multipleRedundant: true },
  { id: "conspire", displayName: "Conspire", multipleRedundant: false },
  { id: "convoke", displayName: "Convoke", multipleRedundant: true },
  { id: "craft", displayName: "Craft", multipleRedundant: false },
  { id: "crew", displayName: "Crew", multipleRedundant: false },
  { id: "cumulative_upkeep", displayName: "Cumulative upkeep", multipleRedundant: false },
  { id: "cycling", displayName: "Cycling", multipleRedundant: false },
  { id: "dash", displayName: "Dash", multipleRedundant: false },
  { id: "daybound", displayName: "Daybound", multipleRedundant: true },
  { id: "deathtouch", displayName: "Deathtouch", multipleRedundant: true },
  { id: "decayed", displayName: "Decayed", multipleRedundant: true },
  { id: "defender", displayName: "Defender", multipleRedundant: true },
  { id: "delve", displayName: "Delve", multipleRedundant: true },
  { id: "demonstrate", displayName: "Demonstrate", multipleRedundant: false },
  { id: "dethrone", displayName: "Dethrone", multipleRedundant: false },
  { id: "devour", displayName: "Devour", multipleRedundant: false },
  { id: "devoid", displayName: "Devoid", multipleRedundant: true },
  { id: "disguise", displayName: "Disguise", multipleRedundant: false },
  { id: "disturb", displayName: "Disturb", multipleRedundant: false },
  { id: "doctors_companion", displayName: "Doctor's companion", multipleRedundant: true },
  { id: "double_agenda", displayName: "Double agenda", multipleRedundant: false },
  { id: "double_strike", displayName: "Double Strike", multipleRedundant: true },
  { id: "double_team", displayName: "Double team", multipleRedundant: false },
  { id: "dredge", displayName: "Dredge", multipleRedundant: false },
  { id: "echo", displayName: "Echo", multipleRedundant: false },
  { id: "embalm", displayName: "Embalm", multipleRedundant: false },
  { id: "emerge", displayName: "Emerge", multipleRedundant: false },
  { id: "enchant", displayName: "Enchant", multipleRedundant: false },
  { id: "encore", displayName: "Encore", multipleRedundant: false },
  { id: "enlist", displayName: "Enlist", multipleRedundant: false },
  { id: "entwine", displayName: "Entwine", multipleRedundant: true },
  { id: "epic", displayName: "Epic", multipleRedundant: true },
  { id: "equip", displayName: "Equip", multipleRedundant: false },
  { id: "escape", displayName: "Escape", multipleRedundant: false },
  { id: "escalate", displayName: "Escalate", multipleRedundant: true },
  { id: "eternalize", displayName: "Eternalize", multipleRedundant: false },
  { id: "etb_counter", displayName: "etbCounter", multipleRedundant: false },
  { id: "etb_replacement", displayName: "ETBReplacement", multipleRedundant: false },
  { id: "class", displayName: "Class", multipleRedundant: false },
  { id: "alternate_additional_cost", displayName: "AlternateAdditionalCost", multipleRedundant: false },
  { id: "visit", displayName: "Visit", multipleRedundant: false },
  { id: "evoke", displayName: "Evoke", multipleRedundant: false },
  { id: "evolve", displayName: "Evolve", multipleRedundant: false },
  { id: "exalted", displayName: "Exalted", multipleRedundant: false },
  { id: "exploit", displayName: "Exploit", multipleRedundant: false },
  { id: "extort", displayName: "Extort", multipleRedundant: false },
  { id: "fabricate", displayName: "Fabricate", multipleRedundant: false },
  { id: "fading", displayName: "Fading", multipleRedundant: false },
  { id: "fear", displayName: "Fear", multipleRedundant: true },
  { id: "firebending", displayName: "Firebending", multipleRedundant: false },
  { id: "first_strike", displayName: "First Strike", multipleRedundant: true },
  { id: "flanking", displayName: "Flanking", multipleRedundant: false },
  { id: "flash", displayName: "Flash", multipleRedundant: true },
  { id: "flashback", displayName: "Flashback", multipleRedundant: false },
  { id: "flying", displayName: "Flying", multipleRedundant: true },
  { id: "for_mirrodin", displayName: "For Mirrodin", multipleRedundant: false },
  { id: "forage", displayName: "Forage", multipleRedundant: false },
  { id: "foretell", displayName: "Foretell", multipleRedundant: false },
  { id: "fortify", displayName: "Fortify", multipleRedundant: false },
  { id: "freerunning", displayName: "Freerunning", multipleRedundant: false },
  { id: "frenzy", displayName: "Frenzy", multipleRedundant: false },
  { id: "fuse", displayName: "Fuse", multipleRedundant: true },
  { id: "gift", displayName: "Gift", multipleRedundant: true },
  { id: "graft", displayName: "Graft", multipleRedundant: false },
  { id: "gravestorm", displayName: "Gravestorm", multipleRedundant: false },
  { id: "harmonize", displayName: "Harmonize", multipleRedundant: false },
  { id: "haste", displayName: "Haste", multipleRedundant: true },
  { id: "haunt", displayName: "Haunt", multipleRedundant: false },
  { id: "hexproof", displayName: "Hexproof", multipleRedundant: true },
  { id: "hideaway", displayName: "Hideaway", multipleRedundant: false },
  { id: "hidden_agenda", displayName: "Hidden agenda", multipleRedundant: false },
  { id: "horsemanship", displayName: "Horsemanship", multipleRedundant: true },
  { id: "impending", displayName: "Impending", multipleRedundant: false },
  { id: "improvise", displayName: "Improvise", multipleRedundant: true },
  { id: "indestructible", displayName: "Indestructible", multipleRedundant: true },
  { id: "infect", displayName: "Infect", multipleRedundant: true },
  { id: "ingest", displayName: "Ingest", multipleRedundant: false },
  { id: "intimidate", displayName: "Intimidate", multipleRedundant: true },
  { id: "kicker", displayName: "Kicker", multipleRedundant: false },
  { id: "job_select", displayName: "Job select", multipleRedundant: false },
  { id: "jump_start", displayName: "Jump-start", multipleRedundant: false },
  { id: "landwalk", displayName: "Landwalk", multipleRedundant: true },
  { id: "level_up", displayName: "Level up", multipleRedundant: false },
  { id: "lifelink", displayName: "Lifelink", multipleRedundant: true },
  { id: "living_metal", displayName: "Living metal", multipleRedundant: true },
  { id: "living_weapon", displayName: "Living Weapon", multipleRedundant: true },
  { id: "madness", displayName: "Madness", multipleRedundant: false },
  { id: "mayhem", displayName: "Mayhem", multipleRedundant: false },
  { id: "melee", displayName: "Melee", multipleRedundant: false },
  { id: "mentor", displayName: "Mentor", multipleRedundant: false },
  { id: "menace", displayName: "Menace", multipleRedundant: true },
  { id: "megamorph", displayName: "Megamorph", multipleRedundant: false },
  { id: "miracle", displayName: "Miracle", multipleRedundant: false },
  { id: "mobilize", displayName: "Mobilize", multipleRedundant: false },
  { id: "modular", displayName: "Modular", multipleRedundant: false },
  { id: "more_than_meets_the_eye", displayName: "More Than Meets the Eye", multipleRedundant: false },
  { id: "morph", displayName: "Morph", multipleRedundant: false },
  { id: "multikicker", displayName: "Multikicker", multipleRedundant: false },
  { id: "mutate", displayName: "Mutate", multipleRedundant: true },
  { id: "myriad", displayName: "Myriad", multipleRedundant: false },
  { id: "nightbound", displayName: "Nightbound", multipleRedundant: true },
  { id: "ninjutsu", displayName: "Ninjutsu", multipleRedundant: false },
  { id: "outlast", displayName: "Outlast", multipleRedundant: false },
  { id: "offering", displayName: "Offering", multipleRedundant: false },
  { id: "offspring", displayName: "Offspring", multipleRedundant: false },
  { id: "overload", displayName: "Overload", multipleRedundant: false },
  { id: "partner", displayName: "Partner", multipleRedundant: true },
  { id: "partner_with", displayName: "Partner with", multipleRedundant: false },
  { id: "persist", displayName: "Persist", multipleRedundant: false },
  { id: "phasing", displayName: "Phasing", multipleRedundant: true },
  { id: "plot", displayName: "Plot", multipleRedundant: false },
  { id: "poisonous", displayName: "Poisonous", multipleRedundant: false },
  { id: "protection", displayName: "Protection", multipleRedundant: true },
  { id: "prototype", displayName: "Prototype", multipleRedundant: false },
  { id: "provoke", displayName: "Provoke", multipleRedundant: false },
  { id: "prowess", displayName: "Prowess", multipleRedundant: false },
  { id: "prowl", displayName: "Prowl", multipleRedundant: false },
  { id: "rampage", displayName: "Rampage", multipleRedundant: false },
  { id: "ravenous", displayName: "Ravenous", multipleRedundant: false },
  { id: "reach", displayName: "Reach", multipleRedundant: true },
  { id: "read_ahead", displayName: "Read ahead", multipleRedundant: true },
  { id: "rebound", displayName: "Rebound", multipleRedundant: true },
  { id: "recover", displayName: "Recover", multipleRedundant: false },
  { id: "reconfigure", displayName: "Reconfigure", multipleRedundant: false },
  { id: "reflect", displayName: "Reflect", multipleRedundant: false },
  { id: "reinforce", displayName: "Reinforce", multipleRedundant: false },
  { id: "renown", displayName: "Renown", multipleRedundant: false },
  { id: "replicate", displayName: "Replicate", multipleRedundant: false },
  { id: "retrace", displayName: "Retrace", multipleRedundant: false },
  { id: "riot", displayName: "Riot", multipleRedundant: false },
  { id: "ripple", displayName: "Ripple", multipleRedundant: false },
  { id: "saddle", displayName: "Saddle", multipleRedundant: false },
  { id: "scavenge", displayName: "Scavenge", multipleRedundant: false },
  { id: "shadow", displayName: "Shadow", multipleRedundant: true },
  { id: "shroud", displayName: "Shroud", multipleRedundant: true },
  { id: "skulk", displayName: "Skulk", multipleRedundant: true },
  { id: "sneak", displayName: "Sneak", multipleRedundant: false },
  { id: "soulbond", displayName: "Soulbond", multipleRedundant: true },
  { id: "soulshift", displayName: "Soulshift", multipleRedundant: false },
  { id: "space_sculptor", displayName: "Space sculptor", multipleRedundant: true },
  { id: "specialize", displayName: "Specialize", multipleRedundant: false },
  { id: "spectacle", displayName: "Spectacle", multipleRedundant: false },
  { id: "splice", displayName: "Splice", multipleRedundant: false },
  { id: "split_second", displayName: "Split second", multipleRedundant: true },
  { id: "spree", displayName: "Spree", multipleRedundant: true },
  { id: "squad", displayName: "Squad", multipleRedundant: false },
  { id: "start_your_engines", displayName: "Start your engines", multipleRedundant: true },
  { id: "starting_intensity", displayName: "Starting intensity", multipleRedundant: true },
  { id: "station", displayName: "Station", multipleRedundant: false },
  { id: "storm", displayName: "Storm", multipleRedundant: false },
  { id: "strive", displayName: "Strive", multipleRedundant: false },
  { id: "sunburst", displayName: "Sunburst", multipleRedundant: false },
  { id: "surge", displayName: "Surge", multipleRedundant: false },
  { id: "suspend", displayName: "Suspend", multipleRedundant: false },
  { id: "tiered", displayName: "Tiered", multipleRedundant: true },
  { id: "toxic", displayName: "Toxic", multipleRedundant: false },
  { id: "training", displayName: "Training", multipleRedundant: false },
  { id: "trample", displayName: "Trample", multipleRedundant: true },
  { id: "transfigure", displayName: "Transfigure", multipleRedundant: false },
  { id: "transmute", displayName: "Transmute", multipleRedundant: false },
  { id: "tribute", displayName: "Tribute", multipleRedundant: false },
  { id: "typecycling", displayName: "TypeCycling", multipleRedundant: false },
  { id: "umbra_armor", displayName: "Umbra armor", multipleRedundant: true },
  { id: "undaunted", displayName: "Undaunted", multipleRedundant: false },
  { id: "undying", displayName: "Undying", multipleRedundant: false },
  { id: "unearth", displayName: "Unearth", multipleRedundant: false },
  { id: "unleash", displayName: "Unleash", multipleRedundant: false },
  { id: "vanishing", displayName: "Vanishing", multipleRedundant: false },
  { id: "vigilance", displayName: "Vigilance", multipleRedundant: true },
  { id: "ward", displayName: "Ward", multipleRedundant: false },
  { id: "warp", displayName: "Warp", multipleRedundant: false },
  { id: "web_slinging", displayName: "Web-slinging", multipleRedundant: false },
  { id: "wither", displayName: "Wither", multipleRedundant: true },
  { id: "mayflashcost", displayName: "MayFlashCost", multipleRedundant: false },
  { id: "mayflashsac", displayName: "MayFlashSac", multipleRedundant: false },
  // Opening-hand / opening-deck "may" effects (Chancellor cycle, Leyline cycle, etc.).
  // Full semantics deferred to future waves; tolerated as canonical ids here.
  { id: "may_effect_from_opening_hand", displayName: "MayEffectFromOpeningHand", multipleRedundant: false },
  { id: "may_effect_from_opening_deck", displayName: "MayEffectFromOpeningDeck", multipleRedundant: false },
  // Synthetic keyword — catches any keyword text the parser does not
  // recognise canonically.  Full semantics are deferred to future waves.
  { id: "freeform", displayName: "Freeform", multipleRedundant: false },
] as const satisfies readonly KeywordMeta[];

export const KEYWORD_IDS = META.map((m) => m.id) as readonly KeywordMeta["id"][];
export type KeywordId = (typeof META)[number]["id"];

const BY_ID = new Map<string, KeywordMeta>(META.map((m) => [m.id, m]));
const BY_DISPLAY_LOWER = new Map<string, KeywordId>(
  META.map((m) => [m.displayName.toLowerCase(), m.id as KeywordId]),
);

export const isKeywordId = (value: string): value is KeywordId => BY_ID.has(value);

export const keywordDisplayName = (id: KeywordId): string => {
  const meta = BY_ID.get(id);
  if (!meta) throw new Error(`unknown KeywordId: ${id}`);
  return meta.displayName;
};

export const keywordIsMultipleRedundant = (id: KeywordId): boolean => {
  const meta = BY_ID.get(id);
  if (!meta) throw new Error(`unknown KeywordId: ${id}`);
  return meta.multipleRedundant;
};

export const keywordIdFromDisplayName = (name: string): KeywordId | null =>
  BY_DISPLAY_LOWER.get(name.toLowerCase()) ?? null;
